### ISSUE TITLE
vcffilter for AD field

### ISSUE THREAD

**Issue by lukewbonham** [vcflib/vcflib#100]
I'm trying to use vcffilter to filter out variants with an AD value below 20. I've tried applying it as:

 vcffilter  -g "AD > 20" name.vcf > ad_filtered.vcf

However, it looks like the filter is only being applied to the reference allele and not to the alternate. What would be the proper way to apply the filter to both alleles? I'm still very new to this so any help/pointers would be greatly appreciated!

**Comment by ekg** [comment]
What does the header say for AD?

**Comment by lukewbonham** [comment]
I pulled this from the header:
##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">

Here’s an example of what I’m seeing when I pull information from one of the variants in my data:
GT:AD:DP:GQ:PL
0/1:37,49:86:99:1391,0,974

Thanks!

**Comment by ekg** [comment]
This is not possible for vcflib to interpret correctly as it does not list
the number of alleles that it represents. Right now vcffilter understands
Number=A (one for each alternate allele) and Number=1. There is a new
standard for Number=R (for all alleles at the locus), but although I prefer
it I have not implemented it yet. Hope this helps.

**Comment by lukewbonham** [comment]
Thanks for the clarification!
