### ISSUE TITLE
Add an option to output version number

### ISSUE THREAD

**Issue by mfoll** [vcflib/vcflib#102]
It would be good to be able to display the git commit number in all tools. Like for example:

``` bash
vcfoverlay --version
vcflib 1.0.0-rc0-7f1575e
```

This is an important issue to build reproducible pipelines using vcflib.
See here for an example how to do that: http://stackoverflow.com/questions/6526451/how-to-include-git-commit-number-into-a-c-executable

**Comment by zeeev** [comment]
@mfoll It's late, but I've started adding the version number in the repo.  

The variable VERSION is populated in the Makefile. 

bin/vcfoverlay  -v
vcflib  v1.0.0-rc0-219-gc789-dirty

**Comment by zeeev** [comment]
Will continue to add versions. Currently there are versions for: 

 modified:   src/vcfcheck.cpp
 modified:   src/vcfcombine.cpp
 modified:   src/vcfgeno2haplo.cpp
 modified:   src/vcfinfosummarize.cpp
 modified:   src/vcfoverlay.cpp
