### ISSUE TITLE
Is that possible to use libvcflib.a directly with C++ project? 

### ISSUE THREAD

**Issue by joelshi** [vcflib/vcflib#107]
Hello all: 

I am a newbie here. We try to incorporate cvflib features into a program on Ubuntu 64bit OS. I can use 'make' to build every executable in bin folder. I find a libvcflib.a file in the root folder. I wonder if I can include it as a library plus the Varient.h into my software project.

It seems impossible since Varient.h depends on many other .h files in many subfolders all over the place. Can anyone shed some lights on how to incorporate this into a program, under Eclipse?

Or otherwise, we can only use cvflib individual executable in a pipeline fashion for downstream analysis?

Many thanks,

Joel

**Comment by zeeev** [comment]
You can use it as a library. You just need to specify the correct library folder to your compiler.
