### ISSUE TITLE
vcf2fasta fails with large vcf file

### ISSUE THREAD

**Issue by dvalenzu** [vcflib/vcflib#110]
Hi and  thanks for maintaining this library!

I'm trying to run vcf2fasta with data from 1000 genomes, something like:

./ext/vcflib/bin/vcf2fasta  -f hs37d5.fa ALL.chr21.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf 

And I'm getting the following error:

could not open HG01512_21:0.fasta for writing, exiting

I tried using a smaller vcf  file generated with vcf-subset ,containing around 90 samples,  
and it seems to works fine.
Any ideas ?

Best Regards, and thanks again,
Daniel

**Comment by dvalenzu** [comment]
Ok, so there are system limits to how many files you can have open simultaneously, see e.g.

http://www.gnu.org/software/libc/manual/html_node/Opening-Streams.html
http://www.gnu.org/software/libc/manual/html_node/General-Limits.html

**Comment by ekg** [comment]
Maybe it is opening too many files. What is your file handle limit? (Ulimit
something...)
