### ISSUE TITLE
vcffilter -g fails ?

### ISSUE THREAD

**Issue by kongdeju** [vcflib/vcflib#111]
when i run  
'''shell 
    zcat saw.vcf.gz | vcffilter -f " DP > 3 & MQ > 30"  -g " ! ( GT = 1/1 ) "
'''
the format column is replaced by a '.'

**Comment by ekg** [comment]
Try breaking these filter commands in two parts. First apply the -f filter
and then the -g.

**Comment by ghost** [comment]
Hi all, 

I want just filter out homozygous variants while keeping only heterozygous sites in the (one sample) vcf file. I used:
vcffilter  --genotype-filter  "GT = 0/0" my file.recode.vcf > file.vcf
In the file.vcf output, the number of SNPs present is the same as the original file and the column for that sample contains "." Why ?
Can someone provide me some suggestion?
Best 
anto

**Comment by ekg** [comment]
You need to use a site level filter to remove the sites that are non-het.
So there are a few ways that are more complex for the multi sample case.
For just a single diploid sample you can use `vcffilter -f 'AC = 1'` to
keep only heterozygous calls.

**Comment by ghost** [comment]
@ekg 

I will try tomorrow and will compare the files output with other I generated in other ways.
Thanks 
anto

**Comment by ghost** [comment]
@ekg 

I have implemented the vcffilter -f  'AC = 1' but it does not work. The output file is empty again.
Best
anto

**Comment by ekg** [comment]
What is the full command line you are using?

**Comment by ghost** [comment]
vcffilter -f 'AC = 1' -g 'GT = 0|0' my_example/input.vcf > output.vcf

**Comment by ghost** [comment]
also I tried other including 
vcffilter -f 'AC = 1'  my_example/input.vcf > output.vcf

**Comment by tseemann** [comment]
I am also having trouble with `vcffilter -g 'GT = 1'` not actually filtering, and putting `.` in the `INFO` section. I'll try and come up with a simple test case.

**Comment by zeeev** [comment]
@tseemann can you provide a small test case?

**Comment by tseemann** [comment]
```
##fileformat=VCFv4.1
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total read depth at the locus">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  snps
SEQ     1       .       T       A       999     .       DP=100  GT      1
SEQ     2       .       G       C       333     .       DP=33   GT      0
```

**Comment by tseemann** [comment]
The sample column `snps` is replaced with a `.` for the cases where GT=1 failed.

I think I was expecting the row to be removed. But I guess this doesn't make sense for a multi-sample VCF, and I need to post-filter the VCF to remove 'empty' rows like this?

`vcffilter -g "GT = 1" test-vcffilter.vcf`

```
##fileformat=VCFv4.1
##filter="genotypes filtered with: GT = 1"
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total read depth at the locus">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  snps
SEQ     1       .       T       A       999     .       DP=100  GT      1
SEQ     2       .       G       C       333     .       DP=33   GT      .
```

If I then use `-s`, the FORMAT _and_ sample column is totally removed for all the rows, and no rows are removed?

`vcffilter -s -g "GT = 1" test-vcffilter.vcf`

```
##fileformat=VCFv4.1
##filter="genotypes filtered with: GT = 1"
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total read depth at the locus">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  snps
SEQ     1       .       T       A       999     .       DP=100
SEQ     2       .       G       C       333     .       DP=33
```

**Comment by ekg** [comment]
-f removes alleles unless the tag pass argument is given. -g removes the
sample genotype fields when they do not match the filter pattern.

**Comment by tseemann** [comment]
@ekg Should the --tag-pass argument go into each row in the FILTER column?

Because it doesn't seem to - it just adds a row to the # header.
