### ISSUE TITLE
vcffirstheader

### ISSUE THREAD

**Issue by yaseen-ladak** [vcflib/vcflib#114]
Hi @ekg 

I am trying to use vcflib after running freebayes.
1. I am a bit confused about the use of vcffirstheader  when do you use this? Freebayes give out the vcf.
2. Also, if there a  tool in vcflib that would breakdown my genotype field when I am using multiple inputs to freebayes to relevant bases rather than 0/1 or 1/1 or 0/2 etc Do i need to decompose the vcf file before using any other tool?
3. Also whats the use of using vt normalise?

Your help is very very much appreciated.

Thanks,

**Comment by yaseen-ladak** [comment]
Hello @ekg 

I would grateful appreciate a little help here.

I got the VCF files from freebayes after I input various BAM files to it. In the genotype field for each sample I get the 0/1 or 0/2 etc.

1) When is it necessary to use vcffirstheader? I read on some forums but very confused.

2) The next step would be to run vcffilter to remove variants that have QC< 20  followed by vcfallelicprimitives followed by vt decompose and and then vt normalise ? 

3) After vt normalize I do the annotation.

Look forward to hearing from you.

Kind regards,
Yaseen Ladak

**Comment by yaseen-ladak** [comment]
Hello @ekg 

I am sorry I need your help not many people around me to guide me. I hope  someone can from here 

1) I dont know what vcffirstheader is and I have seen in forums so I just wanted to make sure that I am not missing any step.

2) My goal is that when I get the VCF file after adding read groups it shows me sample_1 sample_2 sample_3. It has genotypes for each sample as you had explained before  1/0, 0/0 0/2 etc. So instead of having these as numbers I would actually like to have the bases like A/T, T/T, T,A as I need to make an excel sheet and share if with the biologists and they wont understand 1/0, 0/0 etc. I have marked this in red in fields below from three samples i.e. 3 BAM files input to freebayes after adding read groups. Is this doable with vcflib? Example below. 

#CHROM POS ID REF ALT QUAL FILTER INFO FORMAT sample_1 sample_2 sample_3
readseq-I20150421-153209-0786-82917222-es_sequence_1    489 .   A   G   298.546 .   AB=0;ABP=0;AC=6;AF=1;AN=6;AO=18;CIGAR=1X;DP=23;DPB=23;DPRA=0;EPP=42.0968;EPPR=0;GTI=0;LEN=1;MEANALT=2;MQM=37.8889;MQMR=0;NS=3;NUMALT=1;ODDS=10.1895;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=547;QR=0;RO=0;RPL=0;RPP=42.0968;RPPR=0;RPR=18;RUN=1;SAF=18;SAP=42.0968;SAR=0;SRF=0;SRP=0;SRR=0;TYPE=snp;technology.illumina_hi-seq=1  GT:DP:RO:QR:AO:QA:GL    1/1:2:0:0:1:33:-2.92817,-0.30103,0  1/1:16:0:0:13:391:-34.6672,-3.91339,0   1/1:5:0:0:4:123:-8.51485,-1.20412,0

3) I under stand what happens when we normalise vcf but what exactly is the need for this? Does vcflib have something similar to vt?

Thanks a lot
Yaseen

**Comment by tseemann** [comment]
`vcffirstheader` takes concatenated VCF files and ouputs a single VCF file with just the header from the first VCF file but the data lines from _all_ the VCF files. 

This is needed when to run freebayes on separate regions of your genome (in parallel for example) but want to combine the result into a single VCF file for downstream processing.

**Comment by yaseen-ladak** [comment]
@tseemann 

Thank you very much.
