### ISSUE TITLE
can not install vcflib

### ISSUE THREAD

**Issue by ichobits** [vcflib/vcflib#119]
After make command.
The error message:

g++ -O3 -D_FILE_OFFSET_BITS=64 -c Fasta.cpp
Fasta.cpp: In member function ‘std::string FastaReference::getSequence(std::string)’:
Fasta.cpp:254:43: warning: ignoring return value of ‘size_t fread(void_, size_t, size_t, FILE_)’, declared with attribute warn_unused_result [-Wunused-result]
     fread(seq, sizeof(char), seqlen, file);
                                           ^
Fasta.cpp: In member function ‘std::string FastaReference::getSubSequence(std::string, int, int)’:
Fasta.cpp:301:51: warning: ignoring return value of ‘size_t fread(void_, size_t, size_t, FILE_)’, declared with attribute warn_unused_result [-Wunused-result]
     fread(seq, sizeof(char), (off_t) seqlen, file);
                                                   ^
g++ -O3 -D_FILE_OFFSET_BITS=64 -c split.cpp
g++ -O3 -D_FILE_OFFSET_BITS=64 -c disorder.c
g++ -O3 -D_FILE_OFFSET_BITS=64 Fasta.o FastaHack.cpp split.o disorder.o -o fastahack
make[1]: Leaving directory `/home/steven/soft/vcflib/fastahack'
g++ -O3 -D_FILE_OFFSET_BITS=64 -std=c++0x -DVERSION=\"v1.0.0-rc0-163-g9aba\"   -c -o smithwaterman/disorder.o smithwaterman/disorder.cpp
cc    -c -o src/ssw.o src/ssw.c
g++ -O3 -D_FILE_OFFSET_BITS=64 -std=c++0x -DVERSION=\"v1.0.0-rc0-163-g9aba\"   -c -o src/ssw_cpp.o src/ssw_cpp.cpp
ar rs libvcflib.a src/Variant.o src/rnglib.o src/var.o src/pdflib.o src/cdflib.o src/split.o smithwaterman/sw.o fastahack/Fasta.o src/ssw.o src/ssw_cpp.o filevercmp/filevercmp.o tabixpp/tabix.o
ar: creating libvcflib.a
cp libvcflib.a lib
cd intervaltree && make && cp *.h* /home/steven/soft/vcflib/include/
make[1]: Entering directory`/home/steven/soft/vcflib/intervaltree'
g++ -Wall interval_tree_test.cpp -o interval_tree_test -std=c++0x
make[1]: Leaving directory `/home/steven/soft/vcflib/intervaltree'
g++ src/vcfecho.cpp -o bin/vcfecho -Itabixpp/htslib -Iinclude -L. -Ltabixpp/htslib -Llib -lvcflib -lhts -lpthread -lz -lm -O3 -D_FILE_OFFSET_BITS=64 -std=c++0x -DVERSION=\"v1.0.0-rc0-163-g9aba\"
g++ src/dumpContigsFromHeader.cpp -o bin/dumpContigsFromHeader -Itabixpp/htslib -Iinclude -L. -Ltabixpp/htslib -Llib -lvcflib -lhts -lpthread -lz -lm -O3 -D_FILE_OFFSET_BITS=64 -std=c++0x -DVERSION=\"v1.0.0-rc0-163-g9aba\"

src/dumpContigsFromHeader.cpp:11:17: error: ‘vcf’ is not a namespace-name
 using namespace vcf;
                 ^
src/dumpContigsFromHeader.cpp:11:20: error: expected namespace-name before ‘;’ token
 using namespace vcf;
                    ^
src/dumpContigsFromHeader.cpp: In function ‘int main(int, char*_)’:
src/dumpContigsFromHeader.cpp:17:3: error: ‘VariantCallFile’ was not declared in this scope
   VariantCallFile variantFile;
   ^
src/dumpContigsFromHeader.cpp:17:3: note: suggested alternative:
In file included from src/dumpContigsFromHeader.cpp:1:0:
src/Variant.h:54:7: note:   ‘vcflib::VariantCallFile’
 class VariantCallFile {
       ^
src/dumpContigsFromHeader.cpp:17:19: error: expected ‘;’ before ‘variantFile’
   VariantCallFile variantFile;
                   ^
src/dumpContigsFromHeader.cpp:19:3: error: ‘variantFile’ was not declared in this scope
   variantFile.open(filename);
   ^
make: *_\* [bin/dumpContigsFromHeader] Error 1

**Comment by zeeev** [comment]
looking into it.

**Comment by NikTuzov** [comment]
You decided to rename namespace vcf into vcflib, but in many *.cpp files vcf is still used. Don't you try to compile the whole thing after each commit?

**Comment by NikTuzov** [comment]
After I renamed vcf to vcflib, the compilation fails because optind is not defined. I fixed this by including getopt.h

**Comment by zeeev** [comment]
@NikTuzov thank you for your time.  My pull request generated these issues.  The Travis-CI build test was in my pull request, but it requires that @ekg adds the repo to his Travis-CI.  I'm almost done fixing the build bugs.  Can you tell me which file requires getopt.h?

**Comment by zeeev** [comment]
The repo is building.  I was unable to generate the "optind" error.  @NikTuzov please let me know the specifics of that bug and I will fix it.

**Comment by NikTuzov** [comment]
I had to include getopt.h in vcfhetcount.cpp.

**Comment by zeeev** [comment]
@NikTuzov Thanks again.
