### ISSUE TITLE
vcfallelicprimitives throws an exception when applied to SAMTools output

### ISSUE THREAD

**Issue by NikTuzov** [vcflib/vcflib#120]
Hello:

I am trying to regularize this VCF file from SAMTools and I get the following error:

parsedAlternates: alignment does not start with match over padded sequence
1M22S
ZZZZZZZZZZQatgtZZZZZZZZZZ
ZZZZZZZZZZQgtZZZZZZZZZZ

Please help.

Regards,
Nik

**Comment by NikTuzov** [comment]
I also tried using SAMTools on the same input data, but restricted to SNV calls only. In that case vcfallelicprimitives works fine, so the error is caused by some indel. I attached the file that causes the error.

[Bowtie2_SAMTools_gcat_set_025.vcf.gz](https://github.com/ekg/vcflib/files/69873/Bowtie2_SAMTools_gcat_set_025.vcf.gz)

**Comment by zeeev** [comment]
@NikTuzov I modified a subroutine in the library that **may** solve this issue.  If you'd be willing to give it another go?
