### ISSUE TITLE
vcfaddinfo on gzipped (bgzipped) files

### ISSUE THREAD

**Issue by gpcr** [vcflib/vcflib#123]
is there an option for using vcfaddinfo on two large zipped vcf files?

**Comment by ekg** [comment]
No, but you are not stuck. Divide the large files into small regions and
run it at that scale, then concatenate the results.

**Comment by gpcr** [comment]
@ekg : that is my current practice: unfortunately my compressed VCFs are way too large (1.5TB; >50K individuals)

**Comment by ekg** [comment]
Why not use tabix? It should be quick to subset them even at that scale.

**Comment by gpcr** [comment]
yaa using tabix itself; without tabix life will be miserable dealing these files
