### ISSUE TITLE
problem with 'make'

### ISSUE THREAD

**Issue by laurenvw** [vcflib/vcflib#125]
Hi,
I used git clone --recursive git://github.com/ekg/vcflib.git to get vcflib onto my computer Mac OS X Yosemite, and I keep getting this error at the end:

1 error generated.
make: **\* [bin/hapLrt] Error 1

I've tried a fresh clone and make and I still have the same problem... Any advice?

**Comment by zeeev** [comment]
Can you post the full error?

**Comment by laurenvw** [comment]
Thanks, but I wound up just using home brew to install it in the end, and it worked no problem.
