### ISSUE TITLE
Can you make a v1.0.0-rc1 tag please?

### ISSUE THREAD

**Issue by tseemann** [vcflib/vcflib#131]
There have been a few important bug fixes since `v1.0.0-rc0` eg. memory leak.

I would like to update the Brew package.

It would be great if you could just add a tag `v1.0.0-rc1` (not a release) to aid in packaging.

**Comment by ekg** [comment]
Done! https://github.com/vcflib/vcflib/releases/tag/v1.0.0-rc1
