### ISSUE TITLE
vcffixup not working with new commit

### ISSUE THREAD

**Issue by leandrogneves** [vcflib/vcflib#133]
Hello Erik.

I installed the new commit today and observed an issue while running vcffixup that I did not have with the same files and command options in the previous version I have on my machine.

With old version:
$ vcffilter --genotype-filter "! ( DP < 100 )"  $INPUT | vcffixup - | vcffilter --info-filter "NS > 2" |  grep -cv "^#" 
40682

With current version
$ vcffilter --genotype-filter "! ( DP < 100 )"  $INPUT | vcffixup - | vcffilter --info-filter "NS > 2" |  grep -cv "^#"
92112

$ grep -cv "^#" $INPUT
92112

vcffixup is not adjusting the NS field and, therefore, not filtering SNPs off. 

It seems like the way missing information is reported changed from "." to "./."  and could be causing the problem.

With old version
$ vcffilter --genotype-filter "! ( DP < 100 )"  $INPUT | vcffixup - | grep -v "^#" | head -n 1
ref1    20  .   T   C   12.3696 .   AB=0.15;ABP=66.8516;AC=0;AF=-nan;AN=0;AO=9;CIGAR=1X;DP=296;DPB=296;DPRA=1.39831;EPP=14.8328;EPPR=25.8978;GTI=1;LEN=1;MEANALT=1;MQM=33.1111;MQMR=33.9861;NS=0;NUMALT=1;ODDS=2.69144;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=356;QR=11215;RO=287;RPL=0;RPP=22.5536;RPPR=626.223;RPR=9;RUN=1;SAF=1;SAP=14.8328;SAR=8;SRF=116;SRP=25.8978;SRR=171;TYPE=snp;technology.illumina=1  GT:GQ:DP:DPR:RO:QR:AO:QA    .   .   .   .   .   .   .   .   .   .   .   .   .

With new version:
$ vcffilter --genotype-filter "! ( DP < 100 )"  $INPUT | vcffixup - | grep -v "^#" | head -n 1
 ref1   20  .   T   C   12.3696 .   AB=0.15;ABP=66.8516;AC=0;AF=-nan;AN=0;AO=9;CIGAR=1X;DP=296;DPB=296;DPRA=1.39831;EPP=14.8328;EPPR=25.8978;GTI=1;LEN=1;MEANALT=1;MQM=33.1111;MQMR=33.9861;NS=13;NUMALT=1;ODDS=2.69144;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=356;QR=11215;RO=287;RPL=0;RPP=22.5536;RPPR=626.223;RPR=9;RUN=1;SAF=1;SAP=14.8328;SAR=8;SRF=116;SRP=25.8978;SRR=171;TYPE=snp;technology.illumina=1 GT:GQ:DP:DPR:RO:QR:AO:QA    ./.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.

I can send test file and provide more information if needed, but I thought I would ask if something simple changed that you can spot. 

Thanks again for writing these tools!
Cheers
Leandro

**Comment by zeeev** [comment]
Please send a test file.
