### ISSUE TITLE
Merging 3000 VCFs using vcflib

### ISSUE THREAD

**Issue by riyuebao** [vcflib/vcflib#137]
Hi Erik,

Thanks for developing FreeBayes and vcflib and pointing us to vt. We have been using those tools in our pipelines and they worked really good.

I have a quick question about vcflib and was wondering if you could help me. We have 3,000 whole exome VCFs (each with multiple samples) that we have to make them merge into one VCF. I really liked vcflib and how it works. Would you think if vcflib could handle this amount of VCF merging, and if yes, how long time and how much memory would you think it might need? We tried GATK CombineVariants and it estimates over 15 weeks…. Any advice will be highly appreciated!

Thank you very much in advance.

Best,
Riyue Bao
Senior Bioinformatician 
Center for Research Informatics | Biological Sciences Division 
The University of Chicago

**Comment by zeeev** [comment]
I assume they are compressed and tabix indexed?

**Comment by timknut** [comment]
I find bcftools on bgzipped and tabixed vcfs to be the most efficient software for merging.
If phase is not important, plink2 could also work.

**Comment by riyuebao** [comment]
@zeeev Yup they are bgzip compressed and tabix indexed.
@timknut Thanks!! We did not do phasing. Sounds bcftools would be good way to go :)

**Comment by timknut** [comment]
3000 is a lot of files. If possible, would split into many jobs.

**Comment by riyuebao** [comment]
@timknut Thanks~! Yes it is a lot... Would you suggest splitting each VCF by region, for example, into even bins of 25,000bp? That probably can break the one job into 50-100 jobs, each merging VCFs with variants within that bin. At the end we would have to concatenate them all together into one output.

**Comment by krttrr** [comment]
I've successfully merged 25k WES VCFs with bcftools but did it in small batches of 1k each then merged the smaller batches. This was much more efficient than attempting to merge the whole batch at once (I started up a job for this but gave up after letting it run for 2 weeks whereas the other method finished in a few days).
The information transmitted in this email and any of its attachments is intended only for the person or entity to which it is addressed and may contain GeneDx proprietary information, which is privileged, confidential, or subject to copyright belonging to GeneDx. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited and may be unlawful. If you received this in error, please contact the sender immediately and delete and destroy the communication and all of the attachments you have received and all copies thereof.

**Comment by riyuebao** [comment]
@krttrr That is really useful information!! Thank you so much for sharing this. We will try this first on our cloud :)

**Comment by timknut** [comment]
Krttrr approach was what I had in mind :) Good luck!

**Comment by riyuebao** [comment]
@timknut Thank you!!! :)

**Comment by zeeev** [comment]
Closing as an issue.
