### ISSUE TITLE
vcfgeno2haplo bailing on toy vcf

### ISSUE THREAD

**Issue by iqbal-lab** [vcflib/vcflib#138]
-bash-4.1$ cat ref1.fa

> 1
> TTGACCGATGACCCCGGTTCAGGCTTCACCACAGTGTGGAACGCGGTCGTCTCCGAACTTAACGGCGACCCTAAGGTTGACGACGGACCCAGCAGTGATGCTAATCTCAGCGCTCCGCTGACCCCTCAGCAAAGGGCTTGGCTCAATCTCGTCCAGCCATTGACCATCGTCGAGGGGTTTGCTCTGTTATCCGTGCCGAGCAGCTTTGTCCAAAACGAAATCGAGCGCCATCTGCGGGCCCCGATTACCGACGCTCTCAGCCGCCGACTCGGACATCAGATCCAACTCGGGGTCCGCATCGCTCCGCCGGCGACCGACGAAGCCGACGACACTACCGTGCCGCCTTCCGAAAATCCTGCTACCACATCGCCAGACACCACAACCGACAACGACGAGATTGATGACAGCGCTGCGGCACGGGGCGATAACCAGCACAGTTGGCCAAGTTACTTCACCGAGCGCCCGCACAATACCGATTCCGCTACCGCTGGCGTAACCAGCCTTAACCGTCGCTACACCTTTGATACGTTCGTTATCGGCGCCTCCAACCGGTTCGCGCACGCCGCCGCCTTGGCGATCGCAGAAGCACCCGCCCGCGCTTACAACCCCCTGTTCATCTGGGGCGAGTCCGGTCTCGGCAAGACACACCTGCTACACGCGGCAGGCAACTATGCCCAACGGTTGTTCCCGGGAATGCGGGTCAAATATGTCTCCACCGAG
> -bash-4.1$ 
> -bash-4.1$ cat test1.vcf
> ## fileformat=VCFv4.0
> ## FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
> # CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  MickeyMouse
> 
> 1   100 var1    G   T   .   PASS    .   GT  1
> 1   200 var2    G   C   .   PASS    .   GT  1
> 1   202 var3    A   C   .   PASS    .   GT  1
> 1   204 var4    CTT GCG .   PASS    .   GT  0
> 1   207 var5    TG  GA  .   PASS    .   GT  1
> 1   300 var6    CGC AAT .   PASS    .   GT  1
> 1   304 var7    CCGCCGGCGA  C   .   PASS    .   GT  1
> 1   320 var8    A       T   PASS    .   GT  1
> -bash-4.1$ 

vcfgeno2haplo -r ref1.fa -w 31 test1.vcf
## FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
# CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  MickeyMouse

1   100 var1    G   T   0   PASS    .   GT  1
unable to find FASTA index entry for '1'

**Comment by ekg** [comment]
First line in the fasta should be ">1". Does that help?

**Comment by zeeev** [comment]
@iqbal-lab : Did @ekg 's suggestion work?  If so let's close the issue.

**Comment by iqbal-lab** [comment]
Sorry I did not see Erik's comment until now! Will check if the > is there in the original, or if I just failed to copy it into the bug report.

**Comment by zeeev** [comment]
@iqbal-lab no problem.  Can you try indexing the fasta with fastahack/fastahack prior to running vcfgeno2haplo?

If it's a matter of a missing fasta index, I'll add automatic indexing to vcfgeno2haplo.

Thank you for the report!

**Comment by iqbal-lab** [comment]
OK, is a bit complicated. The > may have been missing from the fasta, sorry - I think I may have added it since the bug report. However, now when I run it I get this

 cat test1.vcf 
##fileformat=VCFv4.0
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  MickeyMouse
1   100 var1    G   T   .   PASS    .   GT  1
1   200 var2    G   C   .   PASS    .   GT  1
1   202 var3    A   C   .   PASS    .   GT  1
1   204 var4    CTT GCG .   PASS    .   GT  0
1   207 var5    TG  GA  .   PASS    .   GT  1
1   300 var6    CGC AAT .   PASS    .   GT  1
1   304 var7    CCGCCGGCGA  C   .   PASS    .   GT  1
1   320 var8    A       T   PASS    .   GT  1

cat ref1.fa

> 1
> TTGACCGATGACCCCGGTTCAGGCTTCACCACAGTGTGGAACGCGGTCGTCTCCGAACTTAACGGCGACCCTAAGGTTGACGACGGACCCAGCAGTGATGCTAATCTCAGCGCTCCGCTGACCCCTCAGCAAAGGGCTTGGCTCAATCTCGTCCAGCCATTGACCATCGTCGAGGGGTTTGCTCTGTTATCCGTGCCGAGCAGCTTTGTCCAAAACGAAATCGAGCGCCATCTGCGGGCCCCGATTACCGACGCTCTCAGCCGCCGACTCGGACATCAGATCCAACTCGGGGTCCGCATCGCTCCGCCGGCGACCGACGAAGCCGACGACACTACCGTGCCGCCTTCCGAAAATCCTGCTACCACATCGCCAGACACCACAACCGACAACGACGAGATTGATGACAGCGCTGCGGCACGGGGCGATAACCAGCACAGTTGGCCAAGTTACTTCACCGAGCGCCCGCACAATACCGATTCCGCTACCGCTGGCGTAACCAGCCTTAACCGTCGCTACACCTTTGATACGTTCGTTATCGGCGCCTCCAACCGGTTCGCGCACGCCGCCGCCTTGGCGATCGCAGAAGCACCCGCCCGCGCTTACAACCCCCTGTTCATCTGGGGCGAGTCCGGTCTCGGCAAGACACACCTGCTACACGCGGCAGGCAACTATGCCCAACGGTTGTTCCCGGGAATGCGGGTCAAATATGTCTCCACCGAG

 ~/dev/git/vcflib/bin/vcfgeno2haplo -r ref1.fa -w 31 test1.vcf
index file ref1.fa.fai not found, generating...
##fileformat=VCFv4.0
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  MickeyMouse
1   100 var1    G   T   0   PASS    .   GT  1
1   200 .   GCAGCTTTG   CCCGCTTGA   6.93525e-310    .   GT  1
1   300 .   CGCTCCGCCGGCGACCGACGA   AATTCCCGACG 6.93525e-310    GT  1

So this looks good! I think OK to close bug.

**Comment by iqbal-lab** [comment]
i should have closed this
