### ISSUE TITLE
vcffilter -t and -F flags aren't behaving as flags

### ISSUE THREAD

**Issue by tseemann** [vcflib/vcflib#139]
It seems `vcffilter -t` or `vcffilter --tag-pass` don't work - they are expecting a parameter?
They seem to work if I use `vcffilter --tag-pass 1`.
This problem does not seem to affect the other flags `-k` and `-s`.

```
usage: vcffilter [options] <vcf file>
    -k, --keep-info       used in conjunction with '-g', keeps variant info, but removes genotype
    -s, --filter-sites    filter entire records, not just alleles
    -t, --tag-pass        tag vcf records as positively filtered with this tag, print all records
    -F, --tag-fail        tag vcf records as negatively filtered with this tag, print all records
```

**Comment by zeeev** [comment]
Looking into it.

**Comment by tseemann** [comment]
I've looked at the code and it seems it is a longopt `required_argument`.

It is expecting things like `''` or `PASS`.

The code actually fills in these default values for `-F` and `-t` if they have an empty value, but it's not possible to actually give an empty value from the command line.

They probably need to be tagged as `optional_argument` for getopt, but then may need different logic in the parsing section as `optarg` will be `NULL` in some cases.  

Maybe just leave it as-is but improve the help information?

**Comment by ekg** [comment]
Why would you want the empty value?

**Comment by tseemann** [comment]
We need to pass an empty value to get it to use the default values - as an argument is required?
