### ISSUE TITLE
Where did vcffirstheader, vcfsort etc scripts disappear to?

### ISSUE THREAD

**Issue by tseemann** [vcflib/vcflib#142]
It seems a bunch of helper scripts have disappeared from vcflib since it moved from ekg to vcflib.

eg. vcffirstheader, vcfsort etc

Is this deliberate or an accident?

**Comment by zeeev** [comment]
@ekg might have to field this one.  It's possible i accidentally removed them.

**Comment by tseemann** [comment]
We build brew packages of vcflib which uses them - here is the current tag we use that contains them:

```
 :tag => "v1.0.0-rc0", :revision => "8ac9fd517579134ef3b9797714d20c9c99c18ec6"
```

**Comment by zeeev** [comment]
Were they in bin?

**Comment by tseemann** [comment]
Yes  they were. In fact this has happened before too :-)

See https://github.com/ekg/freebayes/issues/120

**Comment by zeeev** [comment]
@tseemann if we made a new folder would that be easier or harder for you?

**Comment by tseemann** [comment]
Hmmm, I just realised they must be part of freebayes not vcflib!

**Comment by tseemann** [comment]
No, I'm wrong. 'vcffirstheader` used to be in the `bin` folder of `vcflib`.

**Comment by zeeev** [comment]
@tseemann How about putting them into a utils/ folder ?

**Comment by tseemann** [comment]
Another example is `vcfsort`. They are at the same 'level' to the compiled vcf\* tools, they just happen to be implemented as shell or python scripts. They should end up in the same place you would install the compiled binaries to.   They used to be in `bin`. If you change that, you'll break all the packages out there eg. Debian, RPM, Brew, Conda etc.  
But I guess if you _need_ to change it, it's best to do it before official 1.0.0 version.

**Comment by zeeev** [comment]
@tseemann Nope. Wouldn't want to break anything.  I'll track them down and put them into the bin folder. Sorry about that.

**Comment by tseemann** [comment]
Here are just some of the commands you should be able to recover:
- vcffirstheader
- vcfsort
- vcfsnps
- vcfsort
- vcfremovenonAGTC
- vcfqualfilter
- vcfregionreduce
- vcfclearinfo
- vcfclearid

Thanks for getting onto this so fast!

**Comment by zeeev** [comment]
@tseemann Is this the full list?  I'd like to get them all now.

**Comment by tseemann** [comment]
No it's not the full list. There were other `.sh` files and `.r` files. 

Here's the commit we use to build the Brew package and it's bin folder:

https://github.com/vcflib/vcflib/tree/8ac9fd517579134ef3b9797714d20c9c99c18ec6/bin

**Comment by ekg** [comment]
Seems these have disappeared. They should be back in the git history though.

**Comment by tseemann** [comment]
Well I look forward to their return.

**Comment by zeeev** [comment]
@tseemann, @ekg and I have decided to clear out bin (including my R scripts).  All non cpp code can be found in "scripts".  This includes everything in https://github.com/vcflib/vcflib/tree/8ac9fd517579134ef3b9797714d20c9c99c18ec6/bin

**Comment by nh13** [comment]
@zeeev thanks for adding these back, but for folks who rely on them being in a specific place, this is a breaking change, and not so welcome.

**Comment by zeeev** [comment]
@ekg what do you think? @nh13 what does the new path break?

**Comment by tseemann** [comment]
@zeeev @akg I am frustrated  that you have moved those into the `scripts/` folder. They are still "first class" commands in the `vcflib` hierarchy, equivalent in use to the binaries. It just doesn't make any sense to demote them - you've broken the API based on language source. This is a major compatibility break.

**Comment by ekg** [comment]
I think the concern is that it makes it easier to clean the repo if the
scripts are in their own directory. Can we add a command that copies them
into the bin during make?

**Comment by zeeev** [comment]
@ekg @tseemann @nh13 I'll add the command to the make file, it will be default, sometime this afternoon. To be clear there was no demotion, I'm not biased against non complied code. Had I known this was such a big issue I wouldn't have made a scripts folder.

**Comment by zeeev** [comment]
Resolved.
