### ISSUE TITLE
vcfannotategenotypes loses phasing information

### ISSUE THREAD

**Issue by gusevfe** [vcflib/vcflib#143]
It seems like `vcfannotategenotypes` does not transfer over phasing of alleles. Is this by design?

Here I annotate genotypes using two identical files and but phasing is not present for annotated genotype .

```
tabix -h ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr20.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz 20:60571-60571 | vcfkeepsamples - NA19376 | vcfkeepinfo - AF > a.vcf
cp a.vcf b.vcf
vcfannotategenotypes OTHER a.vcf b.vcf | tail -n 1
```

The output of the last command is

```
20      60571   rs116145529     C       A       100     PASS    AF=0.00199681;OTHER.has_variant GT:OTHER        1|0:0/1
```

I expect the transferred annotation `OTHER` to match `GT`, but, as you see, the value in FORMAT tag `OTHER` does not match the expected `1|0`. Is this a bug or not?

**Comment by ekg** [comment]
Strange, I thought it was directly taking the genotypes from the other
file. Maybe they are getting parsed somehow.

**Comment by gusevfe** [comment]
Nope, it maps alleles from the second file onto alleles present in the first file and loses phasing on the way. See pull request for a possible fix.
