### ISSUE TITLE
Installing problem in Ubuntu

### ISSUE THREAD

**Issue by nachoseret** [vcflib/vcflib#150]
I get this error when attempting to compile vclib. I'm running Xubuntu 15.04 and followed the instructions in README.md
Everything goes fine until this:

Fasta.cpp: In member function ‘std::string FastaReference::getSequence(std::string)’:
Fasta.cpp:254:43: warning: ignoring return value of ‘size_t fread(void_, size_t, size_t, FILE_)’, declared with attribute warn_unused_result [-Wunused-result]
     fread(seq, sizeof(char), seqlen, file);
                                           ^
Fasta.cpp: In member function ‘std::string FastaReference::getSubSequence(std::string, int, int)’:
Fasta.cpp:301:51: warning: ignoring return value of ‘size_t fread(void_, size_t, size_t, FILE_)’, declared with attribute warn_unused_result [-Wunused-result]
     fread(seq, sizeof(char), (off_t) seqlen, file);
                                                   ^
g++ -O3 -D_FILE_OFFSET_BITS=64 -c split.cpp
g++ -O3 -D_FILE_OFFSET_BITS=64 -c disorder.c
g++ -O3 -D_FILE_OFFSET_BITS=64 Fasta.o FastaHack.cpp split.o disorder.o -o fastahack
make[1]: Leaving directory '/home/nacho/IBR/vcflib/fastahack'
g++ -O3 -D_FILE_OFFSET_BITS=64 -std=c++0x    -c -o smithwaterman/disorder.o smithwaterman/disorder.cpp
cc    -c -o src/ssw.o src/ssw.c
src/ssw.c: In function ‘sw_sse2_byte’:
src/ssw.c:128:10: warning: SSE vector return without SSE enabled changes the ABI [-Wpsabi]
  __m128i vZero = _mm_set1_epi32(0);
          ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:633:1: error: inlining failed in call to always_inline ‘_mm_set1_epi32’: target specific option mismatch
 _mm_set1_epi32 (int __A)
 ^
src/ssw.c:128:10: error: called from here
  __m128i vZero = _mm_set1_epi32(0);
          ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:645:1: error: inlining failed in call to always_inline ‘_mm_set1_epi8’: target specific option mismatch
 _mm_set1_epi8 (char __A)
 ^
src/ssw.c:137:10: error: called from here
  __m128i vGapO = _mm_set1_epi8(weight_gapO);
          ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:645:1: error: inlining failed in call to always_inline ‘_mm_set1_epi8’: target specific option mismatch
 _mm_set1_epi8 (char __A)
 ^
src/ssw.c:140:10: error: called from here
  __m128i vGapE = _mm_set1_epi8(weight_gapE); 
          ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:645:1: error: inlining failed in call to always_inline ‘_mm_set1_epi8’: target specific option mismatch
 _mm_set1_epi8 (char __A)
 ^
src/ssw.c:143:10: error: called from here
  __m128i vBias = _mm_set1_epi8(bias); 
          ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:686:1: error: inlining failed in call to always_inline ‘_mm_load_si128’: target specific option mismatch
 _mm_load_si128 (__m128i const ___P)
 ^
src/ssw.c:178:9: error: called from here
    vH = _mm_adds_epu8(vH, _mm_load_si128(vP + j));
         ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1043:1: error: inlining failed in call to always_inline ‘_mm_adds_epu8’: target specific option mismatch
 _mm_adds_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:178:7: error: called from here
    vH = _mm_adds_epu8(vH, _mm_load_si128(vP + j));
       ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1091:1: error: inlining failed in call to always_inline ‘_mm_subs_epu8’: target specific option mismatch
 _mm_subs_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:179:7: error: called from here
    vH = _mm_subs_epu8(vH, vBias); /_ vH will be always > 0 _/
       ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:686:1: error: inlining failed in call to always_inline ‘_mm_load_si128’: target specific option mismatch
 _mm_load_si128 (__m128i const *__P)
 ^
src/ssw.c:187:6: error: called from here
    e = _mm_load_si128(pvE + j);
      ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1368:1: error: inlining failed in call to always_inline ‘_mm_max_epu8’: target specific option mismatch
 _mm_max_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:188:7: error: called from here
    vH = _mm_max_epu8(vH, e);
       ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1368:1: error: inlining failed in call to always_inline ‘_mm_max_epu8’: target specific option mismatch
 _mm_max_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:189:7: error: called from here
    vH = _mm_max_epu8(vH, vF);
       ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1368:1: error: inlining failed in call to always_inline ‘_mm_max_epu8’: target specific option mismatch
 _mm_max_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:190:15: error: called from here
    vMaxColumn = _mm_max_epu8(vMaxColumn, vH);
               ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:704:1: error: inlining failed in call to always_inline ‘_mm_store_si128’: target specific option mismatch
 _mm_store_si128 (__m128i *__P, __m128i __B)
 ^
src/ssw.c:197:4: error: called from here
    _mm_store_si128(pvHStore + j, vH);
    ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1091:1: error: inlining failed in call to always_inline ‘_mm_subs_epu8’: target specific option mismatch
 _mm_subs_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:200:7: error: called from here
    vH = _mm_subs_epu8(vH, vGapO); /_ saturation arithmetic, result >= 0 _/
       ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1091:1: error: inlining failed in call to always_inline ‘_mm_subs_epu8’: target specific option mismatch
 _mm_subs_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:201:6: error: called from here
    e = _mm_subs_epu8(e, vGapE);
      ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1368:1: error: inlining failed in call to always_inline ‘_mm_max_epu8’: target specific option mismatch
 _mm_max_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:202:6: error: called from here
    e = _mm_max_epu8(e, vH);
      ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:704:1: error: inlining failed in call to always_inline ‘_mm_store_si128’: target specific option mismatch
 _mm_store_si128 (__m128i *__P, __m128i __B)
 ^
src/ssw.c:203:4: error: called from here
    _mm_store_si128(pvE + j, e);
    ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1091:1: error: inlining failed in call to always_inline ‘_mm_subs_epu8’: target specific option mismatch
 _mm_subs_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:206:7: error: called from here
    vF = _mm_subs_epu8(vF, vGapE);
       ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1368:1: error: inlining failed in call to always_inline ‘_mm_max_epu8’: target specific option mismatch
 _mm_max_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:207:7: error: called from here
    vF = _mm_max_epu8(vF, vH);
       ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:686:1: error: inlining failed in call to always_inline ‘_mm_load_si128’: target specific option mismatch
 _mm_load_si128 (__m128i const *__P)
 ^
src/ssw.c:210:7: error: called from here
    vH = _mm_load_si128(pvHLoad + j);
       ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:686:1: error: inlining failed in call to always_inline ‘_mm_load_si128’: target specific option mismatch
 _mm_load_si128 (__m128i const *__P)
 ^
src/ssw.c:216:12: error: called from here
         vH = _mm_load_si128 (pvHStore + j);
            ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1091:1: error: inlining failed in call to always_inline ‘_mm_subs_epu8’: target specific option mismatch
 _mm_subs_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:222:15: error: called from here
         vTemp = _mm_subs_epu8 (vH, vGapO);
               ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1091:1: error: inlining failed in call to always_inline ‘_mm_subs_epu8’: target specific option mismatch
 _mm_subs_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:223:9: error: called from here
   vTemp = _mm_subs_epu8 (vF, vTemp);
         ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1288:1: error: inlining failed in call to always_inline ‘_mm_cmpeq_epi8’: target specific option mismatch
 _mm_cmpeq_epi8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:224:9: error: called from here
   vTemp = _mm_cmpeq_epi8 (vTemp, vZero);
         ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1386:1: error: inlining failed in call to always_inline ‘_mm_movemask_epi8’: target specific option mismatch
 _mm_movemask_epi8 (__m128i __A)
 ^
src/ssw.c:225:8: error: called from here
   cmp  = _mm_movemask_epi8 (vTemp);
        ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1368:1: error: inlining failed in call to always_inline ‘_mm_max_epu8’: target specific option mismatch
 _mm_max_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:229:16: error: called from here
             vH = _mm_max_epu8 (vH, vF);
                ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1368:1: error: inlining failed in call to always_inline ‘_mm_max_epu8’: target specific option mismatch
 _mm_max_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:230:15: error: called from here
    vMaxColumn = _mm_max_epu8(vMaxColumn, vH);
               ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:704:1: error: inlining failed in call to always_inline ‘_mm_store_si128’: target specific option mismatch
 _mm_store_si128 (__m128i *__P, __m128i __B)
 ^
src/ssw.c:231:13: error: called from here
             _mm_store_si128 (pvHStore + j, vH);
             ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1091:1: error: inlining failed in call to always_inline ‘_mm_subs_epu8’: target specific option mismatch
 _mm_subs_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:232:16: error: called from here
             vF = _mm_subs_epu8 (vF, vGapE);
                ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:686:1: error: inlining failed in call to always_inline ‘_mm_load_si128’: target specific option mismatch
 _mm_load_si128 (__m128i const *__P)
 ^
src/ssw.c:239:16: error: called from here
             vH = _mm_load_si128 (pvHStore + j);
                ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1091:1: error: inlining failed in call to always_inline ‘_mm_subs_epu8’: target specific option mismatch
 _mm_subs_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:241:19: error: called from here
             vTemp = _mm_subs_epu8 (vH, vGapO);
                   ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1091:1: error: inlining failed in call to always_inline ‘_mm_subs_epu8’: target specific option mismatch
 _mm_subs_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:242:19: error: called from here
             vTemp = _mm_subs_epu8 (vF, vTemp);
                   ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1288:1: error: inlining failed in call to always_inline ‘_mm_cmpeq_epi8’: target specific option mismatch
 _mm_cmpeq_epi8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:243:19: error: called from here
             vTemp = _mm_cmpeq_epi8 (vTemp, vZero);
                   ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1386:1: error: inlining failed in call to always_inline ‘_mm_movemask_epi8’: target specific option mismatch
 _mm_movemask_epi8 (__m128i __A)
 ^
src/ssw.c:244:18: error: called from here
             cmp  = _mm_movemask_epi8 (vTemp);
                  ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1368:1: error: inlining failed in call to always_inline ‘_mm_max_epu8’: target specific option mismatch
 _mm_max_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:247:13: error: called from here
   vMaxScore = _mm_max_epu8(vMaxScore, vMaxColumn);
             ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1288:1: error: inlining failed in call to always_inline ‘_mm_cmpeq_epi8’: target specific option mismatch
 _mm_cmpeq_epi8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:248:9: error: called from here
   vTemp = _mm_cmpeq_epi8(vMaxMark, vMaxScore);
         ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1386:1: error: inlining failed in call to always_inline ‘_mm_movemask_epi8’: target specific option mismatch
 _mm_movemask_epi8 (__m128i __A)
 ^
src/ssw.c:249:7: error: called from here
   cmp = _mm_movemask_epi8(vTemp);
       ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1368:1: error: inlining failed in call to always_inline ‘_mm_max_epu8’: target specific option mismatch
 _mm_max_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:110:27: error: called from here
 #define max16(m, vm) (vm) = _mm_max_epu8((vm), _mm_srli_si128((vm), 8)); \
                           ^
src/ssw.c:253:4: note: in expansion of macro ‘max16’
    max16(temp, vMaxScore);
    ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1368:1: error: inlining failed in call to always_inline ‘_mm_max_epu8’: target specific option mismatch
 _mm_max_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:111:13: error: called from here
        (vm) = _mm_max_epu8((vm), _mm_srli_si128((vm), 4)); \
             ^
src/ssw.c:253:4: note: in expansion of macro ‘max16’
    max16(temp, vMaxScore);
    ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1368:1: error: inlining failed in call to always_inline ‘_mm_max_epu8’: target specific option mismatch
 _mm_max_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:112:13: error: called from here
        (vm) = _mm_max_epu8((vm), _mm_srli_si128((vm), 2)); \
             ^
src/ssw.c:253:4: note: in expansion of macro ‘max16’
    max16(temp, vMaxScore);
    ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1368:1: error: inlining failed in call to always_inline ‘_mm_max_epu8’: target specific option mismatch
 _mm_max_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:113:13: error: called from here
        (vm) = _mm_max_epu8((vm), _mm_srli_si128((vm), 1)); \
             ^
src/ssw.c:253:4: note: in expansion of macro ‘max16’
    max16(temp, vMaxScore);
    ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1368:1: error: inlining failed in call to always_inline ‘_mm_max_epu8’: target specific option mismatch
 _mm_max_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:110:27: error: called from here
 #define max16(m, vm) (vm) = _mm_max_epu8((vm), _mm_srli_si128((vm), 8)); \
                           ^
src/ssw.c:267:3: note: in expansion of macro ‘max16’
   max16(maxColumn[i], vMaxColumn);
   ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1368:1: error: inlining failed in call to always_inline ‘_mm_max_epu8’: target specific option mismatch
 _mm_max_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:111:13: error: called from here
        (vm) = _mm_max_epu8((vm), _mm_srli_si128((vm), 4)); \
             ^
src/ssw.c:267:3: note: in expansion of macro ‘max16’
   max16(maxColumn[i], vMaxColumn);
   ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1368:1: error: inlining failed in call to always_inline ‘_mm_max_epu8’: target specific option mismatch
 _mm_max_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:112:13: error: called from here
        (vm) = _mm_max_epu8((vm), _mm_srli_si128((vm), 2)); \
             ^
src/ssw.c:267:3: note: in expansion of macro ‘max16’
   max16(maxColumn[i], vMaxColumn);
   ^
In file included from src/ssw.c:11:0:
/usr/lib/gcc/i686-linux-gnu/4.9/include/emmintrin.h:1368:1: error: inlining failed in call to always_inline ‘_mm_max_epu8’: target specific option mismatch
 _mm_max_epu8 (__m128i __A, __m128i __B)
 ^
src/ssw.c:113:13: error: called from here
        (vm) = _mm_max_epu8((vm), _mm_srli_si128((vm), 1)); \
             ^
src/ssw.c:267:3: note: in expansion of macro ‘max16’
   max16(maxColumn[i], vMaxColumn);
   ^
<integrado>: recipe for target 'src/ssw.o' failed
make: *_\* [src/ssw.o] Error 1

**Comment by marc-sturm** [comment]
I can confirm the problem on Ubuntu 16.04.1 (gcc 5.4.0) for vcflib 'v1.0.0-rc1'.
Is there any solution coming?

Best,
  Marc

**Comment by tseemann** [comment]
You appear to be using a 32 bit operating system. I don't think that will work.
