### ISSUE TITLE
Decomposing complex calls and haplotype calls to the simplest form

### ISSUE THREAD

**Issue by andkam** [vcflib/vcflib#156]
Hi!

I have a multi sample vcf file (called with Freebayes). I want to decompose multi allelic calls into "single" calls on separate rows, and I want to decompose "block calls" to the simplest form of SNP call possible. I have been using vcfbreakmulti and vcfallelicprimitives to do this (also trying vt decompose and vt decompose_blocksub). My question is: Do I need to run the data though both programs? Does it matter in which order I run the data through vcfbreakmulti and vcfallelicprimitives? 

When I run the data though vcfbreakmulti and then vcfallelicprimitives the vcf file produced is about 40 000 rows longer then running the programs in reverse sequence. (total size of vcf file ≈ 6 000 000 rows).

Does anyone know which is the best alternative? (I want to load the final annotated vcf into GEMINI)

**Comment by hzpc-joostk** [comment]
Hi @andkam, I would advice to run it in the following order:

```sh
freebayes ... | vcfallelicprimitives [...] | vcfbreakmulti 
```
Or save the intermediate FreeBayes VCF output and then passing it into `vcfallelicprimitives` and `vcfbreakmulti`, in that order. :)
