### ISSUE TITLE
Source files lack license headers

### ISSUE THREAD

**Issue by lbeltrame** [vcflib/vcflib#16]
Even though the README.md specifies this project's license, it would be very useful if vcflib were to be used by other projects to have MIT license headers in every source file.

**Comment by ekg** [comment]
That's an interesting idea, and at very least I should be adding minimal header information to specify authorship and license type.  This is low-priority for me now, but I do want to resolve this.  Feel free to add them and I will pull your patch.

**Comment by lbeltrame** [comment]
This is still valid. Actually, at this point it would be even better to use SPDX license identifiers following the REUSE specification (https://reuse.software/).

**Comment by pjotrp** [comment]
Anyone feels like supplying a patch?
