### ISSUE TITLE
How to use the C++ library  ?

### ISSUE THREAD

**Issue by dridk** [vcflib/vcflib#160]
There is no documentation explain how work and how to link the library ? 
Is there dependencies ? 
Could you add a quick start guide with a minimal exemple of how to use the library in a C++ project ? 
Or a minimal project easily to compile ? It's a little bit confusing for me now. Because you mix the library and software in the same repository.

**Comment by dridk** [comment]
Ok, I finally success ... ! This line do the job ! 

```
g++  -I vcflib/include -I vcflib/tabixpp/htslib -Lvcflib/lib -Lvcflib/tabixpp/htslib -lvcflib -lhts -lz -lpthread -lm
```

**Comment by zeeev** [comment]
A PR would be great for some basic docs in the README.

**Comment by tseemann** [comment]
See https://github.com/vcflib/vcflib#using-the-c-library
