### ISSUE TITLE
vcffilter question

### ISSUE THREAD

**Issue by MBCSD** [vcflib/vcflib#165]
Hello,
I'm trying to remove all calls that are heterozygous and the variant or reference allele is only supported by one read.

I've tried:
 vcffilter -g "! ( GT = 0/1 & AD = 1,\* OR AD = *,1 )" 

No luck.

Can someone help me with the syntax here?

Thanks so much,
Molly

**Comment by tseemann** [comment]
Is it even possible to get 1 observation (read) and be called heterozygous?
