### ISSUE TITLE
Is vcfallelicprimitives reversible?

### ISSUE THREAD

**Issue by NeillGibson** [vcflib/vcflib#166]
Is there a way to reverse the decomposition of variants to allelic primitives?

Since the decomposed variants are phased, it should be possible to put together again the "haplotype" variants? 

Is this possible in theory and could you suggest a tool that could be used to reverse the decomposition to primitives? 

Thank you.

**Comment by ekg** [comment]
Yes. You want vcfgeno2haplo.

**Comment by NeillGibson** [comment]
Thank you Erik! 

vcfgeno2haplo outputs sample genotypes that look a bit different. 

GT:AO:DP:GQ:PL:QA:QR:RO
0:.:.:.:.:.:.:.
4|4:.:.:.:.:.:.:.
7|6:.:.:.:.:.:.:.
1:.:.:.:.:.:.:.

Do the numbers the GT field still refer to the list of  reference allele + alternative alleles? 
( 0 = REF, 
1 = first ALT,
2= second ALT etc )

Why is sometimes only 1 number used in the GT field? ie the 0:.:.:.:.:.:.:.  and 1:.:.:.:.:.:.:. GT in the above example?

**Comment by NeillGibson** [comment]
Mhm I do run into the errors below and then very quickly a  "Segmentation fault" crash . 

```
no alternate alleles remain at Chr_01:107 after haplotype validation
no alternate alleles remain at Chr_01:130 after haplotype validation
```

The VCF has been produced by running freebayes within bcbio after alignment with bwa.
