### ISSUE TITLE
Increment number of values for BasesToClosestVariant header line when annotating vcf file twice with vcfdistance

### ISSUE THREAD

**Issue by NeillGibson** [vcflib/vcflib#167]
Hi, 

I would like to annotate a VCF file twice with vcfdistance, this to have the distance to all variants in the population and the distance to variants in my samples of interest. 

In the end I would like to do this filter

`bcftools view my.vcf.gz  | vcfdistance | bcftools view -S SOI.txt -c1 | vcfdistance | bcftoolst view -i 'BasesToClosestVariant[0] > 10   & BasesToClosestVariant[1] > 20 '`

Annotating a VCF file twice with vcfdistance appends the second distance to the `BasesToClosestVariant `INFO attribute: `BasesToClosestVariant=61,111`

But the number of values declared for the attribute in the header is not incremented:
`##INFO=<ID=BasesToClosestVariant,Number=1,Type=Integer,Description="Number of bases to the closest variant in the file.">`

The bcftools filter on BasesToClosestVariant does not produce any output. 
`bcftoolst view -i 'BasesToClosestVariant[0] > 10   & BasesToClosestVariant[0] > 20 '`

If I first write the twice annotated VCF file to disk and manually increment the number of values in the header the above filter works. 
`##INFO=<ID=BasesToClosestVariant,Number=2,Type=Integer,Description="Number of bases to the closest variant in the file.">`

Would it be possible to have the vcfdistance tool increment the number of values declared for BasesToClosestVariant in the header if the attribute already exists.  This so that downstream filter tools know that the  BasesToClosestVariant attribute now is a list of integers. 

Thank you!

**Comment by NeillGibson** [comment]
What I propose is to only add the `BasesToClosestVariant` header line here if the  `BasesToClosestVariant` header line does not yet exists. And to otherwise increment the `Number=X` part of the  `BasesToClosestVariant` header line. 
https://github.com/vcflib/vcflib/blob/master/src/vcfdistance.cpp#L41

I don't see an update header line function but there is a `removeInfoHeaderLine` function in the variant class. 
https://github.com/vcflib/vcflib/blob/master/src/Variant.cpp#L1077

So removing the `BasesToClosestVariant` header line  and then adding the updated header line could be done. 

I am not sure how to get the current `BasesToClosestVariant`   `Number=X`  attribute. 
There is  `VCFHeader::getHeaderString()`
https://github.com/vcflib/vcflib/blob/master/src/Variant.cpp#L2368

**Comment by NeillGibson** [comment]
Another maybe easier option is to make the tag name an optional argument. 

For that only the check of number of arguments would be modified:
https://github.com/vcflib/vcflib/blob/master/src/vcfdistance.cpp#L11

and the assignment to the tag name string. 
https://github.com/vcflib/vcflib/blob/master/src/vcfdistance.cpp#L38

This so that it is possible to run vcfdistance with custom tag names. 
`bcftools view my.vcf.gz | vcfdistance PopulationBasesToClosestVariant| bcftools view -S SOI.txt -c1 | vcfdistance SoiBasesToClosestVariant | bcftoolst view -i 'PopulationBasesToClosestVariant > 10 & SoiBasesToClosestVariant  > 20`

**Comment by NeillGibson** [comment]
Hi @zeeev  Could you please have a look at the pull request. This enables adding multiple distance annotations as in this command:

`bcftools view my.vcf.gz | vcfdistance  | bcftools view -S SOI.txt | bcftools view -c1 | vcfdistance SoiBasesToClosestVariant  `

Something we find useful and probably also other people and organizations that use vcflib / vcfdistance. 

The added functionality is backwards compatible. 

Thank you.

**Comment by zeeev** [comment]
Hi Neil,

I’ll take a look this weekend.  Sorry for the delay.  

—Zev

**Comment by NeillGibson** [comment]
Hi @zeeev  Thank you for looking at the pull request.
