### ISSUE TITLE
vcflib installation problem on RHEL 5.5

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [vcflib/vcflib#173]
I need to install on RHEl 5.5. There is many incompatibility on the library
`cc1plus: error: unrecognized command line option "-std=c++0x"`

Could you please help me. I can't upgrade!!

**Comment by colindaven** [comment]
Try bioconda ?

**Comment by tseemann** [comment]
You need gcc >= 4.8.1 that supports C++11
