### ISSUE TITLE
vcfdistance usage

### ISSUE THREAD

**Issue by antunderwood** [vcflib/vcflib#18]
the usage for this tool states
usage: /usr/local/vcflib/vcfdistance <annotation-tag> <vcf file> <vcf file>

shouldn't it be

usage: /usr/local/vcflib/vcfdistance <vcf file> > <vcf out file>

**Comment by ekg** [comment]
I'm not completely sure I follow.  Are the docs correct now?  (https://github.com/ekg/vcflib#vcfdistance)
