### ISSUE TITLE
Error 1 generated

### ISSUE THREAD

**Issue by tdfy** [vcflib/vcflib#180]
Tried a few builds according to instruction but continue to receive Error 1. Suggestions welcome, thanks!

src/Variant.cpp:167:38: error: call to 'abs' is ambiguous
                            sv_len = abs((size_t) stol(this->info["END"][alt_pos]) - (size_t) (this->position));
                                     ^~~
/usr/include/stdlib.h:129:6: note: candidate function
int      abs(int) __pure2;
         ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cstdlib:167:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long      abs(     long __x) _NOEXCEPT {return  labs(__x);}
                                           ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cstdlib:169:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long long abs(long long __x) _NOEXCEPT {return llabs(__x);}
                                           ^
1 error generated.
make: *** [src/Variant.o] Error 1

**Comment by edawson** [comment]
We've hopefully fixed this in the latest build. I'm really sorry for causing build trouble; let me know if it's working for you now.

**Comment by tdfy** [comment]
Up and running, thank you!
