### ISSUE TITLE
ubuntu 14.04 LTS install issue

### ISSUE THREAD

**Issue by sheila-adams-sapper** [vcflib/vcflib#184]
I am running Ubuntu 14.04 LTS on Windows 10 with gcc4.8.2-1ubuntu6
I downloaded the repository for vcflib:
git clone --recursive git://github.com/vcflib/vcflib.git
after navigating to the vcflib directory:
make

the final error line is:
make: *** [src/Variant.o] Error 1

the portion of the log when encountering the first error is pasted below.

g++ -O3 -D_FILE_OFFSET_BITS=64 -c split.cpp
g++ -O3 -D_FILE_OFFSET_BITS=64 -c disorder.c
g++ -O3 -D_FILE_OFFSET_BITS=64 Fasta.o FastaHack.cpp split.o disorder.o -o fastahack
make[1]: Leaving directory `/mnt/c/Users/novem/vcflib/fastahack'
g++ -c -o src/Variant.o src/Variant.cpp -Itabixpp/htslib -Iinclude -L. -Ltabixpp/htslib -Llib -lvcflib -lhts -lpthread -lz -lm -O3 -D_FILE_OFFSET_BITS=64 -std=c++0x && cp src/*.h* /mnt/c/Users/novem/vcflib/include/
src/Variant.cpp: In member function ‘bool vcflib::Variant::canonicalize_sv(FastaReference&, std::vector<FastaReference*>, int)’:
src/Variant.cpp:183:95: error: no matching function for call to ‘regex_replace(__gnu_cxx::__alloc_traits<std::allocator<std::basic_string<char> > >::value_type&, std::regex&, const char [1])’
                                 string var_name = regex_replace(this->alt[alt_pos], arrows, "");
                                                                                               ^
src/Variant.cpp:183:95: note: candidates are:
In file included from /usr/include/c++/4.8/regex:62:0,
                 from src/Variant.h:18,
                 from src/Variant.cpp:1:
/usr/include/c++/4.8/bits/regex.h:2162:5: note: template<class _Out_iter, class _Bi_iter, class _Rx_traits, class _Ch_type> _Out_iter std::regex_replace(_Out_iter, _Bi_iter, _Bi_iter, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(_Out_iter __out, _Bi_iter __first, _Bi_iter __last,
     ^
/usr/include/c++/4.8/bits/regex.h:2162:5: note:   template argument deduction/substitution failed:
src/Variant.cpp:183:95: note:   deduced conflicting types for parameter ‘_Bi_iter’ (‘std::basic_regex<char>’ and ‘const char*’)
                                 string var_name = regex_replace(this->alt[alt_pos], arrows, "");
                                                                                               ^
In file included from /usr/include/c++/4.8/regex:62:0,
                 from src/Variant.h:18,
                 from src/Variant.cpp:1:
/usr/include/c++/4.8/bits/regex.h:2182:5: note: template<class _Rx_traits, class _Ch_type> std::basic_string<_Ch_type> std::regex_replace(const std::basic_string<_Ch_type>&, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(const basic_string<_Ch_type>& __s,
     ^
/usr/include/c++/4.8/bits/regex.h:2182:5: note:   template argument deduction/substitution failed:
src/Variant.cpp:183:95: note:   mismatched types ‘const std::basic_string<_Ch_type>’ and ‘const char [1]’
                                 string var_name = regex_replace(this->alt[alt_pos], arrows, "");
                                                                                               ^
make: *** [src/Variant.o] Error 1

**Comment by ekg** [comment]
Looks like a compiler version problem.

We really need to avoid these regex functions until the version of GCC with
them is more widely used. I think 4.9.2 is required.

**Comment by ekg** [comment]
I've also run into this same issue. I notice that it's not easy to install 4.9.2 on ubuntu 14.04 LTS.

I will probably revert them to functionality we can expect in 4.8 to solve this.

**Comment by ekg** [comment]
@edawson these are changes we recently pulled in. Is there a way to get the same behavior without regex_replace? It's not compatible across nearby GCC versions.

**Comment by edawson** [comment]
This *should* now be fixed. Let me know if there are still issues though!

**Comment by sheila-adams-sapper** [comment]
Many thanks - it has now installed successfully!
