### ISSUE TITLE
Make a release please?

### ISSUE THREAD

**Issue by serine** [vcflib/vcflib#185]
Hi there, 

I'm doing a bit of ansible deployment to few servers and vcflib compilation always fails on one or two random servers. This is perhaps because I'm always pulling from master branch and thus might get one or two "beta" commits. Would you be able to make new release that I can use as a set version in my ansible, that would really help. 

p.s I can ssh directory to a machine and fix it there, but I'd rather that happened through ansible. Also this isn't dep issues because sometimes compilation fails on the machine it was previously compiled. But I can't really say why this happens. Either new release would help. 

Thanks heaps, 

Kirill

**Comment by tseemann** [comment]
I second this - there has been LOTS of commits since 1.0.0

Any chance of a 1.0.1 tagged github release @ekg @zeeev  ?

**Comment by zeeev** [comment]
@tseemann I'de be happy to help with this.  Would you be willing to help me catalog some of the important changes for release notes?  The last change i've made was fixing vcf2tsv.

**Comment by serine** [comment]
@zeeev whats required for cataloguing?  Is just looking through `git log` and making a summary?

**Comment by zeeev** [comment]
@serine @tseemann Sorry for the late reply.  Yes, we just need to go through the log and make a summary.  I'm inclined to wait until we can get the build process under control.  The updates in htslib have caused some issues, as you can see. 

But yes, we need a stable tag.

**Comment by jpuritz** [comment]
I'd like to bump this request.  I want to update the bioconda package, and it would be great to have a new release.

Thanks!

**Comment by tseemann** [comment]
@ekg can we please have a release?  the missing `vcffirstheader` issue means `freebayes-parallel` works for no one. I am manually bundling it.

**Comment by tseemann** [comment]
@ekg @zeeev please make a new release and I will update the brew and conda packages and make a lot of people's problems go away, including mine.

Actually, even just `git tag v1.0.0-rc2` and `git push --tags` could work

**Comment by tseemann** [comment]
@serine We now have a 1.0.0-rc2 release, thank you to @zeeev !

https://github.com/vcflib/vcflib/tags

Can you close this issue (for now) @serine ?

**Comment by serine** [comment]
this is great ! closing this issue now

Thanks everyone
