### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by jmanuelfuentes** [vcflib/vcflib#189]
It seems the tabixpp directory is empty:

Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
if [ ! -d bin ]; then mkdir -p bin; fi
if [ ! -d lib ]; then mkdir -p lib; fi
if [ ! -d include ]; then mkdir -p include; fi
if [ ! -d obj ]; then mkdir -p obj; fi
cd tabixpp && make && cp *.h* /build/vcflib/vcflib-1.0.0-rc1/include/
make[1]: Entering directory `/build/vcflib/vcflib-1.0.0-rc1/tabixpp'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory `/build/vcflib/vcflib-1.0.0-rc1/tabixpp'
make: *** [tabixpp/tabix.o] Error 2

**Comment by tomcheng** [comment]
We ran into the same problem, using `git clone --recursive` solved it for us

**Comment by nurdyana** [comment]
Same here. In need of a solution

**Comment by tseemann** [comment]
`git clone --recursive` is needed as @tomcheng said.
