### ISSUE TITLE
vcflib - vcfbreakmulti = segmentation fault(core dumped)

### ISSUE THREAD

**Issue by myvniels** [vcflib/vcflib#19]
I tried to use your vcflib library
first i got an error related to tabixpp
once reading a thread:
http://seqanswers.com/forums/showthread.php?t=23860

I manged to solve this issue.

However, now when i try to use vcfbreakmulti 
i get a 'Segmentation fault(core dumped)' error

How can I resolve this issue?

As I really would like to split the multi-allelic events.

Thanks in advance.

**Comment by ekg** [comment]
I recently resolved this same issue, please let me know if it is still ongoing in the current versions.
