### ISSUE TITLE
Tabix memory leak

### ISSUE THREAD

**Issue by smottarella** [vcflib/vcflib#193]
Hello,

I am working with vcflib and have found a memory leak in tabix. I found it from my own code, but used vcfstat as a simpler example of this happening. In a standard run of vcfstats with a tabix indexed input through valgrind, I find this output:

`==1142==`
`==1142== HEAP SUMMARY:`
`==1142==     in use at exit: 135,492 bytes in 7 blocks`
`==1142==   total heap usage: 68,002 allocs, 67,995 frees, 6,233,136 bytes allocated`
`==1142== `
`==1142== 135,492 (96 direct, 135,396 indirect) bytes in 1 blocks are definitely lost in loss record 7 of 7`
`==1142==    at 0x4C2C975: calloc (vg_replace_malloc.c:711)`
`==1142==    by 0x44F81B: hts_hopen (hts.c:773)`
`==1142==    by 0x44FD6E: hts_open_format (hts.c:424)`
`==1142==    by 0x444EA7: Tabix::Tabix(std::string&) (tabix.cpp:32)`
`==1142==    by 0x40C840: vcflib::VariantCallFile::open(std::string&) (in /root/ext/vcflib/bin/vcfstats)`
`==1142==    by 0x40A65B: main (in /root/ext/vcflib/bin/vcfstats)`
`==1142== `
`==1142== LEAK SUMMARY:`
`==1142==    definitely lost: 96 bytes in 1 blocks`
`==1142==    indirectly lost: 135,396 bytes in 6 blocks`
`==1142==      possibly lost: 0 bytes in 0 blocks`
`==1142==    still reachable: 0 bytes in 0 blocks`
`==1142==         suppressed: 0 bytes in 0 blocks`
`==1142== `
`==1142== For counts of detected and suppressed errors, rerun with: -v`
`==1142== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)`

**Comment by tseemann** [comment]
Probably should be filed at https://github.com/ekg/tabixpp/issues
