### ISSUE TITLE
cannot compare (>) objects of dissimilar types

### ISSUE THREAD

**Issue by MBeyens** [vcflib/vcflib#194]
Dear 

I cannot filter my vcfs as I get following error: `cannot compare (>) objects of dissimilar types`. I'm using `vcffilter -f "FS < 40 & SOR < 10 & ExcessHet < 1000 & ReadPosRankSum < 30 & MQ0 < 200000 & BaseQRankSum > -60 & HaplotypeScore < 100" vcffile.vcf > vcffile.filtered.vcf` as command.

Apparently the problem is the minus sign of the BaseQRankSum filter value. How to solve this problem?

Many thanks in advance

Matthias

**Comment by zeeev** [comment]
Yes, minus sign is not supported.

**Comment by ekg** [comment]
You can do this. "Q < ( 0 - 60 )"

I'm sorry this DSL is so brain-dead.
