### ISSUE TITLE
xpehh is missing

### ISSUE THREAD

**Issue by lingonghua** [vcflib/vcflib#196]
Dear vcflib authors,
I find the program very useful. I successfully (without any error or warning) make the package in my Fedora 20 system using the commands: 
```
git clone --recursive https://github.com/vcflib/vcflib.git vcflib
cd vcflib
make
```
Finally I obatin 130 programs in the bin path. Unfortunately I can not find the xpehh!
I tried gcc versition 4.8.3 and 7.1.0, and no difference was found so it seems not attributed to the compiler version.  
Could you please help to see why is the xpehh missing or send me (my email is lingonghua@126.com) the compilled xpehh binary?

**Comment by lingonghua** [comment]
Here are the available 130 combined binaries:
abba-baba
bFst
bed2region
bgziptabix
dumpContigsFromHeader
genotypeSummary
hapLrt
LD
iHS
meltEHH
normalize-iHS
pFst
pVst
permuteGPAT++
permuteSmooth
plotBfst.R
plotHapLrt.R
plotHaplotypes.R
plotHaps
plotPfst.R
plotSmoothed.R
plotWCfst.R
plotXPEHH.R
plot_roc.r
popStats
segmentFst
segmentIhs
sequenceDiversity
smoother
vcf2bed.py
vcf2dag
vcf2fasta
vcf2sqlite.py
vcf2tsv
vcf_strip_extra_headers
vcfaddinfo
vcfafpath
vcfallelicprimitives
vcfaltcount
vcfannotate
vcfannotategenotypes
vcfbiallelic
vcfbreakmulti
vcfcat
vcfcheck
vcfclassify
vcfcleancomplex
vcfclearid
vcfclearinfo
vcfcombine
vcfcommonsamples
vcfcomplex
vcfcountalleles
vcfcreatemulti
vcfdistance
vcfecho
vcfentropy
vcfevenregions
vcffilter
vcffirstheader
vcffixup
vcfflatten
vcfgeno2alleles
vcfgeno2haplo
vcfgenosamplenames
vcfgenosummarize
vcfgenotypecompare
vcfgenotypes
vcfglbound
vcfglxgt
vcfgtcompare.sh
vcfhetcount
vcfhethomratio
vcfindelproximity
vcfindels
vcfindex
vcfinfo2qual
vcfinfosummarize
vcfintersect
vcfjoincalls
vcfkeepgeno
vcfkeepinfo
vcfkeepsamples
vcfleftalign
vcflength
vcfmultiallelic
vcfmultiway
vcfmultiwayscripts
vcfnobiallelicsnps
vcfnoindels
vcfnormalizesvs
vcfnosnps
vcfnull2ref
vcfnulldotslashdot
vcfnumalt
vcfoverlay
vcfparsealts
vcfplotaltdiscrepancy.r
vcfplotaltdiscrepancy.sh
vcfplotsitediscrepancy.r
vcfplottstv.sh
vcfprimers
vcfprintaltdiscrepancy.r
vcfprintaltdiscrepancy.sh
vcfqual2info
vcfqualfilter
vcfrandom
vcfrandomsample
vcfregionreduce
vcfregionreduce_and_cut
vcfregionreduce_pipe
vcfregionreduce_uncompressed
vcfremap
vcfremoveaberrantgenotypes
vcfremovenonATGC
vcfremovesamples
vcfroc
vcfsample2info
vcfsamplediff
vcfsamplenames
vcfsitesummarize
vcfsnps
vcfsort
vcfstats
vcfstreamsort
vcfuniq
vcfuniqalleles
vcfunphase
vcfvarstats
wcFst

**Comment by zeeev** [comment]
I've removed it until I can further validate the method.

**Comment by lingonghua** [comment]
@zeeev Thanks for your prompt response.
