### ISSUE TITLE
Can't make vcflib tools. Missing vcfnumalt.cpp?

### ISSUE THREAD

**Issue by arq5x** [vcflib/vcflib#2]
Hi Erik,

I am back to hacking on VCF files and wanted to work with your latest repo.  I am having troubles making the existing tools.  The underlying objects (e.g., Variant.o) seem to compile just fine, but I get an error message when attempting to make the first tool (vcfecho.cpp).  It complains about a missing rule for vcfnumalt.cpp.  This source file doesn't seem to exist in the repo, and looking at the code for vcfecho, I can't tell why it would need it.  Perhaps the Makefile needs to be tweaked?

Best,
Aaron

$ make clean; make
rm -f vcfecho vcfaltcount vcfhetcount vcffilter vcf2tsv vcfgenotypes vcfannotategenotypes vcfcommonsamples vcfgenotypecompare vcffixup vcfclassify vcfsamplediff vcfremoveaberrantgenotypes vcfrandom vcfparsealts vcfstats vcfflatten vcfprimers vcfnumalt Variant.o split.o
cd tabixpp && make clean
rm -fr gmon.out _.o a.out *.dSYM tabix bgzip tabix++ *~ *.a tabix.aux tabix.log tabix.pdf *.class libtabix._.dylib libtabix.so*
cd smithwaterman && make clean
Cleaning up.
cd fastahack && make clean
rm -f fastahack _.o
cd tabixpp && make
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE  bgzf.c -o bgzf.o
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE  kstring.c -o kstring.o
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE  knetfile.c -o knetfile.o
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE  index.c -o index.o
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE  bedidx.c -o bedidx.o
ar -cru libtabix.a bgzf.o kstring.o knetfile.o index.o bedidx.o
ranlib libtabix.a
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE  main.c -o main.o
gcc -g -Wall -O2 -fPIC  -o tabix main.o -lm  -lz -L. -ltabix
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE  bgzip.c -o bgzip.o
gcc -g -Wall -O2 -fPIC  -o bgzip bgzip.o bgzf.o knetfile.o -lz
g++ -g -Wall -O2 -fPIC  -c tabix.cpp
g++ -g -Wall -O2 -fPIC  -o tabix++ main.cpp tabix.o bgzf.o -lm  -lz -L. -ltabix
g++ -c -o Variant.o Variant.cpp  -lm -lz -L. -Ltabixpp/ -ltabix  -O3
i686-apple-darwin10-g++-4.2.1: -lm: linker input file unused because linking not done
i686-apple-darwin10-g++-4.2.1: -lz: linker input file unused because linking not done
i686-apple-darwin10-g++-4.2.1: -ltabix: linker input file unused because linking not done
g++ -c -o split.o split.cpp  -lm -lz -L. -Ltabixpp/ -ltabix  -O3
i686-apple-darwin10-g++-4.2.1: -lm: linker input file unused because linking not done
i686-apple-darwin10-g++-4.2.1: -lz: linker input file unused because linking not done
i686-apple-darwin10-g++-4.2.1: -ltabix: linker input file unused because linking not done
make: *_\* No rule to make target `vcfnumalt.cpp', needed by`vcfecho'.  Stop.

**Comment by ekg** [comment]
I omitted vcfnumalt.cpp from the repository.  Please re-pull for a fixed
revision.

**Comment by arq5x** [comment]
Beautiful, thanks.  In the interim, I just ditched it from the BIN sources list.  Thanks for the quick update, Erik.
