### ISSUE TITLE
vcffilter is seg faulting and not processing filter strings

### ISSUE THREAD

**Issue by charlesdavid** [vcflib/vcflib#202]
Just tried: 
`vcffilter -f "MQ > 10" filter2.vcf > filter3.vcf
could not convert field MQ=NaN to float`

I am working with properly formatted vcf files and all MQ values are indeed floats.
What gives?

Also, 
`vcffilter -f "DP >= 9 & QUAL >= 20" -g "GT = 1/1" filter1.vcf > test.vcf
Segmentation fault`
Truly, what gives???

**Comment by tseemann** [comment]
@charlesdavid the second problem can be solved by using `>` and `<` instead of `>=` and `<=` which are not supported... not sure about the first problem.
