### ISSUE TITLE
vcffilter 

### ISSUE THREAD

**Issue by dwaggott** [vcflib/vcflib#21]
Hey,

Does the vcffilter work on string data types?  I couldn't get to work but my syntax could have been wrong.  If not, it would be a most definitely appreciated feature.

i.e.

```
##INFO=<ID=VT,Number=1,Type=String,Description="Variant type, can be SNP, INS or DEL">
```

Daryl

**Comment by ekg** [comment]
Yes, it does work on these types.

```
vcffilter -f "VT = SNP"
```

This will pick up all variants which have VT=SNP.  Let me know if you get different behavior.

The syntax used for the filter mini-language is somewhat limited due to an overly-simplistic parser, but it does allow for arbitrary expressions.  As I update the documentation I will flesh out some examples of what you can do.  One significant problem I have now is that it isn't possible to use negative numbers.

**Comment by dwaggott** [comment]
Not negative numbers!

I couldn't get it to work with dbSNP138 VCFs.  Flags and Integer expressions worked but there was no output for selecting string values.

```
### dbSNP138
#ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606/VCF/

wget ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606/VCF/clinvar_20130905.vcf.gz 
wget ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606/VCF/clinvar_20130905.vcf.gz.tbi

### test1 and test2 work but not test3-5
vcffilter -f "PM" clinvar_20130905.vcf.gz > test1.vcf  # PM is a flag
vcffilter -f "COMMON = 1" clinvar_20130905.vcf.gz > test2.vcf  # COMMON is a integer
vcffilter -f "CLNSIG = 4" clinvar_20130905.vcf.gz > test3.vcf #  CLINSIG and CLNORIGIN are strings
vcffilter -f "CLNORIGIN = 4" clinvar_20130905.vcf.gz > test4.vcf 
vcffilter -f "(COMMON = 0) & (MUT | PM | CLNSIG = 3 | CLNSIG = 4 | CLNORGIN = 4 | CLNORGIN = 32)"   00-All.vcf.gz > test5.vcf

##INFO=<ID=CLNSIG,Number=.,Type=String,Description="Variant Clinical Significance, 0 - unknown, 1 - untested, 2 - non-pathogenic, 3 - probable-non-pathogenic, 4 - probable-pathogenic, 5 - pathogenic, 6 - drug-response, 7 - histocompatibility, 255 - other">

```

**Comment by ekg** [comment]
Here's a problem: "Number=." is not supported.  I guess I should, as a lot
of people making VCF files aren't providing correct metadata about the
number of fields.

Try changing all the Number=. to Number=1 in the header (where there is
really one value).

**Comment by dwaggott** [comment]
No luck.  I changed Number=. to Number=1 and also shuffled the header around a bit.

**Comment by ekg** [comment]
Try this:

zcat clinvar_20130808.vcf.gz | grep CLNSIG

How many records do you get?

**Comment by dwaggott** [comment]
zcat clinvar_20130808.vcf.gz | grep CLNSIG | wc -l
78760
zcat clinvar_20130808.vcf.gz | grep CLNSIG=4 | wc -l
1672

**Comment by ekg** [comment]
Would you please post this file somewhere?  I actually can't download it
from the ftp link you posted.

**Comment by dwaggott** [comment]
I updated the url in the first post.  I guess the dates were updated.

**Comment by ekg** [comment]
Unfortunately, the file is completely different.  Mind sending me an
example?  Use my email addr. as it appears in the docs.

**Comment by tseemann** [comment]
`bcftools filter` is useful here too.
