### ISSUE TITLE
Consider adopting a Code of Conduct

### ISSUE THREAD

**Issue by abbycabs** [vcflib/vcflib#210]
Hi all 👋 Great work here.

I hope you don't mind this drive-by suggestion, but it might be a good idea to adopt a code of conduct on your project (something like the contributor covenant)

It's super easy on GitHub now & they provide templates: https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

Thanks again!

**Comment by zeeev** [comment]
@acabunoc good idea, want to add one?
