### ISSUE TITLE
error in vcflib compilation

### ISSUE THREAD

**Issue by SimonaDeSumma** [vcflib/vcflib#216]
Hi there,
I have problems in the compilation of vcflib.
My OS is Ubuntu 14.04.5 LTS.
The error is after make command:
root@irccsbari-xxxl:/home/sdesumma/vcflib# make
if [ ! -d bin ]; then mkdir -p bin; fi
if [ ! -d lib ]; then mkdir -p lib; fi
if [ ! -d include ]; then mkdir -p include; fi
if [ ! -d obj ]; then mkdir -p obj; fi
cd tabixpp && make && cp *.h* /home/sdesumma/vcflib/include/
make[1]: Entering directory `/home/sdesumma/vcflib/tabixpp'
make[2]: Entering directory `/home/sdesumma/vcflib/tabixpp'
g++ -g -Wall -O2 -fPIC  -c tabix.cpp -Ihtslib
tabix.cpp: In constructor ‘Tabix::Tabix(std::string&)’:
tabix.cpp:15:10: warning: ‘int bgzf_is_bgzf(const char*)’ is deprecated (declared at htslib/htslib/bgzf.h:238): Use bgzf_compression() or hts_detect_format() instead [-Wdeprecated-declarations]
     if ( bgzf_is_bgzf(cfilename)!=1 )
          ^
tabix.cpp:15:32: warning: ‘int bgzf_is_bgzf(const char*)’ is deprecated (declared at htslib/htslib/bgzf.h:238): Use bgzf_compression() or hts_detect_format() instead [-Wdeprecated-declarations]
     if ( bgzf_is_bgzf(cfilename)!=1 )
                                ^
cd htslib && make lib-static
make[3]: Entering directory `/home/sdesumma/vcflib/tabixpp/htslib'
echo '/* Default config.h generated by Makefile */' > config.h
echo '#define HAVE_LIBBZ2 1' >> config.h
echo '#define HAVE_LIBLZMA 1' >> config.h
cc -g -Wall -O2 -I.  -c -o kfunc.o kfunc.c
cc -g -Wall -O2 -I.  -c -o knetfile.o knetfile.c
cc -g -Wall -O2 -I.  -c -o kstring.o kstring.c
cc -g -Wall -O2 -I.  -c -o bcf_sr_sort.o bcf_sr_sort.c
cc -g -Wall -O2 -I.  -c -o bgzf.o bgzf.c
cc -g -Wall -O2 -I.  -c -o errmod.o errmod.c
cc -g -Wall -O2 -I.  -c -o faidx.o faidx.c
cc -g -Wall -O2 -I.  -c -o hfile.o hfile.c
cc -g -Wall -O2 -I.  -c -o hfile_net.o hfile_net.c
echo '#define HTS_VERSION "1.5"' > version.h
cc -g -Wall -O2 -I.  -c -o hts.o hts.c
cc -g -Wall -O2 -I.  -c -o md5.o md5.c
cc -g -Wall -O2 -I.  -c -o multipart.o multipart.c
cc -g -Wall -O2 -I.  -c -o probaln.o probaln.c
cc -g -Wall -O2 -I.  -c -o realn.o realn.c
cc -g -Wall -O2 -I.  -c -o regidx.o regidx.c
cc -g -Wall -O2 -I.  -c -o sam.o sam.c
cc -g -Wall -O2 -I.  -c -o synced_bcf_reader.o synced_bcf_reader.c
cc -g -Wall -O2 -I.  -c -o vcf_sweep.o vcf_sweep.c
cc -g -Wall -O2 -I.  -c -o tbx.o tbx.c
cc -g -Wall -O2 -I.  -c -o textutils.o textutils.c
cc -g -Wall -O2 -I.  -c -o thread_pool.o thread_pool.c
cc -g -Wall -O2 -I.  -c -o vcf.o vcf.c
cc -g -Wall -O2 -I.  -c -o vcfutils.o vcfutils.c
cc -g -Wall -O2 -I.  -c -o cram/cram_codecs.o cram/cram_codecs.c
cc -g -Wall -O2 -I.  -c -o cram/cram_decode.o cram/cram_decode.c
cc -g -Wall -O2 -I.  -c -o cram/cram_encode.o cram/cram_encode.c
cc -g -Wall -O2 -I.  -c -o cram/cram_external.o cram/cram_external.c
cc -g -Wall -O2 -I.  -c -o cram/cram_index.o cram/cram_index.c
cc -g -Wall -O2 -I.  -c -o cram/cram_io.o cram/cram_io.c
cram/cram_io.c:60:18: fatal error: lzma.h: No such file or directory
 #include <lzma.h>
                  ^
compilation terminated.
make[3]: *** [cram/cram_io.o] Error 1
make[3]: Leaving directory `/home/sdesumma/vcflib/tabixpp/htslib'
make[2]: *** [htslib/libhts.a] Error 2
make[2]: Leaving directory `/home/sdesumma/vcflib/tabixpp'
make[1]: *** [all-recur] Error 1
make[1]: Leaving directory `/home/sdesumma/vcflib/tabixpp'
make: *** [tabixpp/tabix.o] Error 2

Could you please help me?

Simona

**Comment by zeeev** [comment]
Hi @SimonaDeSumma I believe this is now resolved. Try it out.

**Comment by ccoulombe** [comment]
I confirm : the repo builds correctly.
@SimonaDeSumma You need to install `lzma` header files. As the compiler tells you :`No such file or directory #include <lzma.h>`.

**Comment by SimonaDeSumma** [comment]
Thank you so much. In the mean time I corrected the makefile of tabbix directory and I solved the problems.

**Comment by julieaorjuela** [comment]
Hello, I have similar error: I don't understand where did @SimonaDeSumma corrected this error.
I did an "apt-get install lzma" and lzma is already the newest version (9.22-2ubuntu2).
Can you please help me?
`
$ make
if [ ! -d bin ]; then mkdir -p bin; fi
if [ ! -d lib ]; then mkdir -p lib; fi
if [ ! -d include ]; then mkdir -p include; fi
if [ ! -d obj ]; then mkdir -p obj; fi
cd tabixpp && make && cp *.h* /home/adnid/Documents/Logiciels/vcflib/include/
make[1] : on entre dans le répertoire « /home/adnid/Documents/Logiciels/vcflib/tabixpp »
make[2] : on entre dans le répertoire « /home/adnid/Documents/Logiciels/vcflib/tabixpp »
cd htslib && make lib-static
make[3] : on entre dans le répertoire « /home/adnid/Documents/Logiciels/vcflib/tabixpp/htslib »
cc -g -Wall -O2 -I.  -c -o cram/cram_io.o cram/cram_io.c
cram/cram_io.c:60:18: fatal error: lzma.h: Aucun fichier ou dossier de ce type
compilation terminated.
Makefile:134 : la recette pour la cible « cram/cram_io.o » a échouée
make[3]: *** [cram/cram_io.o] Erreur 1
make[3] : on quitte le répertoire « /home/adnid/Documents/Logiciels/vcflib/tabixpp/htslib »
Makefile:38 : la recette pour la cible « htslib/libhts.a » a échouée
make[2]: *** [htslib/libhts.a] Erreur 2
make[2] : on quitte le répertoire « /home/adnid/Documents/Logiciels/vcflib/tabixpp »
Makefile:22 : la recette pour la cible « all-recur » a échouée
make[1]: *** [all-recur] Erreur 1
make[1] : on quitte le répertoire « /home/adnid/Documents/Logiciels/vcflib/tabixpp »
Makefile:170 : la recette pour la cible « tabixpp/tabix.o » a échouée
make: *** [tabixpp/tabix.o] Erreur 2
`

**Comment by ccoulombe** [comment]
@julieaorjuela 
I confirm : the repo builds correctly.
You need to install lzma header files (ubuntu package `lzma-dev`). As the compiler tells you : `fatal error: lzma.h: Aucun fichier ou dossier de ce type`.
