### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by drowca** [vcflib/vcflib#218]
When executing make, I keep getting an error (below). I'm new to the field so it may be something obvious but any help is appreciated.

g++ -O3 -D_FILE_OFFSET_BITS=64 -std=c++0x -fopenmp -D HAS_OPENMP -o tabix++ main.cpp tabix.o -Ihtslib -L. -Lhtslib \
		-lhts -lpthread -lm -lz
htslib/libhts.a(cram_io.o): In function `lzma_mem_deflate':
/home/vcflib/tabixpp/htslib/cram/cram_io.c:669: undefined reference to `lzma_stream_buffer_bound'
/home/vcflib/tabixpp/htslib/cram/cram_io.c:675: undefined reference to `lzma_easy_buffer_encode'
htslib/libhts.a(cram_io.o): In function `cram_compress_by_method':
/home/vcflib/tabixpp/htslib/cram/cram_io.c:1030: undefined reference to `BZ2_bzBuffToBuffCompress'
htslib/libhts.a(cram_io.o): In function `cram_uncompress_block':
/home/vcflib/tabixpp/htslib/cram/cram_io.c:954: undefined reference to `BZ2_bzBuffToBuffDecompress'
htslib/libhts.a(cram_io.o): In function `lzma_mem_inflate':
/home/vcflib/tabixpp/htslib/cram/cram_io.c:691: undefined reference to `lzma_easy_decoder_memusage'
/home/vcflib/tabixpp/htslib/cram/cram_io.c:691: undefined reference to `lzma_stream_decoder'
/home/vcflib/tabixpp/htslib/cram/cram_io.c:706: undefined reference to `lzma_code'
/home/vcflib/tabixpp/htslib/cram/cram_io.c:719: undefined reference to `lzma_code'
/home/vcflib/tabixpp/htslib/cram/cram_io.c:728: undefined reference to `lzma_end'

**Comment by tseemann** [comment]
The makefile now includes `-lzma -lbz2` etc.
