### ISSUE TITLE
vcffilter -r/--region

### ISSUE THREAD

**Issue by drmjc** [vcflib/vcflib#22]
Hi Erik,
I'm getting an error when trying to filter a vcf file to a genomic region. Further I couldn't see any documentation re the expected format of the --region setting, so hopefully this is correct usage:

`vcffilter -r chrM:1-100 dbsnp_137.hg19.vcf.gz`

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
Aborted
```

any ideas?
cheers,
Mark

using vcflib created on 2013-07-09

**Comment by ekg** [comment]
Hi Mark,

Unfortunately, I have not used this functionality much for some time, so
there is possibly a bug that should have been resolved here.

Try using tabix directly on the file, then piping the output into
vcffilter.  This is a workaround, but it is also a more flexible pattern,
and slightly more efficient from a time standpoint on multi-core systems.

tabix -h chrM:1-100 vars.vcf.gz | vcffilter -f "..."

**Comment by drmjc** [comment]
cheers Erik, that's a good workaround
