### ISSUE TITLE
error when running make

### ISSUE THREAD

**Issue by selcant** [vcflib/vcflib#220]
I tried compiling with gcc4.2, gcc6 and gcc7 and I get the same set of warnings with make failing with this msg:

src/cdflib.cpp:10043:15: error: ordered comparison between pointer and zero ('int *' and 'int')
  if ( n_data < 0 )
       ~~~~~~ ^ ~
11 warnings and 1 error generated.
make: *** [src/cdflib.o] Error 1

**Comment by kikeone** [comment]
Same problem, no solution yet.

**Comment by arcadeo** [comment]
same problem under macOS 10.13.2  with GNU Make 3.81

**Comment by kikeone** [comment]
Finally, I had to install it in other computer... 😞

**Comment by arcadeo** [comment]
I just added `*` in line 10043 of cdflib.cpp, changing from `n_data < 0` to `*n_data < 0` and that fixed it on my end. It was a weird bug

**Comment by ConradStack** [comment]
The solution recommended by @arcadeo worked for me.  I am running macOS 10.13.3 with clang-900.0.39.2.  

See also [this Medium post](https://medium.com/@jj1bdx/c-c-ordered-comparison-between-pointer-and-zero-actually-with-null-581374036431) about this error.

**Comment by manuelcorpas** [comment]
Had the same problem with line src/cdflib.cpp:10043:15: error: ordered comparison between pointer and zero ('int *' and 'int')

Version 10.13.4 GNU Make 3.81.

Changed  **n_data** **< 0** to ***n_data < 0** as @arcadeo suggested and it worked.

**Comment by SeekingMeaning** [comment]
(#221 and #247 are duplicates of this issue)

This appears to be fixed by https://github.com/vcflib/vcflib/commit/fd13e5cc0fc326fffb2d624463d7bd79db9a1436
