### ISSUE TITLE
vcfallelicprimitives duplicates INFO (Number=1) tags

### ISSUE THREAD

**Issue by hzpc-joostk** [vcflib/vcflib#225]
Hi! 

I am working on di, tri and tetraploid VCF data called using FreeBayes. I'd like to extract allelic primitives and I am using `vcfallelicprimitives` for this. It works great, even on multi-allelic sites (which `vt decompose_blocksub` does not), and phasing information is nicely retained. 

If there's nothing to decompose, the site is multi-allelic, and `-k/--keep-info` is passed, this tool duplicates the number of values of INFO tags with `Number=1`, which breaks downstream tools such as bcftools (htslib). 

Please, look at the following example, where INFO is truncated, the first column denotes the cmdline used for decomposing and the first line is the input:

```
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total read depth at the locus">
##INFO=<ID=DPB,Number=1,Type=Float,Description="Total read depth per bp at the locus; bases in reads overlapping / bases in haplotype">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
command                     #CHROM      POS   ID  REF  ALT  QUAL    FILTER  INFO                                                               FORMAT                MySample
                            ST4.03ch10  1709  .   T    A,G  918.21  .       ...;AF=0.25,0.5;AN=4;AO=11,27;CIGAR=1X,1X;DP=45;DPB=45;...         GT:DP:AD:RO:QR:AO:QA  0/1/2/2:45:7,11,27:7:265:11,27:434,1081
vcfallelicprimitives        ST4.03ch10  1709  .   T    A,G  918.21  .       AC=1,2;AF=0.25,0.5;LEN=1,1;TYPE=snp,snp;VAP                        GT                    0|1|2|2
vcfallelicprimitives -kg    ST4.03ch10  1709  .   T    A,G  918.21  .       ...;AF=0.25,0.5;AN=4,4;AO=11,27;CIGAR=1X,1X;DP=45,45;DPB=45,45;... GT:DP:AD:RO:QR:AO:QA  0|1|2|2:45:7,11,27:7:265:11,27:434,1081
```

In the truncated INFO, `AN`, `DP`, `DPB` fields are visible and do not reflect the specifications from the header: `Number=1`. 

I am far from a c++ expert, but this part of the code seems to be responsible for it 😉 : https://github.com/vcflib/vcflib/blob/b17eed65ed6b40f1244c4f09ae86800e9ae9a1d6/src/vcfallelicprimitives.cpp#L234-L240  
(I compiled the repo at this commit, therefor this specific reference).

Is it an easy fix? I guess this tool doesn't parse the header to get the specs, why not? Thanks!

**Comment by hzpc-joostk** [comment]
Here's another example:

input
```
ST4.03ch10    28888  .      ATG    AC,ACA 326.806       .      ...;AN=4;AO=9,6;CIGAR=1M1D1X,1M2X;DP=19;DPB=16;DPRA=0,0;EPP=5.18177,8.80089;EPPR=7.35324;GTI=1;LEN=2,2;...                    GT:DP:AD:RO:QR:AO:QA  0/1/1/2:19:2,9,6:2:79:9,6:369,242
```
output
```
ST4.03ch10    28888  .      AT     A      326.806       .      ...;AN=4;AO=9;CIGAR=1M1D1X;DP=19;DPB=16;DPRA=0;EPP=5.18177;EPPR=7.35324;GTI=1;LEN=1;...                                       GT                    0|1|1|0
ST4.03ch10    28889  .      T      C      326.806       .      ...;AN=4;AO=6;CIGAR=1M2X;DP=19;DPB=16;DPRA=0;EPP=8.80089;EPPR=7.35324;GTI=1;LEN=1;...                                         GT                    0|0|0|1
ST4.03ch10    28890  .      G      A,C    326.806       .      ...;AN=4,4;AO=6,9;CIGAR=1M2X,1M1D1X;DP=19,19;DPB=16,16;DPRA=0,0;EPP=8.80089,5.18177;EPPR=7.35324,7.35324;GTI=1,1;LEN=1,1;...  GT                    0|2|2|1
```

alignment (in order of GT)
```
ATG
A-C
A-C
ACA
```

Besides the duplicated values in INFO, another interesting event is happening. The `GT` of the second primitive (28889:T/C) is `0|0|0|1` or `TTTG` but in fact alleles 2 and 3 are deletions. The `GT` should be `0|.|.|1`, isn't it?

**Comment by dvanderleest** [comment]
I have the same type of issue with AN, DP, DPB and DPRA info fields. In my case it concerns a complex indel which I would like to simplify. Has there been some progres on this topic already?

```
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total read depth at the locus">
##INFO=<ID=DPB,Number=1,Type=Float,Description="Total read depth per bp at the locus; bases in reads overlapping / bases in haplotype">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=DPRA,Number=A,Type=Float,Description="Alternate allele depth ratio.  Ratio between depth in samples with each called alternate allele and those without.">

command                     #CHROM          POS     ID    REF          ALT                     QUAL    FILTER  INFO
orginal vcf                 Chromosome_01  2115    .     GAAAAAAC     GAAAAAAAAC,GGAAAAAAAC   5804.57  .       AB=0.303571,0.247401;ABP=209.455,269.587;AC=13,8;AF=0.203125,0.125;AN=64;AO=188,119;CIGAR=1M2I7M,1M2I7M;DP=1171;DPB=1309.25;DPRA=1.87482,1.8716
vcfallelicprimitives        Chromosome_01  2115    .     G            GAA,GGA                 5804.57  .       AC=13,8;AF=0.203125,0.125;LEN=2,2;TYPE=ins,ins
vcfallelicprimitives -kg    Chromosome_01  2115    .     G            GAA,GGA                 5804.57  .       AB=0.303571,0.247401;ABP=209.455,269.587;AC=13,8;AF=0.203125,0.125;AN=64,64;AO=188,119;CIGAR=1M2I7M,1M2I7M;DP=1171,1171;DPB=1309.25,1309.25;DPRA=1.87482,1.8716

expected output             Chromosome_01  2115    .     G            GAA,GGA                 5804.57  .       AB=0.303571,0.247401;ABP=209.455,269.587;AC=13,8;AF=0.203125,0.125;AN=64;AO=188,119;CIGAR=1M2I7M,1M2I7M;DP=1171;DPB=1309.25;DPRA=1.87482,1.8716
```

**Comment by hzpc-joostk** [comment]
> DPRA=1.87482,1.8716

@ikkextoch thanks for your input. In your case, the `DPRA` doesn't seem to be affected, is it?

**Comment by dvanderleest** [comment]
@hzpc-joostk You're correct, my bad. Only the AN, DP and DPB arr affected.
I have been working on a very ugly work around (I can't find a better alternative for grabbing only the first integer in the info field) using the following piece of code:

```
( while IFS=$* read -r line || [[ -n "$line" ]]; do
    newLine="${line}"
    for VAR in AN DP DPB; do
    
        foo=$(grep -o "$VAR=[0-9]*.[0-9]*,[0-9]*.[0-9]*" <<< $newLine)
        
        if [[ $foo ]]; then
            internalVAR=$(grep -o "[0-9]*\.*[0-9]*," <<< $foo)
        fi
        
        myVAR=""
        if [[ $internalVAR ]]; then
            myVAR=${internalVAR::-1}
        fi
        
        internalLine=$(sed "s/$VAR=[0-9]*\.*[0-9]*,[0-9]*\.*[0-9]*/$VAR=$myVAR/g" <<< $newLine)
        newLine=$internalLine
    done
    sed 's/[[ \t]]*/\t/g' <<< $newLine
done < vcfallelicprimitives.output.vcf ) > vcfallelicprimitives.output.restored.vcf
```
It assumes that the first argument in the info field is correct and substitutes the comma separated values for the first value. It does what it is supposed to do, but it is very slow for large files. Some parts might be redundant, but I didn't have time to check for that.

-----------------------------------------------------------------------------------------------------------
**Edit**: my appologies it doesn't do what it is supposed to do. It only did in my training set, which was smaller than the first chromosome. For some reason it cuts off all chromosomes after the first. 

-----------------------------------------------------------------------------------------------------------
**Second edit**: It probably truncated because it didn't handle lines in which the allelecount was above 2 properly, resulting in an error.

**Comment by dvanderleest** [comment]
Below is a function that should handle multiple output documents of vcfallelicprimitives used with the -kg option, in a proper manner:
```
restore_allelic_primitives(){
    for file in $@; do
        echo restoring file: $file with job number:
        while IFS=$* read -r line || [[ -n "$line" ]]; do
            newLine=$line
            affected=false
            for VAR in AN DP DPB; do
                if [ "$(grep "$VAR=[0-9]*\.*[0-9]*," <<< $newLine)" ]; then
                    affected=true
                fi
            done
            if $affected; then
                for VAR in AN DP DPB; do
                    INFOfield=$(grep -o "$VAR=[0-9]*\.*[0-9]*,*[0-9]*\.*[0-9]*\(,[0-9]*\.*[0-9]*\)*" <<< ${newLine})
                    INFO=($(grep -o "[0-9]*\.*[0-9]*" <<< $INFOfield))
                    
                    newLine=$(sed "s/$VAR=[0-9]*\.*[0-9]*,*[0-9]*\.*[0-9]*\(,[0-9]*\.*[0-9]*\)*/$VAR=$INFO/g" <<< ${newLine})
                done
            fi
            sed "s/[[ \t]]*/\t/g" <<< $newLine
        done < $file > ${file%.simple.vcf}.simple.restored.vcf &
    done
}
```
----------------------------------
## Explanation
The function reads the lines of the input document:
```
while IFS=$* read -r line || [[ -n "$line" ]]; do
    ....
done < $file 
```
For each line it checks whether a regular expression pattern is present, and if so it assigns the shell builtin true to  the variable affected. The pattern that it matches is "$VAR=[0-9]*\.*[0-9]*,".

Here $VAR is expanded to AN, DP or DPB. [0-9] matches any single digit between 0 and 9. The dot is escaped (as a single dot would substitute to any character except for linebreaks), and of course the *  (if not escaped) matches when the preceding token is present 0 or more times.
```
for VAR in AN DP DPB; do
    if [ "$(grep "$VAR=[0-9]*\.*[0-9]*," <<< $newLine)" ]; then
        affected=true
    fi
done
```
If (and only if) in the previous step `affected` is set to true, the following piece of code is executed:
```
for VAR in AN DP DPB; do
    infoFieldPattern="$VAR=[0-9]*\.*[0-9]*,*[0-9]*\.*[0-9]*\(,[0-9]*\.*[0-9]*\)*"
    INFOfield=$(grep -o $infoFieldPattern <<< ${newLine})
    INFO=($(grep -o "[0-9]*\.*[0-9]*" <<< $INFOfield))
    newLine=$(sed "s/$infoFieldPattern/$VAR=$INFO/g" <<< ${newLine})
done
```
Here INFOfield is assigned the value of the entire `$VAR` info field starting from "$VAR=" up to, but not including, the semicolon (;) of the next info field. This includes numbers with dots in them, as well as multiple numbers (for example "AN=1,2.22,333.333" should be perfectly matched). `INFO` is implicitly declared as **indexed** array and assigned all the numbers in `$INFOfield`. `sed "s/$infoFieldPattern/$VAR=$INFO/g" <<< ${newLine}` then substitutes the `$infoFieldPattern` for "$VAR=$INFO" in which `$VAR` is one of the values in AN DP and DPB while `$INFO` is the first value in the `INFO` array.

Hope this helps for now.
cheers

**Comment by hzpc-joostk** [comment]
@ikkextoch, thanks. Pretty robust but not flexible workaround. I am using an infamous Perl oneliner with a simple regex substitution on the VCF output (in a pipe):

```sh
perl -pe 's/(AN|DP|EPPR|GTI|MIN_DP|MQMR|NS|NUMALT|ODDS|PAIREDR|PQR|PRO|QR|RO|RPPR|SRF|SRP|SRR)=([0-9.e-]+)(,[0-9.e-]+)+/\1=\2/g'
```

This will match the (known by me) fields with prec `Number=1` followed by an equal sign `=` and two or more numbers, floats or scientific notations. The second and more num/float/scientific values are trimmed off. Although this does not check whether the first and extra values are the same, this works pretty well for my data!

```sh
pre_command in.vcf \
 | vcfallelicprimitives -kg \
 | perl -pe 's/(AN|DP|EPPR|GTI|MIN_DP|MQMR|NS|NUMALT|ODDS|PAIREDR|PQR|PRO|QR|RO|RPPR|SRF|SRP|SRR)=([0-9.e-]+)(,[0-9.e-]+)+/\1=\2/g' \
 | bgzip > out.vcf
```

**Comment by tseemann** [comment]
The more recent versions of `bcftools annotate` can do quite complex manipulations and editing of the VCF tags, and might be worth looking at.

http://www.htslib.org/doc/bcftools.html#annotate

**Comment by hzpc-joostk** [comment]
@tseemann Thanks for the suggestion! 

`bcftools annotate` is a very powerful tool, I use it very frequent. However, it is not able to solve this problem. One could remove the faulty INFO fields (`--remove 'AN,DP,EPPR,GTI,MIN_DP,MQMR,NS,NUMALT,ODDS,PAIREDR,PQR,PRO,QR,RO,RPPR,SRF,SRP,SRR'`), losing (valuable) information. We just want to rectify the affected fields (`Number=1`).

Another solution that works on both VCF and BCF would be using `pysam`.

```
import pysam

def process(vcfin, vcfout):
    fields = set(rec.name for rec in vcfin.header.info.values() if rec.number == 1)
    for rec in vcfin:
        if len(rec.alts) > 1:
            info = rec.info
            for field in fields:
                if field not in info:
                    continue
                info[field] = info[field][0]
        vcfout.write(rec)

with pysam.VariantFile('./tmp.vcf') as vcf:
    with pysam.VariantFile('./tmp.fix.vcf', 'w', header=vcf.header) as vcfout:
        process(vcf, vcfout)
```

Benchmarking on a VCF with 1048499 variants:

`perl -pe 's/(DPB|AN|DP|EPPR|GTI|MIN_DP|MQMR|NS|NUMALT|ODDS|PAIREDR|PQR|PRO|QR|RO|RPPR|SRF|SRP|SRR)=([0-9.e-]+)(,[0-9.e-]+)+/\1=\2/g'`

14.32s user 0.77s system 95% cpu 15.876 wall

Pysam

31.7s user 0.81s system 98% cpu 33.3 wall

I have checked and confirmed that the (VCF) output is the same.

The `pysam` approach takes double time, but check the header for fields that need correction and works on both VCF and BCF.

**Comment by ekg** [comment]
The key insanity is that there are values in VCF which are multiple but
don't correspond to the number of alleles at the locus. For instance,
DPB... I'm sorry this has been hard to deal with. I will look into a
solution in code.

**Comment by joys8998** [comment]
Hi there,

I faced the same error and I managed to perform this step like this.
`bcftools norm --threads 8 -f REFERENCE -m - INPUT_VCF 2> LOG| \
                vcfallelicprimitives -g -k -t DECOMPOSED 2>> LOG | \
                bcftools sort -m 6G  -O v 2>> LOG | \
                vcfuniq > OUTPUT_VCF 2>>LOG`

 These commands not only split variants into allelic primitives but also split records with multi-alternate values.

The INFO and FORMAT fields are ok in my case.

Hope it helps


Joy

**Comment by pjotrp** [comment]
vcfwave replaced vcfprimitivealleles. Please try and report on a new issue thread.
