### ISSUE TITLE
popStats and several other tools give Segmentation fault

### ISSUE THREAD

**Issue by etwatson** [vcflib/vcflib#227]
I have some VCFs produced by FreeBayes (VCFv4.1) that give Segmentation faults on several tools, including popStats.

To my experience, they are not malformed.

**Comment by zeeev** [comment]
Hi @etwatson, can you provide an example VCF and the command you used? There are several places were I opted to not check formatting and array bounds for speed, but I'll add some protection if you can provide examples.

**Comment by etwatson** [comment]
I was just about to edit and add this information, but re-ran the command with a different genotype likelihood format, which worked. I thought that I had PL coded in my VCF, but didn't. So, thanks for the quick reply.

**Comment by zeeev** [comment]
Although changing the parameters worked for you, segmentation faults are never okay. I'm re-opening the issue.
