### ISSUE TITLE
vcffilter does not handle floating point values of +/-Inf or NaN

### ISSUE THREAD

**Issue by blankenberg** [vcflib/vcflib#229]
These are valid floating point values as per the VCF spec, however, attempting to e.g.:
```
-f 'KEY < 1.0'
```
where `KEY` contains +Inf, -Inf, or NaN results in this error:
```could not convert field KEY=+Inf to float```

from the spec:
```
Data types supported by VCF are: 
...
Float (32-bit, formatted to match the regular expression ^[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?$, NaN, or +/-Inf) ...
```

**Comment by tseemann** [comment]
Dan - have you looked at `bcftools filter` lately?  
It is very good, and may not have this issue.

**Comment by blankenberg** [comment]
Will have another look. Thanks Torsten!

**Comment by tseemann** [comment]
https://samtools.github.io/bcftools//bcftools.html

**Comment by blankenberg** [comment]
@tseemann just wanted to confirm that `bcftools filter` handles this situation very nicely. Lots of very useful functionality available there. Thanks again :)
