### ISSUE TITLE
vcf2tsv not splitting multiallelics correctly

### ISSUE THREAD

**Issue by nick-hahner** [vcflib/vcflib#236]
I noticed in the current master, vcf2tsv isn't behaving the way I expected. Looks like it does not split the number=A field when splitting multiallelic sites.

Splitting number=A fields is the way version v1.0.0-rc0 worked, which seems most logical.

From @zeeev 's commit 73b7f1 with comment "... Adds comma lists rather than just indexing off alleles!" it sounds like this might be intentional, even though I don't understand the use case. 

I feel like splitting number=A should be the default and perhaps a flag should be added to keep the new behavior.

Not to draw too much attention to a major tangent, but perhaps splitting number=G fields is also a good idea?

**Comment by ekg** [comment]
Use vcfbreakmulti first and then feed it into vcf2tsv.

I also don't understand the use case and would prefer to switch it back to
the previous.

**Comment by zeeev** [comment]
Hi Erik,

Feel free to roll it back.

Best,

Zev
