### ISSUE TITLE
A (different?) make error

### ISSUE THREAD

**Issue by kgturner** [vcflib/vcflib#237]
Make is giving me an error, the result of which is that the vcflib/bin directory remains empty. Thanks in advance for help, sorry if it is obvious!

src/Variant.cpp: In member function ‘int64_t vcflib::Variant::get_sv_len(int)’:
src/Variant.cpp:186: error: call of overloaded ‘to_string(long int)’ is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
src/Variant.cpp: In member function ‘bool vcflib::Variant::canonicalize_sv(FastaReference&, std::vector<FastaReference*, std::allocator<FastaReference*> >, bool, int)’:
src/Variant.cpp:245: error: expected primary-expression before ‘[’ token
src/Variant.cpp:245: error: expected primary-expression before ‘]’ token
src/Variant.cpp:245: error: expected primary-expression before ‘const’
src/Variant.cpp:245: error: expected ‘,’ or ‘;’ before ‘{’ token
src/Variant.cpp:2729: error: expected ‘}’ at end of input
src/Variant.cpp: At global scope:
src/Variant.cpp:2729: error: expected ‘}’ at end of input
make: *** [src/Variant.o] Error 1

**Comment by tseemann** [comment]
Your compiler is too old, try g++ 4.9 or higher.
