### ISSUE TITLE
LD executable conflicts with /usr/bin/ld

### ISSUE THREAD

**Issue by sjackman** [vcflib/vcflib#239]
I was very confused today when running `gcc` produced this output:

```
❯❯❯ gcc /dev/null
collect2: fatal error: ld terminated with signal 11 [Segmentation fault: 11]
compilation terminated.
…
              This is a vcflib::GPAT++ tool           
-Version       : 3e03
-Contact       : zev.kronenberg [at] gmail.com 
…
```

It turns out the the `vcflib` formula of Homebrew installs all the tools compiled bin `vcflib` in the `bin` directory, which includes `LD`. On a case insensitive file system, which is the default on macOS, this `LD` executable conflicts with `/usr/bin/ld`. Could `LD` please be renamed to `vcflib-ld`?

**Comment by zeeev** [comment]
Hi Shaun,

Thank you for the suggestion. I will make that change tomorrow morning. 

Best,

Zev

**Comment by tseemann** [comment]
@sjackman is APFS still case-preserving but case-insenitive?

**Comment by sjackman** [comment]
HFS+ can be either https://en.wikipedia.org/wiki/HFS_Plus but the default is case-insensitive and case-preserving. Programs/scripts often unintentionally rely on it being case insensitive, so changing the default can cause some programs to break mysteriously. For example the program's data file is called `Data.db` on disk, but the program opens a file named `data.db` at run time

**Comment by sjackman** [comment]
Thanks for the quick response, Zev! Is there a stable release planned with this fix?

**Comment by tseemann** [comment]
Fixed in https://github.com/vcflib/vcflib/commit/5b0f4d5b0cbdfb7b890353b08b9d397c92312d8f
