### ISSUE TITLE
polyploid vcf

### ISSUE THREAD

**Issue by sanjeevksh** [vcflib/vcflib#241]
I have a vcf obtained through gatk4 processing which I want to convert to a human-readable genotype format for downstream data processing. The vcf file has a mix of diploid, tetraploid and few hexaploid samples. I wish to know if vcfgenotypes/vcfglxgt work fine with non-diploid samples?

Thanks,
Sanjeev

**Comment by ekg** [comment]
I believe it should. It was designed to work with freebayes which is often
applied to exactly the same kinds of polyploid vcf files.

**Comment by sanjeevksh** [comment]
Thanks Erik, that's very reassuring,
Sanjeev

**Comment by everestial** [comment]
Sanjeev: You can also look into the application VCFSimplify https://github.com/everestial/VCF-Simplify if you want to convert VCF to tabular or more readable format. This app also has the capability to convert tabular data back to VCF. 

Thanks,

**Comment by sanjeevksh** [comment]
@everestial
Thanks for pointing me to this application, indeed this will be very helpful,
Sanjeev
