### ISSUE TITLE
vcflib crash during install on ubuntu 16.04

### ISSUE THREAD

**Issue by thsierocinski** [vcflib/vcflib#242]
`totot@Bioinfo:~/bins/vcflib-master$ make

if [ ! -d bin ]; then mkdir -p bin; fi

if [ ! -d lib ]; then mkdir -p lib; fi

if [ ! -d include ]; then mkdir -p include; fi

if [ ! -d obj ]; then mkdir -p obj; fi

cd tabixpp && make && cp *.h* /home/thomas/bins/vcflib-master/include/

make[1]: Entering directory '/home/thomas/bins/vcflib-master/tabixpp'

make[1]: *** No targets specified and no makefile found.  Stop.

make[1]: Leaving directory '/home/thomas/bins/vcflib-master/tabixpp'

Makefile:170: recipe for target 'tabixpp/tabix.o' failed

make: *** [tabixpp/tabix.o] Error 2`

**Comment by janxkoci** [comment]
If you want to make your life easier, use [miniconda](https://conda.io/miniconda.html) / [anaconda](https://www.anaconda.com/download/), add [Bioconda channel](https://bioconda.github.io/), then you can install with simple:
`conda install vcflib freebayes tabix`

You are all welcome ;)
