### ISSUE TITLE
Error in  Linux version 2.6.32-696.23.1.el6.x86_64 (mockbuild@x86-01.bsys.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) ) #1 SMP Tue Mar 13 22:44:18 UTC 2018

### ISSUE THREAD

**Issue by Shicheng-Guo** [vcflib/vcflib#243]
Error in  Linux version 2.6.32-696.23.1.el6.x86_64 (mockbuild@x86-01.bsys.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) ) #1 SMP Tue Mar 13 22:44:18 UTC 2018

src/Variant.cpp: In member function ‘int64_t vcflib::Variant::get_sv_len(int)’:
src/Variant.cpp:186: error: call of overloaded ‘to_string(long int)’ is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
src/Variant.cpp: In member function ‘bool vcflib::Variant::canonicalize_sv(FastaReference&, std::vector<FastaReference*, std::allocator<FastaReference*> >, bool, int)’:
src/Variant.cpp:245: error: expected primary-expression before ‘[’ token
src/Variant.cpp:245: error: expected primary-expression before ‘]’ token
src/Variant.cpp:245: error: expected primary-expression before ‘const’
src/Variant.cpp:245: error: expected ‘,’ or ‘;’ before ‘{’ token
src/Variant.cpp:2729: error: expected ‘}’ at end of input
src/Variant.cpp: At global scope:
src/Variant.cpp:2729: error: expected ‘}’ at end of input
make: *** [src/Variant.o] Error 1

**Comment by tseemann** [comment]
Your C++ compiler is too old - need g++ 4.9 or higher.
We recommend using conda or brew to install vcflib.
