### ISSUE TITLE
vcfflatten doesn't fix GT in GATK format

### ISSUE THREAD

**Issue by alehresmann** [vcflib/vcflib#253]
Hello, I've been using vcfflatten and noticed a small discrepancy.

Note the following:
1. I use VCFs generated from GATK, hence their format might be singular compared to VCFs from other sources. For more info on their format, see https://software.broadinstitute.org/gatk/documentation/article?id=11005
2. I use VCFs which have rather large cohorts, thus my percentage of polyallelic sites is high.

In any case, observe the following:
The beginning of a particular site from an unflattened VCF (I've removed some additional stuff in the INFO column that we don't need):

`1	3679775	rs10910024	C	<NON_REF>,T	1408.77	.	AC=0,202;AF=0,0.245742;AN=822;	GT:DP:GQ:MIN_DP:PL:AD:PGT:PID:SAC:SB	0/0:19:48:19:0,48,720,.,.,.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.	0/0:19:54:19:0,54,810,.,.,.:.:.:.:.:.	0/2:26:99:.:499,532,931,0,399,354:11,0,15:0|1:3679775_C_T:9,2,7,8,0,0:9,2,7,8	0/0:.:.:.:.:.:.:.:.:.	0/2:13:99:.:236,254,458,0,204,182:6,0,7:.:.:5,1,5,2,0,0:5,1,5,2	0/2:24:99:.:396,427,713,0,286,244:10,0,14:.:.:6,4,9,5,0,0:6,4,9,5	0/2:19:99:.:261,291,633,0,342,315:10,0,9:.:.:8,2,8,1,0,0:8,2,8,1	0/0:.:.:.:.:.:.:.:.:.	0/2:19:99:.:261,288,622,0,334,305:9,0,10:.:.:8,1,8,2,0,0:8,1,8,2	0/0:.:.:.:.:.:.:.:.:.	2/2:25:75:.:930,930,930,75,75,0:0,0,25:.:.:0,0,19,6,0,0:0,0,19,6 [...]`

Observe that the ALT alleles are <NON_REF>, and T, and that their respective allele counts are 0 and 202. GATK specifies which allele is present in the field GT (genotype), and we can see in fact a number of individuals with the T allele for instance, noted by the 0/2, or even 2/2. 

I then pass my VCF to vcfflatten, and look at its output in the same location:

`1	3679775	rs10910024	C	T	1408.77	.	AC=202;AF=0.245742;AN=822;	GT:DP:GQ:MIN_DP:PL:AD:PGT:PID:SAC:SB	0/0:19:48:19:0,.,.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.	0/0:.:.:.:.:.:.:.:.:.	0/0:19:54:19:0,.,.:.:.:.:.:.	0/2:26:99:.:499,0,354:11,0,15:0|1:3679775_C_T:9,2,7,8,0,0:9,2,7,8	0/0:.:.:.:.:.:.:.:.:.	0/2:13:99:.:236,0,182:6,0,7:.:.:5,1,5,2,0,0:5,1,5,2	0/2:24:99:.:396,0,244:10,0,14:.:.:6,4,9,5,0,0:6,4,9,5	0/2:19:99:.:261,0,315:10,0,9:.:.:8,2,8,1,0,0:8,2,8,1	0/0:.:.:.:.:.:.:.:.:.	0/2:19:99:.:261,0,305:9,0,10:.:.:8,1,8,2,0,0:8,1,8,2	0/0:.:.:.:.:.:.:.:.:.	2/2:25:75:.:930,75,0:0,0,25:.:.:0,0,19,6,0,0:0,0,19,6 [...]`

We here observe that the T allele has been correctly chosen as the ALT allele, as its AC is the highest compared to any other ALT alleles present, here only <NON_REF> with an AC of 0. However, the GT entries have not been changed: the ones with the T allele still indicate the allele count 2, despite the fact that there are only now two alleles to choose from, the REF allele and the ALT allele. 

This poses a number of problems, most especially for further usage in other libraries, as they will often consider this file now invalid (this is the case for bcftools for instance). Now we can obviously fix these to now indicate the proper count, but suppose we had some individual with yet anothe ralt allele, hence for instance, 0/3, which was then filtered out by vcfflatten because of its low allele count, what do you do? Do you instead mark it as 0/0 and claim instead that this was a reference allele? do you declare that site as missing? I'm not sure how you want to handle this. In any case however, I figured I'd bring your attention to this.

**Comment by ekg** [comment]
Could the <NON_REF> allele be the problem? I don't remember how vcfflatten
works in these cases.
