### ISSUE TITLE
segmentation fault with vcfintersect

### ISSUE THREAD

**Issue by SusanaFreitas** [vcflib/vcflib#255]
Dear all,
I have been trying to run this command
vcfintersect -b stacks.bed Tms.scaf.vcf > Tms.intersect.vcf
But I get a segmentation fault (even if I run it without memory constraints).
The Tms.scaf.vcf file was originated by Freebayes (and then used vcfallelicprimitives) and the stacks.bed was originated by stacks and then converted to bed with plink.

Does anyone have any suggestion of what might be happening?
Thanks in advance
Susana

**Comment by tseemann** [comment]
What version are you using?

`bcftools isec` might be another option:
https://samtools.github.io/bcftools/bcftools.html#isec
