### ISSUE TITLE
Segfault and other errors with a version 4.1 VCF

### ISSUE THREAD

**Issue by vodkatad** [vcflib/vcflib#26]
Hello, I'm writing to ask if this lib should support version 4.1 VCF files because I'm trying various tools on a file (gotten from the GEUVADIS consortium) and I encounter different kind of errors (the same tools on the given sample vcf runs without problems), for example a segfault with vcfstats and a "terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check" with vcf2fasta, while for example vcfsamplenames works.

Thanks,
E.

**Comment by ekg** [comment]
What is the URL of the GEUVADIS data that is demonstrating these problems?

**Comment by vodkatad** [comment]
http://www.ebi.ac.uk/arrayexpress/files/E-GEUV-1/GEUVADIS.chr22.PH1PH2_465.IMPFRQFILT_BIALLELIC_PH.annotv2.genotypes.vcf.gz

I've not investigated in any way what could be the problem, so if you tell me that it should be supported I could lend my delevoper (limited to very little vcf peculiarities right now, I fear...but I'm trying to catch up in these aspects as fast as I can) help.
Tomorrow I will try to dowload again the file and redo the tests, but as long as it's a gz I don't expect a byte corruption problem in the downloading phase.

Thank you for your help

**Comment by zeeev** [comment]
@vodkatad I'm closing this issue as we've done some major updates since 2013.  The error you reported 'should' be resolved.  Please open a new bug report if it's not.  Thank you very much for the bug report.
