### ISSUE TITLE
vcf2tsv - output with missing information of the INFO field 

### ISSUE THREAD

**Issue by roselucia** [vcflib/vcflib#268]
Hi,

I am using vcf2tsv on my galaxy docker (Galaxy version 18.09, https://github.com/bgruening/docker-galaxy-stable). Unfortunately for one datatype of my data I am missing information of the INFO field after using vcf2tsv. 
I tried out different things, such as using VCFbreakCreateMulti followed by the VCFtoTab-delimited or VCFsort followed by VCFtoTab-delimited. However, I was left with exactly the same.
In the attached two picture you find example variants, where information from the INFO field
example 1 did neither get lost using VCFtoTab on the galaxy docker
example 2 did get lost using VCFtoTAB on the galaxy docker.
What can I do to probably parse my data for this datatype without losing any information. 
Do you need an example input file as well as the matching output file? How can I sent them to you?
Thanks for your help.
All the best,
Rose
![example 1](https://user-images.githubusercontent.com/53077304/67195503-56317980-f3f9-11e9-8d43-617d8d0e15aa.png)
![example 2](https://user-images.githubusercontent.com/53077304/67195520-5b8ec400-f3f9-11e9-8a25-613ea93add90.png)

**Comment by tseemann** [comment]
If you have access to `bcftools` in Galaxy, `bcftools query` is very flexible:
```
Examples:
        bcftools query -f '%CHROM\t%POS\t%REF\t%ALT[\t%SAMPLE=%GT]\n' file.vcf.gz
```

**Comment by roselucia** [comment]
Hi,
thanks for the response. 
I tried out the tool and it worked well for rather simple queries. However I am stuck at the point where I would like to only extract the first annotation of the ANN Tag in the Info field.

This is what I used for a query in Galaxy (toolshed.g2.bx.psu.edu/repos/iuc/bcftools_query/bcftools_query/1.4.0):

%CHROM\t%POS\t%ID\t%REF\t%ALT\t%QUAL\t%FILTER\t%INFO/DP\t%INFO/UMT\t%INFO/ANN\t%INFO/ANN{0}\t%INFO/ExAC_NFE\t%INFO/AF_popmax\t%INFO/AF_nfe\t%INFO/1000g2015aug_all\t%INFO/1000g2015aug_eur\t [ %GT] \t [ %VF]\n

I am left with the following error message: Error: todo: type 7

I actually wanted not only to extract the first Annotation of the comma separated list of annotations in the ANN Tag of the INFO field, but I also wanted to further split this first annotation in its subcontents, which are separated by "|".
Furthermore I don't know how to handle the problem that my gnomad annotation for genome and exome have the same INFO-Tag and bcftools only extracts one of those values (vcftotab always generated a comma separates list for alle the values available for that one INFO-TAG). Do you have any suggestions?


Thanks for the help!
All the best 
Rose
