### ISSUE TITLE
vcf2tsv (with snpeff vcd) parsing problem

### ISSUE THREAD

**Issue by hmkim** [vcflib/vcflib#27]
Hi, 
I tried convert vcf to tsp with vcf2tsv in vcflib package.
but, I have a problem when I parsing.

for example, I can't get an snpeff annotation on tsv file (converted)
what is the problem?

root@GR0002:/gg/tmp/t6_out# grep 47123898 out_snpeff.geneSets.vcf
chr1    47123898    .   TAAA    TAAAA   554.27  PASS    AC=1;AF=0.167;AN=6;BaseQRankSum=-0.710;DP=63;FS=2.251;HaplotypeScore=16.2535;MLEAC=1;MLEAF=0.167;MQ=60.28;MQ0=0;MQRankSum=0.127;QD=12.32;RPA=15,16,12;RU=A;ReadPosRankSum=-0.091;STR;EFF=INTRON(MODIFIER||||177|ATPAF1||CODING|NM_001256418.1|4|1),INTRON(MODIFIER||||240|ATPAF1||CODING|NM_001243728.1|3|1),INTRON(MODIFIER||||283|ATPAF1||CODING|NM_001042546.2|3|1),INTRON(MODIFIER||||351|ATPAF1||CODING|NM_022745.4|3|1);PhastCons=0.001;MSigDb=CAGGTG_V$E12_Q6,CREIGHTON_ENDOCRINE_THERAPY_RESISTANCE_3,GCTTGAA_MIR-498,GOBERT_OLIGODENDROCYTE_DIFFERENTIATION_DN,GSE11864_CSF1_IFNG_VS_CSF1_IFNG_PAM3CYS_IN_MAC_UP,GSE11864_CSF1_VS_CSF1_IFNG_PAM3CYS_IN_MAC_UP,GSE13229_IMM_VS_MATURE_NKCELL_UP,GSE14308_TH2_VS_NAIVE_CD4_TCELL_DN,GSE14769_UNSTIM_VS_40MIN_LPS_BMDM_DN,GSE14769_UNSTIM_VS_80MIN_LPS_BMDM_UP,GSE18791_CTRL_VS_NEWCASTLE_VIRUS_DC_18H_UP,GSE2197_CPG_DNA_VS_UNTREATED_IN_DC_DN,GSE25087_FETAL_VS_ADULT_TREG_UP,GSE27786_CD4_TCELL_VS_MONO_MAC_UP,GSE27786_CD8_TCELL_VS_MONO_MAC_UP,GSE27786_CD8_TCELL_VS_NEUTROPHIL_UP,GSE27786_ERYTHROBLAST_VS_NEUTROPHIL_DN,GSE27786_LSK_VS_MONO_MAC_UP,GSE27786_NKTCELL_VS_MONO_MAC_UP,GSE27786_NKTCELL_VS_NEUTROPHIL_UP,GSE7460_CTRL_VS_FOXP3_OVEREXPR_TCONV_DN,GSE7460_FOXP3_MUT_VS_HET_ACT_TCONV_DN,GSE7460_FOXP3_MUT_VS_WT_ACT_TCONV_DN,GSE7460_WT_VS_FOXP3_HET_ACT_TCONV_UP,IVANOVA_HEMATOPOIESIS_EARLY_PROGENITOR,KRIEG_KDM3A_TARGETS_NOT_HYPOXIA,LASTOWSKA_NEUROBLASTOMA_COPY_NUMBER_DN,LU_IL4_SIGNALING,NFE2L2.V2,NUYTTEN_EZH2_TARGETS_DN,NUYTTEN_NIPP1_TARGETS_DN,PILON_KLF1_TARGETS_DN,SENESE_HDAC3_TARGETS_DN,TACTTGA_MIR-26A_MIR-26B,TCTGATA_MIR-361,V$E2F_Q2,V$TEF1_Q6,WEI_MIR34A_TARGETS,chr1p33    GT:AD:DP:GQ:PL  0/0:10,1,0:18:4:0,4,274,42,314,654  ./0:3,0,7:22:49:255,281,378,0,49,220    ./1:1,5,6:23:99:414,287,347,127,0,354
chr1    47123898    .   TAAA    T   554.27  PASS    AC=2;AF=0.333;AN=6;BaseQRankSum=-0.710;DP=63;FS=2.251;HaplotypeScore=16.2535;MLEAC=2;MLEAF=0.333;MQ=60.28;MQ0=0;MQRankSum=0.127;QD=12.32;RPA=15,16,12;RU=A;ReadPosRankSum=-0.091;STR;EFF=INTRON(MODIFIER||||177|ATPAF1||CODING|NM_001256418.1|4|1),INTRON(MODIFIER||||240|ATPAF1||CODING|NM_001243728.1|3|1),INTRON(MODIFIER||||283|ATPAF1||CODING|NM_001042546.2|3|1),INTRON(MODIFIER||||351|ATPAF1||CODING|NM_022745.4|3|1);PhastCons=0.001;MSigDb=CAGGTG_V$E12_Q6,CREIGHTON_ENDOCRINE_THERAPY_RESISTANCE_3,GCTTGAA_MIR-498,GOBERT_OLIGODENDROCYTE_DIFFERENTIATION_DN,GSE11864_CSF1_IFNG_VS_CSF1_IFNG_PAM3CYS_IN_MAC_UP,GSE11864_CSF1_VS_CSF1_IFNG_PAM3CYS_IN_MAC_UP,GSE13229_IMM_VS_MATURE_NKCELL_UP,GSE14308_TH2_VS_NAIVE_CD4_TCELL_DN,GSE14769_UNSTIM_VS_40MIN_LPS_BMDM_DN,GSE14769_UNSTIM_VS_80MIN_LPS_BMDM_UP,GSE18791_CTRL_VS_NEWCASTLE_VIRUS_DC_18H_UP,GSE2197_CPG_DNA_VS_UNTREATED_IN_DC_DN,GSE25087_FETAL_VS_ADULT_TREG_UP,GSE27786_CD4_TCELL_VS_MONO_MAC_UP,GSE27786_CD8_TCELL_VS_MONO_MAC_UP,GSE27786_CD8_TCELL_VS_NEUTROPHIL_UP,GSE27786_ERYTHROBLAST_VS_NEUTROPHIL_DN,GSE27786_LSK_VS_MONO_MAC_UP,GSE27786_NKTCELL_VS_MONO_MAC_UP,GSE27786_NKTCELL_VS_NEUTROPHIL_UP,GSE7460_CTRL_VS_FOXP3_OVEREXPR_TCONV_DN,GSE7460_FOXP3_MUT_VS_HET_ACT_TCONV_DN,GSE7460_FOXP3_MUT_VS_WT_ACT_TCONV_DN,GSE7460_WT_VS_FOXP3_HET_ACT_TCONV_UP,IVANOVA_HEMATOPOIESIS_EARLY_PROGENITOR,KRIEG_KDM3A_TARGETS_NOT_HYPOXIA,LASTOWSKA_NEUROBLASTOMA_COPY_NUMBER_DN,LU_IL4_SIGNALING,NFE2L2.V2,NUYTTEN_EZH2_TARGETS_DN,NUYTTEN_NIPP1_TARGETS_DN,PILON_KLF1_TARGETS_DN,SENESE_HDAC3_TARGETS_DN,TACTTGA_MIR-26A_MIR-26B,TCTGATA_MIR-361,V$E2F_Q2,V$TEF1_Q6,WEI_MIR34A_TARGETS,chr1p33    GT:AD:DP:GQ:PL  0/0:10,1,0:18:4:0,4,274,42,314,654  0/1:3,0,7:22:49:255,281,378,0,49,220    ./1:1,5,6:23:99:414,287,347,127,0,354

root@GR0002:/gg/tmp/t6_out# /gg/bio/tools/vcflib/bin/vcf2tsv -n . out_snpeff.geneSets.vcf > z

grep 47123898 zroot@GR0002:/gg/tmp/t6_out# grep 47123898 z
chr1    47123898    .   TAAA    TAAAA   554.27  PASS    .   1   0.167   .   .   .   6   .   -0.710  63  .   .   .   2.251   .   16.2535 .   1   0.167   60.28   0   0.127   .   0.001   12.32   .   A   -0.091  0   1
chr1    47123898    .   TAAA    T   554.27  PASS    .   2   0.333   .   .   .   6   .   -0.710  63  .   .   .   2.251   .   16.2535 .   2   0.333   60.28   0   0.127   .   0.001   12.32   .   A   -0.091  0   1
root@GR0002:/gg/tmp/t6_out# /gg/bio/tools/vcflib/bin/vcf2tsv out_snpeff.geneSets.vcf | grep 47123898
chr1    47123898    .   TAAA    TAAAA   554.27  PASS        1   0.167               6       -0.710  63              2.251       16.2535     1   0.167   60.28   0   0.127       0.001   12.32       A   -0.091  0   1
chr1    47123898    .   TAAA    T   554.27  PASS        2   0.333               6       -0.710  63              2.251       16.2535     2   0.333   60.28   0   0.127       0.001   12.32       A   -0.091  0   1

**Comment by jenzopr** [comment]
I investigated a bit further and noticed that the `,` inside an `INFO` field is a problem:

```
cat test.vcf
```
```
##fileformat=VCFv4.1
##INFO=<ID=SINGLEFIELD,Number=1,Type=String,Description="A single value">
##INFO=<ID=COMMAFIELD,Number=.,Type=String,Description="A possibly comma-separated value">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Sample1
chr1	10	.	A	T	100	PASS	SINGLEFIELD=abc;COMMAFIELD=def	GT	0/1
chr1	20	.	C	A	100	PASS	SINGLEFIELD=ghi;COMMAFIELD=abc,def	GT	0/1
chr1	30	.	C	A	100	PASS	SINGLEFIELD=def;COMMAFIELD=abc|def	GT	0/1
```

And then:

```
vcf2tsv -g test.vcf
CHROM	POS	ID	REF	ALT	QUAL	FILTER	COMMAFIELD	SINGLEFIELD	SAMPLE	GT
chr1	10	.	A	T	100	PASS	def	abc	Sample1	0/1
chr1	20	.	C	A	100	PASS		ghi	Sample1	0/1
chr1	30	.	C	A	100	PASS	abc|def	def	Sample1	0/1
```

The first and third SNP do not have a comma in `COMMAFIELD`, the second has. vcf2tsv fails to resolve this comma-separated field.
Best,
Jens

**Comment by zeeev** [comment]
@jenzopr thanks looking into this issue. Can you provide a small working example?

**Comment by jenzopr** [comment]
@zeeev thanks a lot for your reply. I would consider the comment above already as a small working example. If you copy/paste the vcf data into a file called `test.vcf` and call `vcf2tsv -g test.vcf`, you should get exactly the output I included. Otherwise, let me know what you consider a good small working example and I'll be happy to provide it here.
