### ISSUE TITLE
Abort trap 6 (Python error?)

### ISSUE THREAD

**Issue by beausoleilmo** [vcflib/vcflib#282]
I just installed vcf lib using this: 

`brew install brewsci/bio/vcflib`

But when I run:

```
$ vcfrandomsample
```

I get this: 

```
dyld: Symbol not found: __ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13find_first_ofEPKcmm
  Referenced from: /usr/local/bin/vcfrandomsample
  Expected in: /usr/lib/libstdc++.6.dylib
 in /usr/local/bin/vcfrandomsample
Abort trap: 6
```

I'm on macOS Mojave 10.14.6, Mac Pro. 

```
$ brew --version
Homebrew 2.2.5
Homebrew/homebrew-core (git revision 23125; last commit 2020-02-06)
```

When I look for my active python version 
```
$ python --version
Python 2.7.17
```

I made an alias of python so now it uses python3:
```
$ python --version
Python 3.7.6
```

Then reinstalled vcflib: 
`brew reinstall vcflib` without luck... 

I decided to install it that way: 
```
git clone --recursive https://github.com/vcflib/vcflib.git
cd vcflib
make -j
```

And this worked.

**Comment by markscherz** [comment]
I am having the same problem. I have interpreted it as some difficulty with the libstdc++.6.dylib dependency, which has been deprecated for seven years apparently. Your solution also worked for me, but it's a shame the homebrew version is not working properly.

**Comment by sara-wennersten** [comment]
I am having this exact issue. Installing it using this:
```
git clone --recursive https://github.com/vcflib/vcflib.git
cd vcflib
make -j
```
did not work for me. Anyone else able to work through this issue?

Thank you!
