### ISSUE TITLE
vcffilter gives segmentation fault when filtering by contig name (CHROM)

### ISSUE THREAD

**Issue by elcortegano** [vcflib/vcflib#284]
I am trying to filter a VCF file by contig name only, using the values in the CHROM field of the vcf, for example:

    vcffilter -f "CHROM == C0001 | CHROM == C0002" file.vcf.gz

But this only prints the VCF file metadata and then returns a `Segmentation fault (core dumped)
` error. The same happens when the filter is applied to only one contig.

**Comment by tseemann** [comment]
you might need to put the name in quotes
eg. `- 'CHROM == "C0001" | ... '`

or use bcftools filter
https://samtools.github.io/bcftools/howtos/filtering.html

**Comment by elcortegano** [comment]
With the name in quotes it also fails, but thank you for the suggestion with bcftools!
