### ISSUE TITLE
Default build is debug

### ISSUE THREAD

**Issue by jkbonfield** [vcflib/vcflib#293]
The Makefile should probably include

```
CMAKE_FLAGS?=-DCMAKE_BUILD_TYPE=Release 
```

It can still be overridden on the command line, but at least it means a git clone and make -j, as suggested by the README file, gives you an optimised build.  This is particularly important given that by default cmake produces makefiles that do not report the command line being used, so it's non-obvious that the builds don't have -O options.

PS Argh sorry for odd initial post; github randomly decided return was the same as submit.

**Comment by pjotrp** [comment]
Hi James, if you use the build instructions in the updated README cvflib should build with ~-O3~. See 
https://github.com/vcflib/vcflib/blob/master/README.md#build-from-source
