### ISSUE TITLE
Bug in vcfnulldotslashdot

### ISSUE THREAD

**Issue by roddypr** [vcflib/vcflib#294]
Hi,

This script isn't working properly for me. It gives me the error "TypeError: can't multiply sequence by non-int of type 'float'"

I think the problem is that the `bincoeff` function is returning a float instead of an integer.

https://github.com/vcflib/vcflib/blob/cbb6c119c35094a7058ad51e6e0bc460aa4b7732/scripts/vcfnulldotslashdot#L6

**Comment by pjotrp** [comment]
See #307
