### ISSUE TITLE
vcffilter more field from the VCF

### ISSUE THREAD

**Issue by elcortegano** [vcflib/vcflib#296]
It is my understanding that vcffilter only works on the INFO field, genotypes and QUAL value. Would it be possible to expand the use of this utility to make it work for other fields in the VCF?

I'm working with large VCF files that involve non-variant sites and would like particularly to filter by value in ALT, eg. `vcffilter -f "! ( ALT = . )" file.vcf.gz`, and possibly by other values (eg. at reference G or C sites,etc).

**Comment by pjotrp** [comment]
Take a look at https://github.com/vcflib/bio-vcf/
