### ISSUE TITLE
Vcflib/vcffilter error

### ISSUE THREAD

**Issue by nadiabeyg** [vcflib/vcflib#297]
Hi,
I am using vcfilter on my VCF file `vcffilter -f "QUAL / AO > 10 & SAF > 0 & SAR > 0 & RPR > 1 & RPL > 1 & EPP >= 3 & SRP >= 3 & SAP >= 3"` Error: cannot compare (>) objects of dissimilar types
3 2

I tried doing this too `vcffilter -f " QUAL >= 30 " ` Error: segmentation fault

filter3: `vcfbiallelic | vcffilter -f "QUAL / AO > 10 & SAF > 0 & SAR > 0 & RPR > 1 & RPL > 1 & EPP >= 3 & SRP >= 3 & SAP >= 3 & MQM / MQMR >= 0.4 & MQM / MQMR <= 2.5`
cannot compare (>) objects of dissimilar types
3 2
It only works by using just > or <. How to apply >= or <= check ?

Thanks

**Comment by pjotrp** [comment]
Did you figure it out?
