### ISSUE TITLE
Time for a new release

### ISSUE THREAD

**Issue by mr-c** [vcflib/vcflib#298]
Debian would appreciate a new release, as we use vcflib v1.0.1 for the vg package, and currently they are 34 commits ahead https://github.com/vcflib/vcflib/compare/v1.0.1...a31f0578569a2dfb8ecc99d9cbde03cd5a0b2fd4

Thanks!

**Comment by pjotrp** [comment]
@mr-c is vcflib already in Debian? It has a few useful tools and we could try creating a release.

**Comment by mr-c** [comment]
> @mr-c is vcflib already in Debian? It has a few useful tools and we could try creating a release.

Yes, https://tracker.debian.org/pkg/libvcflib

versions

    oldstable: 1.0.0~rc1+dfsg1-3
    old-bpo: 1.0.0~rc1+dfsg1-6~bpo9+1
    stable: 1.0.0~rc2+dfsg-2
    stable-bpo: 1.0.1+dfsg-3~bpo10+1
    testing: 1.0.1+dfsg-4
    unstable: 1.0.1+dfsg-4

**Comment by pjotrp** [comment]
From the build log it appears to split into three packages: libvcflib, libvcflib-dev and libvcflib-tools. Can't argue with the naming ;)

**Comment by pjotrp** [comment]
We released!

**Comment by mr-c** [comment]
Thank you @pjotrp !

**Comment by mr-c** [comment]
@pjotrp The v1.0.2 release is missing a submodules-included tarball, which is why Debian didn't notice it

Can you attach a `vcflib-1.0.2-src.tar.gz` to https://github.com/vcflib/vcflib/releases/tag/v1.0.2 ?

And maybe update your release checklist? :-)

**Comment by pjotrp** [comment]
Yes, sure. Any recommend way of creating the tarball? No .git in there, I presume.

**Comment by mr-c** [comment]
@pjotrp I make a new `git clone --recursive` of the repo and then `find ${repo_checkout_folder} -name .git -type d | xargs rm -Rf`

**Comment by pjotrp** [comment]
I added the tarball with submodules at https://github.com/vcflib/vcflib/releases

**Comment by mr-c** [comment]
Thank you @pjotrp , that works for us!
