### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [vcflib/vcflib#301]
Would you like to wrap any pointers with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [main 1](https://github.com/vcflib/vcflib/blob/d4073c3c89da2fff1748536032850465f6428428/src/sequenceDiversity.cpp#L413)
- [main 2](https://github.com/vcflib/vcflib/blob/d4073c3c89da2fff1748536032850465f6428428/src/pFst.cpp#L254)

**Comment by pjotrp** [comment]
Sure. Do you intend to send a patch?

**Comment by Glebanister** [comment]
Hi! I would like to work on this issue. But your code style is not quite clear for me. Is there any description of a preferred way to write code?

> Sure. Do you intend to send a patch?

**Comment by Glebanister** [comment]
Pull request #306

**Comment by pjotrp** [comment]
Merged!
