### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [vcflib/vcflib#302]
Would you like to add more error handling for return values from functions like the following?
- [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [r8vec_multinormal_pdf](https://github.com/vcflib/vcflib/blob/d4073c3c89da2fff1748536032850465f6428428/src/pdflib.cpp#L3376)
- [realloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/realloc.html "Memory reallocation") ⇒ [banded_sw](https://github.com/vcflib/vcflib/blob/d4073c3c89da2fff1748536032850465f6428428/src/ssw.cpp#L578)

**Comment by pjotrp** [comment]
Sure. Feel free to submit a patch.
