### ISSUE TITLE
BCF support?

### ISSUE THREAD

**Issue by Zilong-Li** [vcflib/vcflib#304]
Since bcf is a more efficient format than vcf and it can save a lot storage, which makes it more common for keeping large dataset, it will be very useful if vcflib can support BCF and BCF.gz.

**Comment by pjotrp** [comment]
You are welcome to submit changes!

**Comment by Zilong-Li** [comment]
@pjotrp I think there is no easy way to support BCF without using ```htslib```. So I made a single file only lib to support this https://github.com/Zilong-Li/vcfpp which can be easily included. I am happy to offer help for anyone who come across this request.

**Comment by pjotrp** [comment]
Cool. Note that vcflib uses htslib already.
