### ISSUE TITLE
vcfnulldotslashdot Type-Error: can't multiply sequence by non-int of type 'float' 

### ISSUE THREAD

**Issue by J-Pieplow** [vcflib/vcflib#307]
Hi everyone,

I'm working on a CentOS based computer cluster and wanted to run vcfnulldotslashdot on some qualityfiltered and normalized vcf-files but got an Error message regarding line 18 of the vcfnulldotslashdot-script:

Line 18: `flatgls = ",".join([str(x) for x in [0]*multcoeff(alleles,2)])`
`TypeError: can't multiply sequence by non-int of type 'float'`

This is the nulldotslashdotscript:

````

1. #!/usr/bin/env python3
2. # Rewrite null genotypes to ./.
3. #
4. import sys
5. import math
6. 
7. def bincoeff(n,k): return math.factorial(n) / (math.factorial(n-k)*math.factorial(k))
8. def multcoeff(n,k): return bincoeff(n+k-1,k)
9. 
10. for line in sys.stdin:
11.     if line.startswith("#"):
12.         print(line.strip())
13.         continue
14.     fields = line.strip().split("\t")
15.     alleles = len(fields[4].split(","))+1
16.     # assume that we have GT:GL
17.     # how many genotypes?  assume diploid
18.     flatgls = ",".join([str(x) for x in [0]*multcoeff(alleles,2)])
19.     for i in range(9, len(fields)):
20.         if fields[i] == ".":
21.             fields[i] = "./.:" + flatgls
22.     print("\t".join(fields))

````

I figured the problem was likely that for some reason the multcoeff got formatted as a float number which then caused some trouble when applying to the [0]*multcoeff command. 
As the binomialcoefficient should be a whole number in theory I tried to resolve this by changing line 8 of the code a little and just converting multcoeff to an integer. 

Like this:

````

1. #!/usr/bin/env python3
2. # Rewrite null genotypes to ./.
3. #
4. import sys
5. import math
6. 
7. def bincoeff(n,k): return math.factorial(n) / (math.factorial(n-k)*math.factorial(k))
8. def multcoeff(n,k): return int(bincoeff(n+k-1,k))
9. 
10. for line in sys.stdin:
11.     if line.startswith("#"):
12.         print(line.strip())
13.         continue
14.     fields = line.strip().split("\t")
15.     alleles = len(fields[4].split(","))+1
16.     # assume that we have GT:GL
17.     # how many genotypes?  assume diploid
18.     flatgls = ",".join([str(x) for x in [0]*multcoeff(alleles,2)])
19.     for i in range(9, len(fields)):
20.         if fields[i] == ".":
21.             fields[i] = "./.:" + flatgls
22.     print("\t".join(fields))

````

It seemed to work, at least I didn't get the error anymore. 
But I'm quite new to programming and bioinformatics and am a bit insecure now. I'm wondering if I can really trust the resulting vcf-file and the change of the code didn't change anything about the function. Also I'm puzzled why nobody else seems to have had this issue before, at least I couldn't find anything on google about it. 

Would be very grateful if someone with more expertise could comment on this =)

**Comment by pjotrp** [comment]
Hi @J-Pieplow. You may have a chance of an answer if you provide the actual data and point out any issues with that! Cheers.

**Comment by WinterFor** [comment]
I have same situation, and I pulled a request just now. I don't know if it's appropriate. I did a similar change. @J-Pieplow
```
Traceback (most recent call last):
  File "../vcfnulldotslashdot", line 17, in <module>
    flatgls = ",".join([str(x) for x in [0]*multcoeff(alleles,2)])
TypeError: can't multiply sequence by non-int of type 'float'
```

**Comment by poecile-palustris** [comment]
Good evening,

I faced the same problem. Could you please clarify the correctness of the change
`def multcoeff(n,k): return int(bincoeff(n+k-1,k))`?
There are not similar changes in original [script](https://github.com/vcflib/vcflib/blob/master/scripts/vcfnulldotslashdot), so I can't be sure.
Thank you in advance!

Best regards,
Poecile

**Comment by pjotrp** [comment]
I am not sure what you are asking.

**Comment by poecile-palustris** [comment]
Hello @pjotrp, 

Thanks for the answer!
I launched
```
vcffilter -f "TYPE = snp & QUAL > 30 & AF > 0.99" bwamap_unfilteredSNP.vcf \
| vcfnulldotslashdot \
| grep -vF './.' | grep -vF '.|.' \
> bwamap_filteredSNP_ver_Q30_AF099.vcf
```
and got an error:
```
Traceback (most recent call last):
 File "/home/poecile/miniconda3/envs/vcflib/bin/vcfnulldotslashdot", line 17, in <module>
   flatgls = ",".join([str(x) for x in [0]*multcoeff(alleles,2)])
TypeError: can't multiply sequence by non-int of type 'float'
```

But now all is good and I haven't got an error with the same script and file! I have installed **vcflib 1.0.3** instead of **1.0.0_rc2**, which was default in [anaconda.org](https://anaconda.org/bioconda/vcflib).
