### ISSUE TITLE
Error: Failed to download resource "vcflib".

### ISSUE THREAD

**Issue by olferievm** [vcflib/vcflib#316]
Can't install "vcflib" using brew formula on OSX Big Sur. Failed to download resource "vcflib". Any suggestions?
Seems like the resource is not available by that adress.

brew install brewsci/bio/vcflib
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
haruhi-dl
==> Updated Formulae
Updated 2 formulae.
==> Updated Casks
Updated 1 cask.

==> Installing vcflib from brewsci/bio
==> Downloading https://archive.org/download/brewsci/bottles-bio/vcflib-1.0.1.si
#=#=-#  #
curl: (22) The requested URL returned error: 403
Error: Failed to download resource "vcflib"
Download failed: https://archive.org/download/brewsci/bottles-bio/vcflib-1.0.1.sierra.bottle.tar.gz

**Comment by pjotrp** [comment]
Ask the brew folks.
