### ISSUE TITLE
vcfdistance missing VCF header

### ISSUE THREAD

**Issue by edg1983** [vcflib/vcflib#317]
Hi,
I'm trying to use vcfdistance (vcflib v1.0.1) to annotate distance to closest var in my VCF. 

When I try
`vcfdistance closestVar_dist < input.vcf.gz` or
`vcfdistance < input.vcf.gz`

I get this error: `error: no VCF header`

However, the input file has a regular VCF header (as far as I can tell), and no of the other tools I've used complained about missing / malformed header, so I can't understand where the issue comes from. The header of my file is attached 
[header.txt](https://github.com/vcflib/vcflib/files/6538214/header.txt)

**Comment by ekg** [comment]
Try using zcat to send an uncompressed file to it, or simply applying
vcfdistance with the filename.

**Comment by edg1983** [comment]
Ok, thanks. Got it now!
I was confused because the help shows
`usage: vcfdistance [customtagname] < [vcf file]`

So I assumed it would accept compressed .gz as well, while it only works with uncompressed from stdin.
Basically, 
`vcfdistance customtag vcf_file.vcf` doesn't work, while
`cat vcf_file.vcf  | vcfdistance` or `vcfdistance < vcf_file.vcf` works fine.
