### ISSUE TITLE
vcfcombine - terminate called after throwing an instance of 'std::out_of_range' error

### ISSUE THREAD

**Issue by adcosta17** [vcflib/vcflib#32]
Hi, 

I am trying to combine two vcf files and when I run the executable vcfcombine and pass in the two file names as arguments I receive the following error message:

terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
Aborted

The version I am using was downloaded about 40 mins prior to this message being sent to you. Would like to know if there is a workaround for this, or if I am doing something wrong. 

Thanks

Al

**Comment by tseemann** [comment]
Consider https://samtools.github.io/bcftools/bcftools.html#merge
