### ISSUE TITLE
Compilation failure of intervaltree/Intervaltree.h on Unbuntu 21.10

### ISSUE THREAD

**Issue by timmassingham** [vcflib/vcflib#320]
**Only bug reports!**

The C++ version of VCFLIB is in *maintenance* mode. Use the github issue
tracker to report bugs *only*. For comments, questions and features,
please use the google group mailing list as stated on the
[README](https://github.com/vcflib/vcflib/blob/master/README.md)!

**Describe the bug**

Compilation failure on Ubuntu 21.10 due to missing header file in IntervalTree.h

```
/data/giraffe/vg/deps/vcflib/intervaltree/IntervalTree.h:249:76: note:   candidate expects 2 arguments, 0 provided
  249 |             std::pair<Scalar, Scalar> x = {std::numeric_limits<Scalar>::max(),
      |                                                                       ~~~~~^~
/data/giraffe/vg/deps/vcflib/intervaltree/IntervalTree.h:250:61: error: ‘numeric_limits’ is not a member of ‘std’
  250 |                                                        std::numeric_limits<Scalar>::min() };
      |                                                             ^~~~~~~~~~~~~~
/data/giraffe/vg/deps/vcflib/intervaltree/IntervalTree.h:250:82: error: expected primary-expression before ‘>’ token
  250 |                                                        std::numeric_limits<Scalar>::min() };
      |                                                                                  ^
/data/giraffe/vg/deps/vcflib/intervaltree/IntervalTree.h:250:88: error: no matching function for call to ‘min()’
  250 |                                                        std::numeric_limits<Scalar>::min() };
```

**Resolution**
Issue is fixed upstream, version of dependency needs to be bumped.

**Comment by pjotrp** [comment]
Thanks @timmassingham - this appears to be part of giraffe. Can you tell me the exact build steps you are using?

**Comment by timmassingham** [comment]
Hello.  Giraffe is just the name of directory I am compiling the [VG tools](https://github.com/vgteam/vg) in.

VG tools imports vcflib as a submodule, https://github.com/vgteam/vg/tree/master/deps and it build by standard process.
Both the commit of vcflib imported as a submodule 83e6414fe913433dc176b558a75a27a25cc23ea5 and current master of vcflib have ekg/intervaltree@17ddd57 as a submodule, which has the missing header file.  The relevant commit is ekg/intervaltree@aa5937755000f1cd007402d03b6f7ce4427c5d21 but the root cause appears to be changes in the header files of the standard C++ so `<limits>` is no longer implicitly imported by one of the other headers.

**Comment by pjotrp** [comment]
Thanks. Sounds to me that it is one of two things:

1. Update the code so we pull the right include file
2. find the debian/ubuntu package that includes limits.h

does this help: https://unix.stackexchange.com/questions/504139/installing-python-modules-fail-limits-h-missing

If not, it is probably more of a vg thing. I am sorry these stacked git modules are such a mess. I just built vcflib in a Guix container and it is fine.

**Comment by timmassingham** [comment]
`<limits>` is standard header file and is already installed as part of the libc package.  You don't mention which version of Guix you tried, but I'm confident will become an increasingly more frequent issue as people upgrade their OS.

For reference, the following also fails with the same error, whereas it builds fine after bumping the version of IntervalTree:
```bash
git clone --recursive https://github.com/vcflib/vcflib.git
cd vcflib
mkdir -p build && cd build
cmake ..
cmake --build .
```

I've created a pull request #322 to fix the problem.

**Comment by pjotrp** [comment]
Excellent!
