### ISSUE TITLE
Support for streaming from cloud storage?

### ISSUE THREAD

**Issue by SHuang-Broad** [vcflib/vcflib#325]
E.g S3, GCS (Google) etc.

If so, and special instructions needed for enabling that when installing/compiling, can the instructions be added to Readme?

Thanks!

Steve

**Comment by SHuang-Broad** [comment]
BTW, a template for feature request would be good, like the one for a bug report.

**Comment by pjotrp** [comment]
vcflib is a command line tool. You can use cloud tools to pipe into most tools. This is the Unix philosophy.
