### ISSUE TITLE
Brew installation of vcflib requires outdated libstdc++.6.dylib

### ISSUE THREAD

**Issue by annalisasnow** [vcflib/vcflib#327]
Good day!

I have just installed the vcflib via `brew install brewsci/bio/vcflib` everything seems to be fine. However, I can't run the command:

`vcfcombine --help`

Here's the output I get:

` dyld[14745]: Symbol not found: __ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13find_first_ofEPKcmm
  Referenced from: /usr/local/Cellar/vcflib/1.0.1/bin/vcfcombine
  Expected in: /usr/lib/libstdc++.6.dylib
zsh: abort      vcfcombine --help
`
Just in case I have tested a couple of other commands: `vcfinfo2qual`, `vcf2fasta` and so on. The result's unfortunately the same - it doesn't work and returns issue with the `/usr/lib/libstdc++.6.dylib`

As far as I understand it, that's happening due to requirement of `libstdc++.6.dylib` which should be replaced with `libc++`.

Mac OS: Mac OS Monterey, 16 GB and 2.9 GHz (i7)

Is there anything I can do with that issue?

Many thx for your hard work

**Comment by pjotrp** [comment]
This is a matter for the brew folks.
