### ISSUE TITLE
vcfallelicprimitives feature request 

### ISSUE THREAD

**Issue by mandiedriskill** [vcflib/vcflib#332]
It would be really useful if vcfallelicprimitives would report monomorphic sites too. Freebayes allows --report-monomorphic to report all sites, then if you use vcfallelicprimitives this gives call gaps at monomorphic sites.

**Comment by pjotrp** [comment]
Can you provide an example? Why not filter out monomorphic sites?

**Comment by mandiedriskill** [comment]
Hello,

I am calculating pi which requires monomorphic sites to accurately calculate this statistic.

**Comment by ekg** [comment]
Hmm. We might add this to vcfwave... But could you not simply count
alignment-covered sites in the reference that aren't called as polymorphic?
