### ISSUE TITLE
Error building from source

### ISSUE THREAD

**Issue by jdidion** [vcflib/vcflib#348]
#0 34.53 CMake Error at CMakeLists.txt:435 (pybind11_add_module):
#0 34.53   Unknown CMake command "pybind11_add_module".

**Comment by pjotrp** [comment]
you need to install pybind11 for the test framework.

**Comment by jdidion** [comment]
@pjotrp I installed pybind11 (`pip3 install pybind11`) - still getting same error

**Comment by pjotrp** [comment]
try the Debian/CentOS package

**Comment by jdidion** [comment]
Got it working with `apt install pybind11-dev`

**Comment by pjotrp** [comment]
Great. I may make it optional in the future. Though pybind11 will allow for easy Python functionality.

**Comment by nathanweeks** [comment]
FWIW, `pip3 install --user 'pybind11[global]'` (source: https://stackoverflow.com/a/70403316) also resolved the `"Unknown CMake command "pybind11_add_module"` error for me.
