### ISSUE TITLE
Installation does not work because packaged dependency headers are not installed

### ISSUE THREAD

**Issue by adamnovak** [vcflib/vcflib#358]
**Describe the bug**

When I try to use `make install` to install vcflib, the WFA headers aren't installed.

**To Reproduce**

1. Clone vcflib and go into it.
2. `mkdir build && cd build`
3. `cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_ONLY_LIB=ON -DCMAKE_INSTALL_PREFIX=`pwd`/inst .. && make -j15 && make install`
4. Look in `inst/include`. In particular, `inst/include/Variant.h` will `#include "bindings/cpp/WFAligner.hpp"`, but there is no `inst/bindings/` directory installed.

**Expected behavior**

`make install` should install all necessary headers for compiling against `vcflib`. Ideally into directories by package name ("bindings" at the root of the include directory might already be occupied by some other installed library).

**Screenshots**

N/A

**Additional context**

Toggling `BUILD_ONLY_LIB` on and off doesn't seem to help, but having it on reduces the build time for testing.

**Comment by pjotrp** [comment]
it is in https://github.com/vcflib/vcflib/blob/master/.gitmodules

**Comment by adamnovak** [comment]
Oh OK, the problem is that I'm not doing a *recursive* clone, but the build and install succeed and just don't install all the headers that are needed when the submodules are missing?

**Comment by pjotrp** [comment]
yup
