### ISSUE TITLE
Including vcflib headers now leaks a FORMAT macro, which conflicts with user constants named FORMAT regardless of scope or namespace

### ISSUE THREAD

**Issue by adamnovak** [vcflib/vcflib#359]
After including `Variant.h`, I get a macro named `FORMAT` defined as `'%'`, from `WFA2-lib`'s `utils/commons.h` which now gets transitively included.

That header also defines macros with other very common names, such as `SPACE`, `HASH`, `MIN`, `rand_init`, `SWAP`, etc. These all leak out of vcflib and end up defined in my user code.

If I update vcflib in `vg` to the current version, I would have to go through he whole `vg` codebase and make sure that none of those tokens were used as the names of any functions, variables, or constants, in any scope or namespace. That seems impractical.

Either vcflib should use a `WFA2-lib` that doesn't lay claim to so many token names (maybe by prefixing them all with the package name?), or vcflib should take steps to avoid leaking `WAF2-lib` macro definitions into code that depends only on vcflib. That could involve a bunch of #undef directives in vcflib, or it could involve not including any (or at least these) WFA2-lib headers in installed vcflib headers, and making the code that communicates with WFA2-lib include WFA2-lib headers only in its own compilation units, and not in the headers that define its interface.

**Comment by pjotrp** [comment]
It probably makes sense to have it fixed upstream

**Comment by pjotrp** [comment]
Sorry for the delay. @adamnovak as soon as this is merged upstream we can test with vcflib.

**Comment by pjotrp** [comment]
I just updated the main repo. Should work now. You'll need to check out a fresh copy of the submodules.

**Comment by pjotrp** [comment]
Merged and closed with https://github.com/smarco/WFA2-lib/pull/38
