### ISSUE TITLE
vcffilter flagging/removing heterozygous genotypes

### ISSUE THREAD

**Issue by leandrogneves** [vcflib/vcflib#36]
Hi Eric

I am having a hard time implementing a filter with vcffilter to flag/remove heterozygous sites and I was hoping you could help. Here is the situation:

The vcf file has individuals with 0/0, 1/1 and 0/1 genotypes. From this file I tried to achieve two things:
1- Convert sample assigned as heterozygous to missing. 
2- Flag sites with at least one sample assigned as heterozygous (0/1).

The details of what I tried is below. I appreciate if you could help me identify if I am doing something wrong or if there is a bug here. 

Thanks much.

Leandro
###### DETAILS

For 1 I tried the following:
vcffilter  --genotype-filter "GT = 0/1"  $VCFFILTER
This converts all 0/0 and 1/1 samples to missing. I wanted the opposite, so I tried adding --invert but it produced the exact same output. I also tried adding --genotype-filter ! "(GT = 0/1)", but there was no output being generated.
As a workaround I wrote a perl script for this.

For 2 I tried the following:
vcffilter --tag  --genotype-filter "GT = 0/1"  $VCFFILE

And returned and error
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
Aborted
I could not find a workaround for this issue yet.

VERSION: vcflib/20121207

**Comment by ekg** [comment]
vcffilter -g "! ( GT = 0/1 )" will keep only those samples that are not
hets.

The filters work by keeping things which match their expression.

Sorry for the very crude notation for the filters.  For example, the only
way to use negative numbers is now to do this:

vcffilter -f "AC > ( 0 - 1 )"

Also, everything needs to have a space between it and the next operator,
due to the way that the parser is implemented.  I'd love to make it better
but it's hard to argue with something that works.

**Comment by leandrogneves** [comment]
That is very helpful and I was able to make it work now! I knew it was something to be with parenthesis and spaces, but could not make it work for every combination I tried. The only one I did not try was to put the ! inside the quotation "! ( GT = 0/1 )".

I kindly suggestion you to change this on the documentation website (https://github.com/ekg/vcflib) under vcffilter? It explains that to obtain a logical negation you should use ! "( DP = 10 )" (note the ! outside the quotation marks. That misled me not to try the ! inside the quotation marks, but I was able to understand the need for parenthesis and spaces.

Thanks again
Leandro

**Comment by ekg** [comment]
Thank you for the note about the documentation.  I will get to this the
next time I have my hands in the code.

Glad this is working for you,
Erik
