### ISSUE TITLE
vcfwave using only one core

### ISSUE THREAD

**Issue by RenzoTale88** [vcflib/vcflib#363]
Hello,
I am currently using vcfwave to post-process a VCF file. I have compiled the tool within a docker container as follow:
```
# Install vcflib
RUN git clone --recursive https://github.com/vcflib/vcflib.git && \
  cd vcflib && \
  mkdir -p build && cd build && \
  cmake -DZIG=OFF .. && \
  cmake --build . && \
  cmake --install .
```

I then converted the image to singularity and run it in a cluster providing 8 cores, specified as follow:
```
vcfwave -k -t 8  tmp.vcf > tmp2.vcf
```

However, when monitoring the job I can see that the process is using just one core:
```
23164024                  1:    **wallclock=12:43:10, cpu=12:32:03**, mem=32581.64442 GBs, io=28.51506 GB, iow=5.740 s, ioops=18003272, vmem=1.148G, maxvmem=3.956G
```
As seen by the wallclock and cpu times matching in number.
Have I compiled the tool in the wrong way? Or am I missing on something?

Thanks in advance
Andrea

**Comment by ekg** [comment]
It only runs in parallel over multiple alleles at the same site. You can
split up the VCF into pieces and recombine the results if you need to
parallelize over sites.

**Comment by RenzoTale88** [comment]
Ok thanks!
