### ISSUE TITLE
unable to -DZIG=ON for installing vcfcreatemulti

### ISSUE THREAD

**Issue by Overcraft90** [vcflib/vcflib#369]
**Only bug reports!**

The C++ version of VCFLIB is in *maintenance* mode. Use the github issue
tracker to report bugs *only*. For comments, questions and features,
please use the google group mailing list as stated on the
[README](https://github.com/vcflib/vcflib/blob/master/README.md)!

**Describe the bug**

I'm trying to build from source — I've done so successfully before the release of `vcfcreatemulti` — including the flag -DZIG=ON for the additional functionalities of `vcfcratemulti`. Still, I'm getting an issue with `zig` despite having installed all dependencies and packages.

**To Reproduce**

1. git clone --recursive https://github.com/vcflib/vcflib.git
2. cd vcflib
3. mkdir -p build && cd build
4. `cmake -DCMAKE_BUILD_TYPE=Debug -DZIG=ON -DOPENMP=ON ..`
5. `cmake --build .`

```
[  0%] Performing build step for 'ZIG-EXT'
error: unable to find zig installation directory '/usr/local/bin/zig': FileNotFound
gmake[2]: *** [CMakeFiles/ZIG-EXT.dir/build.make:86: ZIG-EXT-prefix/src/ZIG-EXT-stamp/ZIG-EXT-build] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:302: CMakeFiles/ZIG-EXT.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```

**Expected behavior**

I would expect to generate all executable and then be able to `cmake --install .`, and if necessary move them to my /bin for easy access to them.

**Screenshots**

**Additional context**

I tried with few options to point to my `zig` directory 
_e.g._ `-DCMAKE_INSTALL_PREFIX=/path/to/zig` or `-DCMAKE_PREFIX_PATH=/home/mat/Downloads/zig` but none of them worked.

Include a set of VCF files to reproduce the issue

+ bonus points if you try to minimize the test case yourself, as issues are often localized:
  - try to use sambamba or samtools slice to first extract the reference where the error occurs
  - if that succeeds (the error is still reproducible), continue to crop the file in binary-search fashion

**Finally**

Please check the README and docs carefully. Everyone working on vcflib is doing that for free. Please respect our time (too).

**Comment by pjotrp** [comment]
How about ZIG=OFF

**Comment by Overcraft90** [comment]
Well, it actually works with ZIG=OFF. As I said I already built it from source once, as I needed `vcfwave`, the real problem is that now I would like to access the functions of `vcfcreatemulti`, which based on the description on the main page requires ZIG=ON.

Let me know, maybe I misunderstood.

**Comment by pjotrp** [comment]
Ah, in that case have zig in you build path. vcfcreatemulti requires zig.

**Comment by Overcraft90** [comment]
I tried both ways:

1. keeping the entire `zig` directory in the build
2. keeping simply the executable

I always get this error message

> [  0%] Performing build step for 'ZIG-EXT'
> error: unable to find zig installation directory '/usr/local/bin/zig': FileNotFound
> gmake[2]: *** [CMakeFiles/ZIG-EXT.dir/build.make:86: ZIG-EXT-prefix/src/ZIG-EXT-stamp/ZIG-EXT-build] Error 1
> gmake[1]: *** [CMakeFiles/Makefile2:302: CMakeFiles/ZIG-EXT.dir/all] Error 2
> gmake: *** [Makefile:146: all] Error 2

**Comment by pjotrp** [comment]
unpack zig as a directory and add that to PATH. When you type 'zig version' you should see version.

**Comment by Overcraft90** [comment]
@pjotrp I tried both ways, either unzipping and adding the executable to my `/usr/local/bin` or building from source and adding the files in the **stage3** folder for the `zip` package to my /usr/local/bin` led to the same result... I'm prompted with the error message above. 

Typing `zig` it actually returns the version for the tool, but the system seems not being able to detect it at least for this particular install...

Specifically, this is what I'm running after building from source
```
~$ zig version 
0.11.0-dev.1584+9ccd8ed0a

**Comment by pjotrp** [comment]
Weird. I'll take a look tomorrow.

**Comment by Overcraft90** [comment]
Hi @pjotrp,

I was wondering whether you had the chance to look into this issue. Thanks!

**Comment by pjotrp** [comment]
So I create a container that has no zig
```
guix shell -C -D -f guix.scm
```
in the shell there is no zig because I disabled te dependency in `guix.scm`
```
zig
sh: zig: command not found
```
Now run cmake
```
cd build
cmake ..
CMake Error at CMakeLists.txt:105 (MESSAGE):
  zig binary not found in PATH.  zig is used for vcfcreatemulti's latest
  features.  Either use cmake -DZIG=OFF option or add zig to the PATH
```
Now, from outside the container, I copy the full zig dir into the directory
```
cp -vau zig-linux-x86_64-0.11.0-dev.987+a1d82352d .
```
so it is visible in the container in the dir of that name.
Next I add the path in the container and I can run zig
```
export PATH=$PATH:$(pwd)/zig-linux-x86_64-0.11.0-dev.987+a1d82352d
zig version
0.11.0-dev.987+a1d82352d
```
Now run cmake again and it is happy
```
cd build
cmake ..
-- Found pybind11: /gnu/store/7cqy8vhipq7dy3f5j721vj6kw5cagkmq-profile/include (found version "2.8.1" )
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- WFA using include contrib/WFA2-lib
-- Configuring done
-- Generating done
-- Build files have been written to: /export/local/home/wrk/iwrk/opensource/code/pangenome/vcflib/build
```
So, what are you actually trying?

**Comment by Overcraft90** [comment]
Thanks @pjotrp,

Actually till the `cmake ..` everything works perfectly. But once I launch the `cmake --build .`, I got prompted the same exact message as before

> [  0%] Performing build step for 'ZIG-EXT'
> error: unable to find zig installation directory '/usr/local/bin/zig': FileNotFound
> gmake[2]: *** [CMakeFiles/ZIG-EXT.dir/build.make:86: ZIG-EXT-prefix/src/ZIG-EXT-stamp/ZIG-EXT-build] Error 1
> gmake[1]: *** [CMakeFiles/Makefile2:302: CMakeFiles/ZIG-EXT.dir/all] Error 2
> gmake: *** [Makefile:146: all] Error 2

Any idea on why is that? This is my `tree -h` directory structure of `vcflib`
```
[4.0K]  .
├── [4.0K]  1KG_Index
├── [4.0K]  build
├── [ 16K]  CMakeLists.txt
├── [4.0K]  contrib
├── [4.0K]  doc
├── [4.0K]  examples
├── [3.2K]  guix-clang.scm
├── [3.3K]  guix.scm
├── [1.0K]  LICENSE
├── [4.0K]  logos
├── [ 769]  Makefile
├── [4.0K]  man
├── [4.0K]  paper
├── [ 30K]  README.md
├── [6.3K]  RELEASE_NOTES.md
├── [4.0K]  samples
├── [4.0K]  scripts
├── [4.0K]  src
├── [4.0K]  test
├── [   6]  VERSION
└── [4.0K]  zig

13 directories, 8 files
```

**Comment by pjotrp** [comment]
Yes, build works fine:
```
[ 18%] Built target ZIG-EXT
```
maybe destroy the build dir and try again? Otherwise you may want to try out guix.scm as it replicates an identical build environment that I use.

**Comment by pjotrp** [comment]
I note btw that github-ci also uses Zig, but on Debian. It passes, so it is not specific to my environment:

https://github.com/vcflib/vcflib/blob/master/.github/workflows/ci_test.yml

**Comment by Overcraft90** [comment]
@pjotrp thanks I tried again but the error persist, even after deleting the `build` directory and starting with a new building process... I'm not sure what it triggers it though, sometimes it stops a 2%, sometimes at 17%, most often at 0%.

Anyway, I might give it a try with the `guix.scm` as you recommended.

**Comment by pjotrp** [comment]
I think it is a cmake thing. Also try the verbosity option of cmake
and maybe do a grep on /usr/local/bin in the build dir. These build
systems are complicated.

If you need help with Guix - totally happy to!
