### ISSUE TITLE
Build Broken for the Variant.cpp

### ISSUE THREAD

**Issue by MIngPAPA** [vcflib/vcflib#387]
###ENV###
GCC:10.3
CMAKE: 3.22.5
VCFLIB:1.0.9
OS:CentOS 7

###CMAKE COMMD###
cmake ..   -DCMAKE_INSTALL_PREFIX=MYVCFLIBDIR\
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INCLUDE_PATH=MYtabixpp/include \
                -DCMAKE_LIBRARY_PATH=MYtabixpp/lib
cmake . --build

###ERROR MESSAGE###
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp: In function ‘std::ostream& vcflib::operator<<(std::ostream&, vcflib::Variant&)’:
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp:1113:30: error: expected unqualified-id before ‘[’ token
             for (const auto& [name1, value]: var.info)
                              ^
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp:1113:30: error: expected ‘;’ before ‘[’ token
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp:1113:31: error: ‘name1’ was not declared in this scope
             for (const auto& [name1, value]: var.info)
                               ^
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp:1113:38: error: ‘value’ was not declared in this scope
             for (const auto& [name1, value]: var.info)
                                      ^
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp: In lambda function:
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp:1113:44: error: expected ‘{’ before ‘:’ token
             for (const auto& [name1, value]: var.info)
                                            ^
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp: In function ‘std::ostream& vcflib::operator<<(std::ostream&, vcflib::Variant&)’:
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp:1113:44: error: expected ‘;’ before ‘:’ token
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp:1113:44: error: expected primary-expression before ‘:’ token
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp:1113:44: error: expected ‘)’ before ‘:’ token
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp:1113:44: error: expected primary-expression before ‘:’ token
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp:1113:44: error: expected ‘;’ before ‘:’ token
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp:1115:30: error: expected unqualified-id before ‘[’ token
             for (const auto& [name2, value]: var.infoFlags)
                              ^
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp:1115:30: error: expected ‘;’ before ‘[’ token
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp:1115:31: error: ‘name2’ was not declared in this scope
             for (const auto& [name2, value]: var.infoFlags)
                               ^
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp:1115:38: error: ‘value’ was not declared in this scope
             for (const auto& [name2, value]: var.infoFlags)
                                      ^
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp: In lambda function:
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp:1115:44: error: expected ‘{’ before ‘:’ token
             for (const auto& [name2, value]: var.infoFlags)
                                            ^
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp: In function ‘std::ostream& vcflib::operator<<(std::ostream&, vcflib::Variant&)’:
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp:1115:44: error: expected ‘;’ before ‘:’ token
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp:1115:44: error: expected primary-expression before ‘:’ token
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp:1115:44: error: expected ‘)’ before ‘:’ token
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp:1115:44: error: expected primary-expression before ‘:’ token
/share/softwarepackage/vcflib-1.0.9/src/Variant.cpp:1115:44: error: expected ‘;’ before ‘:’ token
gmake[2]: *** [CMakeFiles/vcflib.dir/src/Variant.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/vcflib.dir/all] Error 2
gmake: *** [all] Error 2

**Comment by zwh82** [comment]
Hi, I have a similar situation when installing vcflib for vg. My system: GCC 6.3.0, centos 7.
I find that the error of compile not passing occurs in a few lines of code in the Variant.cpp file. Its program syntax uses the Structured Bindings introduced by C++17. GCC 6.3.0 don't support C++17, so I update GCC to GCC 7.5.0. The default C++standard supported by GCC 7.5 and your GCC 10.3 is C++14. I add `alias g++="g++ -std=c++17"` in .bashrc file and then `source ~/.bashrc`. Now it can work.

code in the Variant.cpp file
```
            for (const auto& [name1, value]: var.info)
                if (!lookup_keys[name1]) missing_keys.push_back(name1);
            for (const auto& [name2, value]: var.infoFlags)
                if (lookup_keys[name2] == false);
```
