### ISSUE TITLE
vcflib 1.0.9 conda build "symbol lookup error"

### ISSUE THREAD

**Issue by kyleomics** [vcflib/vcflib#389]
**Describe the bug**

vcfstreamsort is not functional in the 1.0.9 conda build as it seems to have some error with compilation linking.

**To Reproduce**

```
conda create -n vcflib -c bioconda -y -q vcflib=1.0.9
/home/ubuntu/miniconda3/envs/vcflib/bin/vcfstreamsort
```

gives error:
```
/home/ubuntu/miniconda3/envs/vcflib/bin/vcfstreamsort: symbol lookup error: /home/ubuntu/miniconda3/envs/vcflib/bin/../lib/libvcflib.so.1: undefined symbol: wavefront_align
```

**Additional context**

This manifests as an issue for freebayes parallel which uses vcflib. Error looks like this when running freebayes-parallel:

```
  vcfuniq: symbol lookup error: /venv/bin/../lib/libvcflib.so.1: undefined symbol: wavefront_align
  vcfstreamsort: symbol lookup error: /venv/bin/../lib/libvcflib.so.1: undefined symbol: wavefront_align
  Traceback (most recent call last):
    File "/venv/bin/vcffirstheader", line 10, in <module>
      print(line.strip())
  BrokenPipeError: [Errno 32] Broken pipe
```

For any who encounter this (like I did) while running freebayes you "fix" by pinning vcflib to an older release:
```
conda create -n freebayes_test -c bioconda -y -q vcflib=1.0.3 freebayes=1.3.6
```

**Comment by ghuls** [comment]
It happens for every binary that needs `libvcflib.so`.

**Comment by lczech** [comment]
Same here... :-(

**Comment by lczech** [comment]
Update: When installing via conda, apparently, `vcflib=1.0.3` on its own does not work anymore, I now also need to specify `freebayes` or `tabixpp` as well, as otherwise, I run into this:

```
vcfcat: error while loading shared libraries: libtabixpp.so.0: cannot open shared object file: No such file or directory
```

If I am reading the [conda files list](https://anaconda.org/bioconda/vcflib/files) correctly, the package recently received a force push using the same version label 1.0.3, but somehow with broken dependencies for the above now... Can anyone confirm?

**Comment by nhartwic** [comment]
I got the same result. I'm currently running again by downgrading tabixpp...

tabixpp=1.1.0

...I think this at least resolve dthe issue with that library. I've no idea if I'm going to run into yet another compilation related issue afterwards.

**Comment by juliawiggeshoff** [comment]
Same here... Pinning vcflib to 1.03 and tabixpp to 1.1.0 will do the trick, but I'd like to see a fix to be able to use vcflib 1.0.9

`mamba create --name vcflib_new -c bioconda -c conda-forge vcflib=1.0.3 tabixpp=1.1.0`

**Comment by johanneskoester** [comment]
@mencian, you made some quite extensive changes in the way we build vcflib in Bioconda here: https://github.com/bioconda/bioconda-recipes/commit/032977aed9bcf6941284034e443b234e36af62e5, after which the error seems to occur. Would you be so kind to have a look what might be wrong?

cc @bgruening

**Comment by ghuls** [comment]
zig 0.11.0 is out while the recipe uses zig 0.10.1. There is a chance that that will solve it.

**Comment by juliawiggeshoff** [comment]
I came back to this issue hoping that it would have been solved, as I would have liked to be able to create a conda environment with vcflib, mainly to be used with Snakemake, but to no avail. Therefore, I settled to create a singularity recipe that solves the issues with vcfwave and the many library dependencies. If it might be of interest to anyone, it's [here](https://github.com/juliawiggeshoff/singularity-recipes/blob/main/vcflib-1.09.def)

**Comment by maxineliu** [comment]
> I came back to this issue hoping that it would have been solved, as I would have liked to be able to create a conda environment with vcflib, mainly to be used with Snakemake, but to no avail. Therefore, I settled to create a singularity recipe that solves the issues with vcfwave and the many library dependencies. If it might be of interest to anyone, it's [here](https://github.com/juliawiggeshoff/singularity-recipes/blob/main/vcflib-1.09.def)

Hi, I tried your recipe on a cluster, but unfortunately, it failed. The fatal error message is: "No LD_PRELOAD in fakeroot environment." I'm wondering if you would be willing to share the SIF image directly? If so, that would be very convenient for me.

**Comment by juliawiggeshoff** [comment]
> Hi, I tried your recipe on a cluster, but unfortunately, it failed. The fatal error message is: "No LD_PRELOAD in fakeroot environment." I'm wondering if you would be willing to share the SIF image directly? If so, that would be very convenient for me.

Oh, how interesting @maxineliu. I also built it on a cluster and it worked fine. But sure, [here](https://github.com/juliawiggeshoff/singularity-recipes/blob/main/vcflib-1.09.simg) is the link to download the SIF. 

Hope that helps!

**Comment by maxineliu** [comment]
> > Hi, I tried your recipe on a cluster, but unfortunately, it failed. The fatal error message is: "No LD_PRELOAD in fakeroot environment." I'm wondering if you would be willing to share the SIF image directly? If so, that would be very convenient for me.
> 
> Oh, how interesting @maxineliu. I also built it on a cluster and it worked fine. But sure, [here](https://github.com/juliawiggeshoff/singularity-recipes/blob/main/vcflib-1.09.simg) is the link to download the SIF.
> 
> Hope that helps!

Yeah, it works! Thanks so much!

**Comment by pjotrp** [comment]
In @juliawiggeshoff  fix the libwfa2 shared library gets copied in a logical place. I'll take a look at cmake again for that. I note that only a few tools depend on this library (vcfwave in particular), so other files should not depend on it. If I do `ldd vcfstreamsort` it is not in there. So the symbol lookup should not happen.

**Comment by pjotrp** [comment]
Latest trunk should do this correctly.

**Comment by lczech** [comment]
@pjotrp, there is no update on bioconda, which is still at 1.0.9, so the fix in trunk does not really help here, due to the whole issue being about installation via conda. Could you maybe push the fixed version 1.0.10 to bioconda as well? Right now, I still need to work with 1.0.3, for the reasons explained above. Thanks!

**Comment by jbloom** [comment]
I just wanted to echo the above comment that it would be great if this fix can be added to the version on `conda`.

**Comment by mencian** [comment]
I've added a patch to link `wfa2-lib` to the `vcflib` binaries [here](https://github.com/bioconda/bioconda-recipes/pull/50750); let me know if v`1.0.10` along with the new patch fixes the symbol lookup error.
