### ISSUE TITLE
vcfwave: command not found

### ISSUE THREAD

**Issue by BlackSlipper** [vcflib/vcflib#390]
hello i tried downloading using bioconda and Ubuntu with the commands given on the [homepage](https://github.com/vcflib/vcflib). 

Both of the installations were successful, but did not contain vcfwave command. 

is there a optimal way to download and use vcfwave? 

thank you in advance.

**Comment by tzaquin** [comment]
Any update on this?

**Comment by alicia-hgim** [comment]
got the same error

**Comment by plnspineda** [comment]
Hi all, I had the same issue and this is my work around:

1. Download the source file.
2. Decompress and go to the folder and do this:

```
mkdir -p build && cd build
cmake  -DCMAKE_BUILD_TYPE=Debug -DZIG=OFF -DOPENMP=ON  .
cmake --build .
```
sourced from these issues:
https://github.com/vcflib/vcflib/issues/369

**Comment by pjotrp** [comment]
Please report with distros.
