### ISSUE TITLE
Error when installing from source

### ISSUE THREAD

**Issue by Avinash-git-py** [vcflib/vcflib#391]
Hi,

I am facing the error while installing using source commands.

The command:
cmake -DCMAKE_BUILD_TYPE=Debug -DZIG=OFF -DOPENMP=OFF ..

The error that I'm facing:
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Checking for module 'htslib'
--   Found htslib, version 1.10.2-3ubuntu0.1
-- Checking for module 'tabixpp'
--   No package 'tabixpp' found
-- 

-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- WFA using include contrib/WFA2-lib
CMake Error at CMakeLists.txt:459 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".

-- Configuring incomplete, errors occurred!
See also "/media/ngslinux/External Disk/GATK_pipeline/vcflib/build/CMakeFiles/CMakeOutput.log".

cmake --build .
make: *** No targets specified and no makefile found.  Stop.

![vcflib](https://github.com/vcflib/vcflib/assets/125788800/a3ab3d23-e418-48c6-867e-df755121f96a)

Also kindly explain the complete installation using conda.

**Comment by zwh82** [comment]
You lack pybind11 library, you can install it using `pip install "pybind11[global]"` and it will add files to `/usr/local/include/pybind11` and `/usr/local/share/cmake/pybind11`. https://pybind11.readthedocs.io/en/latest/installing.html#global-install-with-brew
