### ISSUE TITLE
VCFwave error with WFA 

### ISSUE THREAD

**Issue by maggs-x** [vcflib/vcflib#396]
Hi,

I'm running vcfwave on a pangenome vcf generated with cactus-mini graph pipeline. vcfbub has already been run on it. 

I'm getting the following error:

vcfwave 1.0.7 processing...
[WFA::Penalties] Match score must be negative or zero (M=19)

Here is the line of code I ran:
vcfwave -I 1000 Amex-pg.vcf.gz > Amex-pg_wave.vcf

It appears to be a problem with the BiWFA alignment? The first few lines of the vcf are all SNPs and are processed successfully by vcfwave. The error occurs at the first line with a MNP (2bp).

Please let me know if you have any solutions to the issue. I appreciate how vcfwave handles complex and nested variants, and would like to get it working. Thanks!

Maggs

**Comment by aariani** [comment]
I am encountering the same problem. The documentation does not explain much about vcfwave and the error is really cryptic
