### ISSUE TITLE
libwfa2.so missing after cmake install

### ISSUE THREAD

**Issue by marc-sturm** [vcflib/vcflib#397]
Hi,

I just built and installed vcflib 1.0.9 on Ubuntu 20.04 using these commands:
```
git clone https://github.com/vcflib/vcflib.git vcflib-1.0.9
cd vcflib-1.0.9
git checkout v1.0.9 && git submodule update --recursive --init
mkdir build
cd build
cmake -DZIG=OFF ..
cmake --build .
cmake -DCMAKE_INSTALL_MANDIR=$prefix --install . --prefix $prefix 
```

When I start a command, e.g. vcfallelicprimitives, from the `build` folder everything works.
However when I start the same command from the `prefix` folder, libWFA is missing.

Is there a bug in the installation, or am I missing a parameter for cmake?

Best,
 Marc

**Comment by pjotrp** [comment]
You are right.

**Comment by marc-sturm** [comment]
Will this be fixed?

**Comment by pjotrp** [comment]
Yes. The current trunk uses either the distro version or the bundled wfa2lib and should install correctly.
