### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [vcflib/vcflib#40]
I would like to point out that identifiers like "[`__VARIANT_H`](https://github.com/ekg/vcflib/blob/14118579cc3f99ae5fb1b6a10b05255310e2127d/src/Variant.h#L1)" and "[`__JOIN_H`](https://github.com/ekg/vcflib/blob/271d2eeb548abffe97eeec12be22c40cf2560edf/src/join.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL32-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by pjotrp** [comment]
Thanks @elfring, I agree that needs to be fixed. A patch would be appreciated.
