### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [vcflib/vcflib#41]
I expect that exception handling is usually supported by a C++ program. I wonder why your functions "[main](https://github.com/ekg/vcflib/blob/271d2eeb548abffe97eeec12be22c40cf2560edf/src/vcfremap.cpp#L34)" do not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main) so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706)?

Would you like to adjust the implementations if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108) like they are described by Danny Kalev?

**Comment by elfring** [comment]
Under which circumstances can mentioned implementation details clarified better?

**Comment by pjotrp** [comment]
An uncaught exception will just bail out with an error code. In general that does the job. If you have an improvement feel free to submit a patch.

**Comment by elfring** [comment]
[The application of C++ exceptions](https://en.cppreference.com/w/cpp/language/try_catch "Description for exception handling") can eventually be improved further.

How should a production-quality main() function look like?

**Comment by pjotrp** [comment]
I closed the issue. If anyone feels like writing code we can reopen.
