### ISSUE TITLE
Coding standards for contributions -- is it ok to use c++11 syntax?

### ISSUE THREAD

**Issue by winni2k** [vcflib/vcflib#43]
Hi there,
I'm looking at modifying some vcflib code to later contribute back to the project.  Looking at vcfbreakmulti, it looks like it was written in pre-c++11.  Nothing wrong with that, but is it ok for me to use c++11? Is there a project policy about such things?

**Comment by ekg** [comment]
I am only concerned about portability.  Do you know in which linux
distributions c++11 became standard?  OSX would be another one to pay
attention to.

**Comment by winni2k** [comment]
For OSX it's relatively straight forward:  OSX switched to clang recently, and the earliest version of clang that supports all of c++11 is version 3.3.  clang 3.3 was made available with XCode 5.0.0, which is only available on current versions of Mountain Lion and Mavericks (10.8 and 10.9).  However, most aspects of c++11 were available in clang 2.9, which was distributed with XCode 3.2.6, which runs on OSX versions as far back as Snow Leopard (10.6).

Linux distros may instead be using gcc, which will need to be at 4.7 or greater for relatively complete c++11 support.
