### ISSUE TITLE
Call rate

### ISSUE THREAD

**Issue by maximebastien** [vcflib/vcflib#44]
Hello,

I generated a vcf file from potato (tetraploid) genotyping by sequencing data with Freebayes. Although my file has over 21,000 markers most of them are of limited use because there contain a lot of missing data. I would like to filter this file to keep only markers with a call rate of at least 0.75. 

I have made many attempts to do this with vcflib, but to no avail. The best result I get is with these commands:

vcffilter -g "geno = .75" mpileup20140318_1153.vcf > Test.vcf
vcffilter -g "min_call_rate = .75" mpileup20140318_1153.vcf > Test.vcf

They both generate a file where all genotype calls are replaced with missing data.

Is there a way to use vcflib to filter my file based on call rate?

Thank you.

Maxime

**Comment by ekg** [comment]
Hi Maxime,

If this is for freebayes, just use the NS field to determine how many
genotypes are called.

If you had 100 samples and wanted only sites where there were >75% called,
you would use this command to filter sites:

```
vcffilter -f "NS > 75" file.vcf >out.vcf
```

I'm not sure what the field in mpileup means, but this is how you'd do it
for freebayes.  The filename you presented makes it seem you've used
samtools to generate this file, not freebayes.

Erik

**Comment by maximebastien** [comment]
The filename mpileup20140318_1153.vcf is from me. I tried your command, it works fine.

Thank you!

Maxime

**Comment by ekg** [comment]
Awesome, glad to help clear this up.

**Comment by sjclare** [comment]
I'm working with a tetraploid called with FreeBayes, where the depth is important for dosage calls. Therefore I want to recode data points that have low depth and if this makes the site overall have as 25% missing I want to completely remove the site? How could I do this because the NS value will remain the same? Thanks
