### ISSUE TITLE
vcffilter

### ISSUE THREAD

**Issue by BOUDHRIOUA** [vcflib/vcflib#45]
Hi Erik
I am having a problem filtering my vcf file  to create an output with few missing genotypes across all individuals.
I tried the -g and the -geno options but there is no output file 
for exemple
vcffilter -gno .9 Optimisation_1_ApekI_filtred.vcf  out_filtered
d
error: no VCF header

**Comment by sanjeevksh** [comment]
Hi BOUDHRIOUA,
Did you manage to solve this issue?

Regards,
Sanjeeb
