### ISSUE TITLE
vcffilter to support filtering by FORMAT fields

### ISSUE THREAD

**Issue by isthisthat** [vcflib/vcflib#46]
Hello,
It would be nice to be able to filter for FORMAT fields the same way one can filter for INFO fields.
Thank you for a great toolset!

**Comment by isthisthat** [comment]
Hi again,
I see now that this functionality is fulfilled by `-g`. However, I still can't get it to do what I want.
My use-case is that I'm trying to keep records who's Variant Frequency (VF) genotype field is below 0.02. I have just one sample in my vcf. I tried

```
vcffilter -g "VF < 0.02" -s my.vcf > my_VF2pc.vcf
```

but that didn't filter anything. It just removed all genotype entries from all rows (I've checked the VFs of my variants and about 10% should have VF < 0.02). Anything I'm doing wrong?

**Comment by ekg** [comment]
Try removing the -s flag, then use

```
vcffixup - | vcffilter -f 'AC > 0'
```

**Comment by isthisthat** [comment]
wow! How on earth did that work? Can you please explain? Thank you very much.

**Comment by ekg** [comment]
vcffilter -g removes samples that do not match the filter.

vcffixup recalculates the AC, NS, and AF fields using the genotypes.

vcffilter -f 'AC > 0' removes sites with no alternate alleles.  You could
also filter with NS > 0 if you wanted to keep 0/0 calls.

**Comment by isthisthat** [comment]
Thank you.
