### ISSUE TITLE
There are edge cases where vcfallelicprimitives doesn't always split apart indels and SNPs

### ISSUE THREAD

**Issue by ernfrid** [vcflib/vcflib#49]
I've encountered a case of an adjacent indel and SNP that were unable to be picked apart by vcfallelicprimitives. The variant is an T insertion into a T homopolymer run and an A->T SNP at the end of the run. A more complete representation would be: TTTTTTTTA -> TTTTTTTTT 

The indel as reported is this:
`5  132267859   .   A   TT`

Running through vcfallelicprimitives doesn't change the representation at all, even though this is a SNP and an indel. Adding padding allows this to be split out as I would have expected.

`5  132267858   .   TA  TTT` is then reported as 

```
5   132267858   .   T   TT
5   132267859   .   A   T
```

**Comment by travc** [comment]
Bump...
I'm seeing cases like this too.  It would be very nice if vcfallelicprimitives would handle them, since otherwise I just have to exclude such sites (with two variant types) from my downstream analysis.

**Comment by ekg** [comment]
Interesting issue. The fact that adding padding changes the output is a bit
surprising.
