### ISSUE TITLE
vcffilter related error

### ISSUE THREAD

**Issue by sanjeevksh** [vcflib/vcflib#50]
I am applying vcffilter on a Freebayes vcf file but having the following error message:
error: no VCF header

my command line is:
qsub -V -cwd -j yes -b y -l hostname="n13*" vcffilter -g "DP > 15" TSB_GBS_geno384_bwt2_vsensN1_L_0_-0.37_08MM.bam.SNPs.vcf | vcffixup - | > TSB_8MM_FB_geno384_fltdDP15_fixed.vcf

Previously I have tested exactly same commands on the similar file but it worked fine though at that time I just tested it on a smaller subset.  

At first I applied vcffilter on vcfindex parsed file and thought the issue could be related to that but then I also attempted this filter on the original vcf file but got the same error.

Is this a known issue? Any help on this would be highly appreciated.

Regards,
Sanjeev

**Comment by nekrut** [comment]
Sanjeev, since this is a vcflib-specific question, please direct it to vcflib mailing lists. Thanks. anton
