### ISSUE TITLE
vcfkeepsamples for a large number of samples

### ISSUE THREAD

**Issue by sanjeevksh** [vcflib/vcflib#51]
Hi Erik,

I want to use 'vcfkeepsamples' for a large number (290) of samples but this is not working for me. I have tried inputting sample names in the command line as well as using a shell script. Is there any solution to use this tool for large number of samples? or by feeding sample names by a file??

Regards,
Sanjeev

**Comment by brentp** [comment]
`vcfkeepsamples` works for a large number of samples, but it is _very_ slow. If I want to pull out 3 samples, out of ~1K total, it is the slowest part of my pipeline, (including VEP which is notoriously slow).

**Comment by zeeev** [comment]
Carson and I have done some benchmarking.  The slowdown comes from splitting the genotypes using the functions in split.h.  There is a faster split function in boost, but only provides pointers to the fields not the actual strings.

**Comment by brentp** [comment]
I have been just using the functionality in htslib to extract a list of samples with bcf_hdr_set_samples.
