### ISSUE TITLE
error building

### ISSUE THREAD

**Issue by thomasvangurp** [vcflib/vcflib#52]
Hi Erik,

I'm trying to build vcflib on mac osx maverick with:
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.2.0
Thread model: posix

I get the following error when trying to build:
In file included from src/Variant.h:6:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/map:1192:17: error: no matching function for call to object of type 'const vcf::ChromNameCompare'
            if (__tree_.value_comp().key_comp()(__k, __nd->__value_.__cc.first))
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/map:1361:36: note: in instantiation of member function 'std::__1::mapstd::__1::basic_string<char,
      std::__1::map<long, std::__1::map<std::__1::vector<std::__1::basic_string<char>, std::__1::allocatorstd::__1::basic_string<char > >, std::__1::map<vcf::VariantCallFile *, vcf::Variant *,
      std::__1::less<vcf::VariantCallFile *>, std::__1::allocator<std::__1::pair<vcf::VariantCallFile *const, vcf::Variant *> > >, std::__1::lessstd::__1::vector<std::__1::basic_string<char,
      std::__1::allocatorstd::__1::basic_string<char > > >, std::__1::allocator<std::__1::pair<const std::__1::vector<std::__1::basic_string<char>, std::__1::allocatorstd::__1::basic_string<char > >,
      std::__1::map<vcf::VariantCallFile *, vcf::Variant *, std::__1::less<vcf::VariantCallFile *>, std::__1::allocator<std::__1::pair<vcf::VariantCallFile *const, vcf::Variant *> > > > > >,
      std::__1::less<long>, std::__1::allocator<std::__1::pair<const long, std::__1::map<std::__1::vector<std::__1::basic_string<char>, std::__1::allocatorstd::__1::basic_string<char > >,
      std::__1::map<vcf::VariantCallFile *, vcf::Variant *, std::__1::less<vcf::VariantCallFile *>, std::__1::allocator<std::__1::pair<vcf::VariantCallFile *const, vcf::Variant *> > >,
      std::__1::lessstd::__1::vector<std::__1::basic_string<char, std::__1::allocatorstd::__1::basic_string<char > > >, std::__1::allocator<std::__1::pair<const
      std::__1::vector<std::__1::basic_string<char>, std::__1::allocatorstd::__1::basic_string<char > >, std::__1::map<vcf::VariantCallFile *, vcf::Variant *, std::__1::less<vcf::VariantCallFile *>,
      std::__1::allocator<std::__1::pair<vcf::VariantCallFile *const, vcf::Variant *> > > > > > > > >, vcf::ChromNameCompare, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>,
      std::__1::map<long, std::__1::map<std::__1::vector<std::__1::basic_string<char>, std::__1::allocatorstd::__1::basic_string<char > >, std::__1::map<vcf::VariantCallFile *, vcf::Variant *,
      std::__1::less<vcf::VariantCallFile *>, std::__1::allocator<std::__1::pair<vcf::VariantCallFile *const, vcf::Variant *> > >, std::__1::lessstd::__1::vector<std::__1::basic_string<char,
      std::__1::allocatorstd::__1::basic_string<char > > >, std::__1::allocator<std::__1::pair<const std::__1::vector<std::__1::basic_string<char>, std::__1::allocatorstd::__1::basic_string<char > >,
      std::__1::map<vcf::VariantCallFile *, vcf::Variant *, std::__1::less<vcf::VariantCallFile *>, std::__1::allocator<std::__1::pair<vcf::VariantCallFile *const, vcf::Variant *> > > > > >,
      std::__1::less<long>, std::__1::allocator<std::__1::pair<const long, std::__1::map<std::__1::vector<std::__1::basic_string<char>, std::__1::allocatorstd::__1::basic_string<char > >,
      std::__1::map<vcf::VariantCallFile *, vcf::Variant *, std::__1::less<vcf::VariantCallFile *>, std::__1::allocator<std::__1::pair<vcf::VariantCallFile *const, vcf::Variant *> > >,
      std::__1::lessstd::__1::vector<std::__1::basic_string<char, std::__1::allocatorstd::__1::basic_string<char > > >, std::__1::allocator<std::__1::pair<const
      std::__1::vector<std::__1::basic_string<char>, std::__1::allocatorstd::__1::basic_string<char > >, std::__1::map<vcf::VariantCallFile *, vcf::Variant *, std::__1::less<vcf::VariantCallFile *>,
      std::__1::allocator<std::__1::pair<vcf::VariantCallFile *const, vcf::Variant *> > > > > > > > > > > >::__find_equal_key' requested here
    __node_base_pointer& __child = __find_equal_key(__parent, __k);
                                   ^
src/vcfcombine.cpp:109:42: note: in instantiation of member function 'std::__1::mapstd::__1::basic_string<char, std::__1::map<long, std::__1::map<std::__1::vector<std::__1::basic_string<char>,
      std::__1::allocatorstd::__1::basic_string<char > >, std::__1::map<vcf::VariantCallFile *, vcf::Variant *, std::__1::less<vcf::VariantCallFile *>,
      std::__1::allocator<std::__1::pair<vcf::VariantCallFile *const, vcf::Variant *> > >, std::__1::lessstd::__1::vector<std::__1::basic_string<char, std::__1::allocatorstd::__1::basic_string<char > >
      >, std::__1::allocator<std::__1::pair<const std::__1::vector<std::__1::basic_string<char>, std::__1::allocatorstd::__1::basic_string<char > >, std::__1::map<vcf::VariantCallFile *, vcf::Variant *,
      std::__1::less<vcf::VariantCallFile *>, std::__1::allocator<std::__1::pair<vcf::VariantCallFile *const, vcf::Variant *> > > > > >, std::__1::less<long>, std::__1::allocator<std::__1::pair<const long,
      std::__1::map<std::__1::vector<std::__1::basic_string<char>, std::__1::allocatorstd::__1::basic_string<char > >, std::__1::map<vcf::VariantCallFile *, vcf::Variant *,
      std::__1::less<vcf::VariantCallFile *>, std::__1::allocator<std::__1::pair<vcf::VariantCallFile *const, vcf::Variant *> > >, std::__1::lessstd::__1::vector<std::__1::basic_string<char,
      std::__1::allocatorstd::__1::basic_string<char > > >, std::__1::allocator<std::__1::pair<const std::__1::vector<std::__1::basic_string<char>, std::__1::allocatorstd::__1::basic_string<char > >,
      std::__1::map<vcf::VariantCallFile *, vcf::Variant *, std::__1::less<vcf::VariantCallFile *>, std::__1::allocator<std::__1::pair<vcf::VariantCallFile *const, vcf::Variant *> > > > > > > > >,
      vcf::ChromNameCompare, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, std::__1::map<long, std::__1::map<std::__1::vector<std::__1::basic_string<char>,
      std::__1::allocatorstd::__1::basic_string<char > >, std::__1::map<vcf::VariantCallFile *, vcf::Variant *, std::__1::less<vcf::VariantCallFile *>,
      std::__1::allocator<std::__1::pair<vcf::VariantCallFile *const, vcf::Variant *> > >, std::__1::lessstd::__1::vector<std::__1::basic_string<char, std::__1::allocatorstd::__1::basic_string<char > >
      >, std::__1::allocator<std::__1::pair<const std::__1::vector<std::__1::basic_string<char>, std::__1::allocatorstd::__1::basic_string<char > >, std::__1::map<vcf::VariantCallFile *, vcf::Variant *,
      std::__1::less<vcf::VariantCallFile *>, std::__1::allocator<std::__1::pair<vcf::VariantCallFile *const, vcf::Variant *> > > > > >, std::__1::less<long>, std::__1::allocator<std::__1::pair<const long,
      std::__1::map<std::__1::vector<std::__1::basic_string<char>, std::__1::allocatorstd::__1::basic_string<char > >, std::__1::map<vcf::VariantCallFile *, vcf::Variant *,
      std::__1::less<vcf::VariantCallFile *>, std::__1::allocator<std::__1::pair<vcf::VariantCallFile *const, vcf::Variant *> > >, std::__1::lessstd::__1::vector<std::__1::basic_string<char,
      std::__1::allocatorstd::__1::basic_string<char > > >, std::__1::allocator<std::__1::pair<const std::__1::vector<std::__1::basic_string<char>, std::__1::allocatorstd::__1::basic_string<char > >,
      std::__1::map<vcf::VariantCallFile *, vcf::Variant *, std::__1::less<vcf::VariantCallFile *>, std::__1::allocator<std::__1::pair<vcf::VariantCallFile *const, vcf::Variant *> > > > > > > > > > >
      >::operator[]' requested here
                variantsByChromPosAltFile[var->sequenceName][var->position][var->alt][vcf] = var;
                                         ^
src/Variant.h:487:10: note: candidate function not viable: 'this' argument has type 'const vcf::ChromNameCompare', but method is not marked const
    bool operator()(const string& a, const string& b) {
         ^
1 error generated.
make: **\* [bin/vcfcombine] Error 1

**Comment by nekrut** [comment]
See https://github.com/ekg/freebayes/issues/83

this fixes this issue

**Comment by zeeev** [comment]
@thomasvangurp Master is building on OS X now.
