### ISSUE TITLE
Sometimes no VT tag is output by vcfsamplediff

### ISSUE THREAD

**Issue by jts** [vcflib/vcflib#53]
When strict mode is on in vcfsamplediff and the germline sample has a non-zero alternative allele count, no VT tag will be written to the VCF record. This is due to the following condition not having an else statement:

https://github.com/ekg/vcflib/blob/master/src/vcfsamplediff.cpp#L173

In this case the variant should probably be tagged as "germline".

**Comment by murphycj2** [comment]
I have noticed the same issue.
