### ISSUE TITLE
vcfbreakmulti keeps all AD values instead of using only two

### ISSUE THREAD

**Issue by igordot** [vcflib/vcflib#55]
I tried using vcfbreakmulti (If multiple alleles are specified in a single record, break the record into
multiple lines, preserving allele-specific INFO fields). It works mostly as specified, but there seems to be a problem with the AD values. It keeps the original values. Although there is only one alt allele listed after running the script, there are still more than two values in the AD field.

**Comment by xguse** [comment]
No one interested in commenting on this?

**Comment by seru71** [comment]
Voting +1 for implementing this feature / fixing the bug

**Comment by igordot** [comment]
I am not sure if this was actually resolved.

**Comment by pjotrp** [comment]
Can someone provide a recent example?

**Comment by alexander-e-f-smith** [comment]
I also have this problem. Was there ever a resolution of this? EAch record outputted by Multi=allelic split retaining all AD info for all multi-allelic calls rather than just the one relating to that split out record.

**Comment by pjotrp** [comment]
If you give a simple example input and output we have a chance at fixing it. Better even, submit a fix with a test.
