### ISSUE TITLE
VcfAllelicPrimitives segfault with -m option

### ISSUE THREAD

**Issue by nekrut** [vcflib/vcflib#56]
VcfAllelicPrimitives consistently segfaults with -m option when used on sample.vcf file. This occurs on the build of the latest release (8a5602bf07ff7b59f85135c4ed9d87abf6abaad4). All other options appear to work as expected. The command line generating segfault is:

```
cat sample.vcf | vcfallelicprimitives --use-mnps -t "Split primitives" -L "200"
```

**Comment by tseemann** [comment]
This no longer segfaults in 1.x
