### ISSUE TITLE
vcfbreakmulti modifies GT calls incorrectly

### ISSUE THREAD

**Issue by henrikstranneheim** [vcflib/vcflib#64]
When i process  a vcf file using vcfbreakmulti, it modifies some GT calls oddly.

Look at the second sample GT.

Original record:
5   113698544   rs40179 G   C   104439.72   PASS    AC=1;AF=0.500;AN=2;BaseQRankSum=-7.310e-01;DB;DP=0;FS=0.523;GQ_MEAN=1678.26;GQ_STDDEV=1388.36;InbreedingCoeff=-0.2664;MQ=40.70;MQ0=0;MQRankSum=-2.960e-01;NCC=1;POSITIVE_TRAIN_SITE;QD=20.02;ReadPosRankSum=-2.170e-01;VQSLOD=2.53;culprit=FS   GT:AD:DP:GQ:PL  0/1:3,7:.:58:162,0,58   ./.:0,0:0

After vcfbreakmulti:
5   113698544   rs40179 G   C   104440  PASS    AC=1;AF=0.500;AN=2;BaseQRankSum=-7.310e-01;DP=0;FS=0.523;GQ_MEAN=1678.26;GQ_STDDEV=1388.36;InbreedingCoeff=-0.2664;MQ=40.70;MQ0=0;MQRankSum=-2.960e-01;NCC=1;QD=20.02;ReadPosRankSum=-2.170e-01;VQSLOD=2.53;culprit=FS;DB;POSITIVE_TRAIN_SITE   GT:AD:DP:GQ:PL  0/1:3,7:.:58:162,0,58   1/2:0,2,4:.:35:129,65,49,36,0,75

Suddenly the second sample's GT goes from nocall to having multiple alternative alleles. 

And vcfbrakemulti should not even touch this record since there are no multiple alternative allels in the original file or am I missing something?

**Comment by slaurie** [comment]
Did this issue ever get resolved?

**Comment by slaurie** [comment]
Answering my own question - still not resolved.

**Comment by hzpc-joostk** [comment]
Hi @slaurie I think you may have switched your lines, as the line "after vcfbreakmulti" contains more information for the seconds sample. :)

**Comment by hzpc-joostk** [comment]
See #201 also questioning the output of `vcfbreakmulti`
