### ISSUE TITLE
vcfcombine drops fileformat & filedate lines, leaving a .vcf file that bcftools (for instance) can't parse

### ISSUE THREAD

**Issue by ljdursi** [vcflib/vcflib#65]
Reproducer:

```
$ cd samples
$ head -2 sample.vcf
##fileformat=VCFv4.0
##fileDate=20090805

$ bcftools view -h sample.vcf  | head -2
##fileformat=VCFv4.0
##FILTER=<ID=PASS,Description="All filters passed">

$ ../bin/vcfcombine sample.vcf sample.vcf > combined.vcf
$ head -2 combined.vcf
##source=myImputationProgramV3.1
##reference=1000GenomesPilot-NCBI36

$ bcftools view -h combined.vcf
Failed to open combined.vcf: unknown file type
```

The issue seems to be in how the header lines and header lists maps are constructed and used: so when vcfcombine reads through the header of the first file and adds meta information lines, it lowercases all the keys:

```
void VCFHeader::addMetaInformationLine(const string& meta_line)
 {

        //.... 
        // all map keys are lower case so when we check we need to be lower case too!
        std::transform(meta_line_prefix.begin(), meta_line_prefix.end(), meta_line_prefix.begin(), ::tolower);
}
```

But some keys, including fileFormat, in header_line_names_ordered are mixed case:

```
    VCFHeader::VCFHeader()
    {
        // ...
        // the order is used when outputting as a string
        this->header_line_names_ordered.push_back("##fileFormat");
        this->header_line_names_ordered.push_back("##fileDate");
        //...
```

Thus when it comes time to get the header string:

```
    string VCFHeader::getHeaderString()
    {
        // getHeaderString generates the string each time it is called
        string header_string;

        // start by adding the header_lines
        for (vector<string>::const_iterator header_lines_iter = this->header_line_names_ordered.begin(); header_lines_iter != this->header_line_names_ordered.end(); ++header_lines_iter)
        {
            if (this->header_lines[(*header_lines_iter)] != "")
            {
                header_string += this->header_lines[(*header_lines_iter)] + "\n";
            }
        }
        //...
```

nothing is ever found for fileFormat, since only fileformat exists in the map.

I've confirmed that this can be fixed by either using all-lowercase keys in header_line_names_ordered, or using a custom comparitor in the header_lines and header_lists map to make insert and find operations on the map case-insensitive.   I can submit a PR either way, but they're pretty different solutions.

**Comment by ljdursi** [comment]
I've submitted 2 PRs that address the issue two different ways.

**Comment by ekg** [comment]
Thanks Jonathan. Which solution would you recommend?

**Comment by ljdursi** [comment]
I'd suggest going  with the comparitor patch, especially if you have time to run a few vcfcombine tests to verify first, otherwise the case-change patch will certainly close the issue.

The case-change solution is a trivial patch which completely addresses the current issue, but leaves the underlying "gotcha" in the code.  But VCF header fields don't change that often, so maybe that's fine, and the resulting change in output (to, eg, ##fileformat) is ok.

The case-insensitive comparitor fixes the gotcha, keeps the output the same, and I've tested it on my data, but it's always better if someone else runs tests too - my vcf files are all pretty homogeneous.  It looks like only vcfcombine currently uses VCFHeader.

**Comment by knbknb** [comment]
Today I've compiled vcfcombine from freebayes repo commit  c003c1e (2015-06-05). The bug is still there. No output lines 

```
##fileformat=VCFv4.1                                                            
###fileDate=20150724
```

in the output file.
