### ISSUE TITLE
add "prependcol" script for ROC plotting routine

### ISSUE THREAD

**Issue by mdshw5** [vcflib/vcflib#69]
Reading [this post](http://clavius.bc.edu/~erik/CSHL-advanced-sequencing/freebayes-tutorial.html) leads me to believe that the `plot_roc.r` script relies on a simple script that prepends "freebayes" or "truth" to each thresholded set generated by `vcfroc`. Could you add this script to your repository, or (even better) modify `vcfroc` to just produce this format by default?

**Comment by ekg** [comment]
That's a good idea, and the right solution. I think it would be a very easy
patch, and certainly _way_ easier than coding up your own solution from
scratch.

**Comment by mdshw5** [comment]
In the interest of reinventing the wheel, here is my wheel: https://gist.githubusercontent.com/mdshw5/8301a232b3eef043a780/raw/dd32200bf19f9fcc4dbbb75985a79b17d7aa4d64/prependcol

**Comment by ekg** [comment]
Oops I thought I had added this to the repo already.

It was the behavior that plot_roc assumes (that the truth set is included
in the file) which should be patched into vcfroc.
