### ISSUE TITLE
Downloading and installing problem

### ISSUE THREAD

**Issue by Swanthana** [vcflib/vcflib#70]
Hello
I am trying to download vcflib onto server. But i couldn't download it. I followed the instructions given, all I am able to get is index.html and 2 png files. Please help me to download it. Thanks in advance.

**Comment by ekg** [comment]
Did you see any error messages?

**Comment by Swanthana** [comment]
I know I am getting back to it very late, but i still face problems in installing the vcflib. Here is the error I am getting while I try to make the file. please help me to install it. Thanks. 

cd tabixpp && make
make[1]: Entering directory `/u06/opt/vcflib-master/tabixpp'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory`/u06/opt/vcflib-master/tabixpp'
make: **\* [tabixpp/tabix.o] Error 2

**Comment by ekg** [comment]
You need to use git clone --recursive to download the library.

**Comment by Swanthana** [comment]
Thanks for the immediate response.

Here is the command i used to download the library : wget git clone --recursive https://github.com/ekg/vcflib.git
It downloaded 5 files 

Below are the files before downloading the library:
bin         fsom          Makefile     samples        tabixpp
fastahack   intervaltree  multichoose  smithwaterman  tests
filevercmp  LICENSE       README.md    src

And these are files or directories I have now after downloading the library:
bin         fsom        intervaltree  multichoose  smithwaterman  tests
fastahack   git         LICENSE       README.md    src
filevercmp  github.com  Makefile      samples      tabixpp

But still I don't see the vcflib director and I got the same error when I tried make. 
Thank you.

**Comment by ekg** [comment]
Don't use wget! Just do:

```
git clone --recursive https://github.com/ekg/vcflib.git
```

Git is its own program which manages the download.

**Comment by Swanthana** [comment]
So that worked and created a vcflib directory in which I tried make. Than I am getting this error,
make[1]: Leaving directory `/u06/opt/vcflib-master/vcflib/smithwaterman'
cd fastahack && make
make[1]: Entering directory`/u06/opt/vcflib-master/vcflib/fastahack'
g++ -O3 -D_FILE_OFFSET_BITS=64 -c Fasta.cpp
g++ -O3 -D_FILE_OFFSET_BITS=64 -c split.cpp
g++ -O3 -D_FILE_OFFSET_BITS=64 -c disorder.c
g++ -O3 -D_FILE_OFFSET_BITS=64 Fasta.o FastaHack.cpp split.o disorder.o -o fastahack
make[1]: Leaving directory `/u06/opt/vcflib-master/vcflib/fastahack'
cc    -c -o src/ssw.o src/ssw.c
g++ -O3 -D_FILE_OFFSET_BITS=64   -c -o src/ssw_cpp.o src/ssw_cpp.cpp
cd fsom && g++ -O3 -D_FILE_OFFSET_BITS=64 -c fsom.c -lm
fsom.h:77: error: non-local function ‘void som_network_destroy(som_network_t_)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.h:78: error: non-local function ‘void som_set_inputs(som_network_t_, double_)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.h:79: error: non-local function ‘void som_train(som_network_t_, double**, size_t, size_t)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.h:80: error: non-local function ‘void som_serialize(som_network_t_, const char_)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.h:81: error: non-local function ‘void som_init_weights(som_network_t*, double**, size_t)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.h:82: error: non-local function ‘double som_get_best_neuron_coordinates(som_network_t_, size_t_, size_t_)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.h:83: error: non-local function ‘som_network_t_ som_deserialize(const char_)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.h:84: error: non-local function ‘som_network_t_ som_network_new(size_t, size_t, size_t)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.c:249: error: non-local function ‘som_network_t\* som_network_new(size_t, size_t, size_t)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.c:397: error: non-local function ‘void som_network_destroy(som_network_t_)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.c:417: error: non-local function ‘void som_set_inputs(som_network_t_, double_)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.c:436: error: non-local function ‘double som_get_best_neuron_coordinates(som_network_t_, size_t_, size_t_)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.c:560: error: non-local function ‘double som_learning_rate_fast(som_network_t_, size_t, double, size_t)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.c: In function ‘void som_train_iteration(som_network_t_, double_, size_t)’:
fsom.c:597: warning: converting to ‘size_t’ from ‘double’
fsom.c: At global scope:
fsom.c:616: error: non-local function ‘void som_init_weights(som_network_t_, double**, size_t)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.c:859: error: non-local function ‘void som_train(som_network_t*, double**, size_t, size_t)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.c:887: error: non-local function ‘void som_serialize(som_network_t_, const char_)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.c:927: error: non-local function ‘som_network_t\* som_deserialize(const char_)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
make: *_\* [fsom/fsom.o] Error 1

Any more suggestions please. Thank you.

**Comment by ekg** [comment]
OK, I am assuming you're on mac?

Given that no one is really using som, I should probably disable it so that
mac users can build vcflib.

**Comment by Swanthana** [comment]
Nope, I am trying to install it on server from my windows machine.

**Comment by ekg** [comment]
That's weird... huh. What server operating system?

**Comment by ekg** [comment]
I removed the library that so-often fails to build.

To get the new version and rebuild, do this:

```
make clean
git pull origin master
make
```

**Comment by Swanthana** [comment]
I think its linux server OS, but not sure of it. And as our's is not git repository, I got this error when i tried git pull origin master
fatal: Not a git repository (or any parent up to mount point /u06)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

So what I did is, downloaded vcflib again and used installed it and gave it make command, which installed all libraries except 
ar: creating libvcflib.a
a - src/Variant.o
a - src/split.o
a - smithwaterman/sw.o
a - fastahack/Fasta.o
a - src/ssw.o
a - src/ssw_cpp.o
ar: fsom/fsom.o: No such file or directory
make: **\* [libvcflib.a] Error 1
So, this says I got installed the vcflib, right or do I need to install anything more?

**Comment by ekg** [comment]
Should be fixed shortly. I made a typo.

**Comment by ekg** [comment]
Try again now.

**Comment by Swanthana** [comment]
Finally I got it installed. Thank you so much Eric for all the help.

**Comment by ekg** [comment]
Not a problem! Thanks for working with me on this.

**Comment by marina-yurieva** [comment]
I'm on Mac and trying to install it but it gives me this:

git clone --recursive https://github.com/ekg/vcflib.git
Cloning into 'vcflib'...
remote: Counting objects: 1647, done.
remote: Total 1647 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (1647/1647), 1.09 MiB | 43.00 KiB/s, done.
Resolving deltas: 100% (947/947), done.
Checking connectivity... done.
Submodule 'fastahack' (https://github.com/ekg/fastahack.git) registered for path 'fastahack'
Submodule 'filevercmp' (https://github.com/ekg/filevercmp.git) registered for path 'filevercmp'
Submodule 'fsom' (https://github.com/ekg/fsom.git) registered for path 'fsom'
Submodule 'intervaltree' (https://github.com/ekg/intervaltree.git) registered for path 'intervaltree'
Submodule 'multichoose' (https://github.com/ekg/multichoose.git) registered for path 'multichoose'
Submodule 'smithwaterman' (https://github.com/ekg/smithwaterman.git) registered for path 'smithwaterman'
Submodule 'tabixpp' (https://github.com/ekg/tabixpp.git) registered for path 'tabixpp'
Cloning into 'fastahack'...
remote: Counting objects: 192, done.
remote: Total 192 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (192/192), 45.42 KiB | 0 bytes/s, done.
Resolving deltas: 100% (110/110), done.
Checking connectivity... done.
fatal: Error reading .git

It makes the vcflib folder but when I try to use make it gives the same error as above:

cd tabixpp && make
make[1]: **\* No targets specified and no makefile found.  Stop.
make: **\* [tabixpp/tabix.o] Error 2

**Comment by Erikacj** [comment]
This is what I am getting:

make
cd tabixpp && /Applications/Xcode.app/Contents/Developer/usr/bin/make
ar -cru libtabix.a 
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
    ar -m [-TLsv] archive file ...
    ar -m [-abiTLsv] position archive file ...
    ar -p [-TLsv] archive [file ...]
    ar -q [-cTLsv] archive file ...
    ar -r [-cuTLsv] archive file ...
    ar -r [-abciuTLsv] position archive file ...
    ar -t [-TLsv] archive [file ...]
    ar -x [-ouTLsv] archive [file ...]
make[2]: **\* [libtabix.a] Error 1
make[1]: **\* [all-recur] Error 1
make: **\* [tabixpp/tabix.o] Error 2

I have a Makefile, README, etc....any suggestions? I'm on a mac

**Comment by Erikacj** [comment]
*on a mac

**Comment by admerait** [comment]
I have the same issue on Ubuntu 12.04

htslib/libhts.a(cram_io.o): In function `lzma_mem_deflate':
/usr/local/vcflib/tabixpp/htslib/cram/cram_io.c:669: undefined reference to `lzma_stream_buffer_bound'
/usr/local/vcflib/tabixpp/htslib/cram/cram_io.c:675: undefined reference to `lzma_easy_buffer_encode'
htslib/libhts.a(cram_io.o): In function `cram_compress_by_method':
/usr/local/vcflib/tabixpp/htslib/cram/cram_io.c:1030: undefined reference to `BZ2_bzBuffToBuffCompress'
htslib/libhts.a(cram_io.o): In function `cram_uncompress_block':
/usr/local/vcflib/tabixpp/htslib/cram/cram_io.c:954: undefined reference to `BZ2_bzBuffToBuffDecompress'
htslib/libhts.a(cram_io.o): In function `lzma_mem_inflate':
/usr/local/vcflib/tabixpp/htslib/cram/cram_io.c:691: undefined reference to `lzma_easy_decoder_memusage'
/usr/local/vcflib/tabixpp/htslib/cram/cram_io.c:691: undefined reference to `lzma_stream_decoder'
/usr/local/vcflib/tabixpp/htslib/cram/cram_io.c:706: undefined reference to `lzma_code'
/usr/local/vcflib/tabixpp/htslib/cram/cram_io.c:719: undefined reference to `lzma_code'
/usr/local/vcflib/tabixpp/htslib/cram/cram_io.c:728: undefined reference to `lzma_end'
collect2: error: ld returned 1 exit status
make[2]: *** [tabix++] Error 1
make[2]: Leaving directory `/usr/local/vcflib/tabixpp'
make[1]: *** [all-recur] Error 1
make[1]: Leaving directory `/usr/local/vcflib/tabixpp'
make: *** [tabixpp/tabix.o] Error 2

**Comment by zeeev** [comment]
You're missing the lazma header.  If you install the "xy" package you should be good to go.  

https://tukaani.org/xz/

**Comment by hongdavid94** [comment]
I see that tabixpp is no longer directly under vcflib directory but now under vcflib/contrib/tabixpp.

Are we suppossed to go into tabixapp and use the "make" command?
