### ISSUE TITLE
vcfcleancomplex segfault

### ISSUE THREAD

**Issue by travc** [vcflib/vcflib#71]
vcfcleancomplex (with no options) is segfaulting on a freebayes generated vcf.
Here is a test vcf reduced down to a single failing variant line:
http://popi.ucdavis.edu/~travc/tmp/vcfcleancomplex_fail.vcf
(Cloned fresh about 24 hours ago... version numbers should be in the vcf header.)

I don't really know what vcfcleancomplex is supposed to do, which is why I was trying to run it to find out. 

UPDATE: vcfstats segfaults on the same file.  Which is more annoying to me since vcfstats seem potentially useful to me.
vcfallelicprimitives runs fine though, so it isn't something wrong with my build of everything in vcflib.

**Comment by ekg** [comment]
It's supposed to do what vt normalize does. I would use that instead.
https://github.com/atks/vt

**Comment by travc** [comment]
Thanks for the pointer...  I do recall the existence of vt, but haven't looked at it carefully.
Yet another toolset to figure out isn't all that appealing though.  And I'm not sure it will be all that applicable since I'm not dealing with human data.
Eventually we are really going to have to start converging/merging.

I don't think I'll end up using vcfcleancomplex of vcfstats, but you can keep this issue open until you get around to resolving it by fixing the bug or deprecating/removing the programs.

**Comment by ekg** [comment]
Well vt isn't human-specific, at least the normalization routines aren't.
They are pretty general. I have found that using vcfallelicprimitives and
then vt normalize produces a very stable, minimal representation of VCF
entries.

**Comment by slaurie** [comment]
Just to flag-up that this issue is still valid.
