### ISSUE TITLE
vcffilter tag only (-F)

### ISSUE THREAD

**Issue by travc** [vcflib/vcflib#73]
vcffilter --tag-fail isn't working for me... probably my fault, but the usage is at least unclear.

If I do a command like:
`vcffilter -f 'AC > 10' -F TEST`
It just removes removes the failing lines as if `-F` were not given.

It would also be nice to know what INFO fields vcffilter updates (if any).  There other filtering programs, but I'm assuming vcflib/vcftools will tend to handle freebayes output more completely/properly than something like bcftools would.

**Comment by tseemann** [comment]
I wonder if only one of `-f` or `-F`  can be used at once?

`bcftools` is much more mature now:
https://samtools.github.io/bcftools/bcftools.html
