### ISSUE TITLE
VCFfilter gives no header error

### ISSUE THREAD

**Issue by Swanthana** [vcflib/vcflib#74]
Hello Eric,
I am trying to use vcffilter on a vcf file that i got from bcftools. Though the vcf file have header in it, the vcffilter reports an error: no VCF header

Here is my command for the vcffilter
opt/vcflib-master/vcflib/bin/vcffilter --info-filter "DP > 2 & QUAL > 20" --tag-pass BM.vcf.recode.vcf > BM_filtered.vcf

Thank you.

**Comment by ekg** [comment]
Would you please email me this file for testing?

**Comment by Swanthana** [comment]
Could you please send me your email address. I will share my vcf file with you. 

And is there any option in vcflib to sort the vcf file. Thanks.

**Comment by zeeev** [comment]
@Swanthana was this issue resolved?

**Comment by Martulie** [comment]
@ekg Hello Eric,
I have the same issue, despite my VCF has a header. Can you please help me?
Martina
