### ISSUE TITLE
Would it be possible to create a tag/release?

### ISSUE THREAD

**Issue by holtgrewe** [vcflib/vcflib#76]
This would make it easier for users to install vcflib alongside freebayes and add dependencies from freebayes to vcflib.

Thanks

**Comment by martenson** [comment]
+1
I believe the Galaxy community would also welcome versioned releases.

**Comment by visze** [comment]
+2

**Comment by martenj** [comment]
+1

**Comment by tseemann** [comment]
+1

This would make it simpler to create a Brew package to go with the Freebayes one we've done.

It can't be a proper dependency if only HEAD exists in github. Here's the formula I've got so far:
https://github.com/Homebrew/homebrew-science/pull/2092

**Comment by tseemann** [comment]
I've been informed that it is possible to package after all:
https://github.com/Homebrew/homebrew/issues/17387

**Comment by ekg** [comment]
So should we start from version 1.0?

**Comment by sjackman** [comment]
As you wish. 1.0 is suitable if you think the API is stable.

**Comment by tseemann** [comment]
@ekg before you do release can you accept this pull request https://github.com/ekg/vcflib/pull/84 ?

**Comment by serverhorror** [comment]
+1

**Comment by serverhorror** [comment]
Would be nice to simply have something where a complete source tarball can be downloaded I'm working on an integration with [EasyBuild](http://hpcugent.github.io/easybuild/) and a building block is to actually have something downloadable that has a kind of version number

**Comment by holtgrewe** [comment]
In any case, I would recommend following semantic versioning http://semver.org/

**Comment by tseemann** [comment]
I think @ekg has implictly voted **-6** ;-)

**Comment by ekg** [comment]
Actually, I think I need to add a volunteer as a committer. Anyone game?

**Comment by sjackman** [comment]
_chirp chirp_
_chirp chirp_
:crickets:

**Comment by sjackman** [comment]
@serverhorror Have you seen [Homebrew](http://brew.sh), [Linuxbrew](http://brew.sh/linuxbrew) and [Homebrew-science](http://brew.sh/homebrew-science)?

**Comment by sjackman** [comment]
@serverhorror [vcflib](https://github.com/Homebrew/homebrew-science/blob/master/vcflib.rb) is already packaged for Homebrew-science.

**Comment by ekg** [comment]
Looks like I'll continue on as sole maintainer :)

Version 1.0.0 coming up. Any objections?

**Comment by sjackman** [comment]
Tag it! :rocket:

**Comment by ekg** [comment]
I've tagged one, but I listed it as a release candidate: https://github.com/ekg/vcflib/releases/tag/v1.0.0-rc0

Honesty, I don't care for release candidates. Might as well just bump the minor version no? Thoughts? I can tag 1.0.0 stable and we can all get on with our genomics.

**Comment by sjackman** [comment]
I'm not a fun of release candidates either. I'd just call it 1.0.0 and get on with it. Bugs can be fixed in the patch-level version, like you say. See [Semantic Versioning](http://semver.org/)

**Comment by ekg** [comment]
Yup, I'll "release" version 1.0.0 and we can get on with it.

**Comment by tseemann** [comment]
Thank you!

**Comment by sjackman** [comment]
@ekg Please bump this thread when you do, and I'll update the [Homebrew-science formula](https://github.com/Homebrew/homebrew-science/blob/master/vcflib.rb).

**Comment by tseemann** [comment]
@sjackman vclib now has a release, although it has the -rc0 suffix: https://github.com/ekg/vcflib/releases/tag/v1.0.0-rc0
Don't forget vcflib uses sub-modules so the `.tar.gz` won't have all the dependencies?

**Comment by sjackman** [comment]
Cool. Feel free to update the Homebrew formula. You can continue to use the git url, just add a `:tag` parameter, and it will fetch the submodules.

**Comment by dominikborkowski** [comment]
Is there a possibility of having a release tarball that includes all of the git submodules? Similarly to @serverhorror, we're trying to package Freebayes via EasyBuild. Without those components included, we won't be able to accomplish it.

Thanks!

**Comment by tseemann** [comment]
Done - https://github.com/vcflib/vcflib/releases/tag/v1.0.1

**Comment by serverhorror** [comment]
Cool thanks! Let's maybe not take another 5 years for the next release :)

**Comment by tseemann** [comment]
@serverhorror i asked @ekg to be added to this github so I could make some releases as I was in the same boat as you :)

**Comment by tseemann** [comment]
@dominikborkowski both `brew` and `conda` support `git clone --recursive` with `--tag v1.0.1` parameter.  Easybuild needs to support that too probably, as github makes it painfully manual to create a tarball.

**Comment by sjackman** [comment]
If you use autotools (autoconf and automake) run `make distcheck` and then upload the tarball to the releases page. It is manual, but it's a big help.

**Comment by tseemann** [comment]
`vcflib` ain't using no fancy autotools mate! 😉

**Comment by ekg** [comment]
We should switch to cmake though. Not a trivial thing but at least finite.

**Comment by sjackman** [comment]
I personally prefer `autotool` to `cmake,` based on totally subjective and anecdotal experience. I find myself cursing a lot when I use `cmake`. Curse words per minute could be a new quantitative metric of software quality.

**Comment by serverhorror** [comment]
That’s long established:
https://images.app.goo.gl/4pNB4caf1PjhjTWs7

**Comment by sjackman** [comment]
WTF per minute! 🤣
Absolutely true. I want Siri to measure this metric while I'm reviewing a PR. I'm not even joking.

**Comment by tseemann** [comment]
@ekg two ppl tried: https://github.com/vcflib/vcflib/pull/9 https://github.com/vcflib/vcflib/pull/146
