### ISSUE TITLE
How to cite vcflib?

### ISSUE THREAD

**Issue by riyuebao** [vcflib/vcflib#78]
Hi Erik,

I hope all is well! I was wondering how to cite vcflib in papers? We were preparing a manuscript and used vcflib for the data analysis. Thank you! =)

Best,
Riyue
## 

Riyue Bao, Ph.D.
Bioinformatician
Center for Research Informatics | Biological Sciences Division
The University of Chicago

**Comment by zeeev** [comment]
@riyuebao If you're curious the manuscript draft is in vcflib/paper.  Hopefully we'll submit soon.
