### ISSUE TITLE
vcfleftalign is broken

### ISSUE THREAD

**Issue by sveint** [vcflib/vcflib#79]
When trying to use the tool vcfleftalign from current master (b1dfd7a73140f9b12cb8fd2a554d70188ff05cca), vcfleftalign does not work.

I have a 75MB file with many insertions/deletions, and **none** are changed. The REF and ALT doesn't change at all, although it spends over a minute processing, so something is happening. GATK's LeftAlignAndTrimVariants works fine, and left aligns many variants.

An example case is given below. Running it with GATK left aligns it, but vcfleftalign doesn't.

```
##fileformat=VCFv4.1
#CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  NA123
10  104263980   CI100961    C   CC  .   .   .   GT: 0/1
```

**Comment by tseemann** [comment]
@sveint Can you provide the output from GATK for comparison?

**Comment by ekg** [comment]
I should probably remove this function as it is not maintained! Sorry for
the trouble. Please use `vt normalize` to achieve left normalization.

**Comment by tseemann** [comment]
@ekg should we remove `vcfleftalign` ?

**Comment by pjotrp** [comment]
It actually builds fine.
