### ISSUE TITLE
vcffilter -f "DP >= 10" segfaults

### ISSUE THREAD

**Issue by tseemann** [vcflib/vcflib#80]
`vcffilter -f "DP >= 10" file.vcf` segfaults.

I understand that >= operator is not supported (only >) but segfault is not desirable.

**Comment by zeeev** [comment]
@tseemann fixed.

**Comment by tseemann** [comment]
Thanks @zeeev!  

 I've been on 1.0.0-rc1 and just built from HEAD today and noticed lots of other segfaults no longer occur (`vcfstats` often segfaulted on freebayes outputs, but works now).

**Comment by zeeev** [comment]
@tseemann Thank you for being active.  I'm working hard to harden the library and tools.
