### ISSUE TITLE
Compilation issue: smithwaterman/sw.o: No such file or directory

### ISSUE THREAD

**Issue by isthisthat** [vcflib/vcflib#82]
Hello,
Upon `make all`, I get the following output:

```
cd tabixpp && make
make[1]: Entering directory `/illumina/thirdparty/vcflib/vcflib-150224/tabixpp'
make[2]: Entering directory `/illumina/thirdparty/vcflib/vcflib-150224/tabixpp'
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE  bgzf.c -o bgzf.o
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE  kstring.c -o kstring.o
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE  knetfile.c -o knetfile.o
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE  index.c -o index.o
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE  bedidx.c -o bedidx.o
ar -cru libtabix.a bgzf.o kstring.o knetfile.o index.o bedidx.o
ranlib libtabix.a
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE  main.c -o main.o
gcc -g -Wall -O2 -fPIC  -o tabix main.o -lm  -L. -ltabix -lz
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE  bgzip.c -o bgzip.o
gcc -g -Wall -O2 -fPIC  -o bgzip bgzip.o bgzf.o knetfile.o -lz
g++ -g -Wall -O2 -fPIC  -c tabix.cpp
g++ -g -Wall -O2 -fPIC  -o tabix++ main.cpp tabix.o bgzf.o -lm  -L. -ltabix -lz
make[2]: Leaving directory `/illumina/thirdparty/vcflib/vcflib-150224/tabixpp'
make[1]: Leaving directory `/illumina/thirdparty/vcflib/vcflib-150224/tabixpp'
g++ -c -o src/Variant.o src/Variant.cpp -I. -L. -Ltabixpp/ -lvcflib -ltabix -lz -lm -O3 -D_FILE_OFFSET_BITS=64
g++ -c -o src/split.o src/split.cpp -I. -L. -Ltabixpp/ -lvcflib -ltabix -lz -lm -O3 -D_FILE_OFFSET_BITS=64
cd smithwaterman && make
make[1]: Entering directory `/illumina/thirdparty/vcflib/vcflib-150224/smithwaterman'
g++    -c -o smithwaterman.o smithwaterman.cpp
g++    -c -o BandedSmithWaterman.o BandedSmithWaterman.cpp
g++    -c -o SmithWatermanGotoh.o SmithWatermanGotoh.cpp
g++    -c -o Repeats.o Repeats.cpp
g++    -c -o LeftAlign.o LeftAlign.cpp
g++    -c -o IndelAllele.o IndelAllele.cpp
cc -Wall -O3   -c -o disorder.o disorder.c
  * linking smithwaterman
make[1]: Leaving directory `/illumina/thirdparty/vcflib/vcflib-150224/smithwaterman'
cd fastahack && make
make[1]: Entering directory `/illumina/thirdparty/vcflib/vcflib-150224/fastahack'
g++ -O3 -D_FILE_OFFSET_BITS=64 -c Fasta.cpp
g++ -O3 -D_FILE_OFFSET_BITS=64 -c split.cpp
g++ -O3 -D_FILE_OFFSET_BITS=64 -c disorder.c
g++ -O3 -D_FILE_OFFSET_BITS=64 Fasta.o FastaHack.cpp split.o disorder.o -o fastahack
make[1]: Leaving directory `/illumina/thirdparty/vcflib/vcflib-150224/fastahack'
ar rs libvcflib.a src/Variant.o src/split.o smithwaterman/sw.o fastahack/Fasta.o src/ssw.o src/ssw_cpp.o filevercmp/filevercmp.o tabixpp/tabix.o tabixpp/bgzf.o tabixpp/index.o tabixpp/knetfile.o tabixpp/kstring.o
ar: creating libvcflib.a
ar: smithwaterman/sw.o: No such file or directory
make: *** [libvcflib.a] Error 1
```

I looked into the makefile of `smithwaterman` and there is no `sw.o` target. Possibly a bug? Thank you for your help.

**Comment by isthisthat** [comment]
If I rename `sw.o` to `smithwaterman.o` and do another `make`, I get:

```
ar rs libvcflib.a src/Variant.o src/split.o smithwaterman/smithwaterman.o fastahack/Fasta.o src/ssw.o src/ssw_cpp.o filevercmp/filevercmp.o tabixpp/tabix.o tabixpp/bgzf.o tabixpp/index.o tabixpp/knetfile.o tabixpp/kstring.o
ar: creating libvcflib.a
g++ src/vcfecho.cpp -o bin/vcfecho -I. -L. -Ltabixpp/ -lvcflib -ltabix -lz -lm -O3 -D_FILE_OFFSET_BITS=64
./libvcflib.a(Variant.o): In function `vcf::Variant::parsedAlternates(bool, bool, bool, float, float, float, float, float, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
Variant.cpp:(.text+0x7c14): undefined reference to `CSmithWatermanGotoh::CSmithWatermanGotoh(float, float, float, float)'
Variant.cpp:(.text+0x7c46): undefined reference to `CSmithWatermanGotoh::EnableRepeatGapExtensionPenalty(float, float)'
Variant.cpp:(.text+0x7c65): undefined reference to `CSmithWatermanGotoh::Align(unsigned int&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
Variant.cpp:(.text+0x7c6d): undefined reference to `CSmithWatermanGotoh::~CSmithWatermanGotoh()'
Variant.cpp:(.text+0x7e21): undefined reference to `CSmithWatermanGotoh::EnableEntropyGapPenalty(float)'
Variant.cpp:(.text+0x8cb2): undefined reference to `CSmithWatermanGotoh::~CSmithWatermanGotoh()'
collect2: ld returned 1 exit status
make: *** [bin/vcfecho] Error 1
```

So it doesn't seem to be the right library?!
Thank you.

**Comment by ekg** [comment]
You did clone with --recursive?

**Comment by isthisthat** [comment]
I think so. Otherwise my `smithwaterman` directory would be empty no?

**Comment by ekg** [comment]
And you've tried a completely fresh rebuild (fresh clone --recursive, then
make)?

**Comment by isthisthat** [comment]
A fresh clone and rebuild seems to have fixed the issue. Thank you for your help!

**Comment by jzook** [comment]
Hi Erik,

I'm still getting this error on my Mac, whether I clone using the web browser or on the command line with git clone --recursive https://github.com/ekg/vcflib.git

Here's the make output:
PN105860:bioinfo jzook$ cd vcflib2
PN105860:vcflib2 jzook$ make
cd tabixpp && /Applications/Xcode.app/Contents/Developer/usr/bin/make
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE  bgzf.c -o bgzf.o
bgzf.c:44:1: warning: unused function 'kh_clear_cache' [-Wunused-function]
KHASH_MAP_INIT_INT64(cache, cache_t)
^
./khash.h:468:2: note: expanded from macro 'KHASH_MAP_INIT_INT64'
        KHASH_INIT(name, uint64_t, khval_t, 1, kh_int64_hash_func, kh_in...
        ^
./khash.h:140:21: note: expanded from macro 'KHASH_INIT'
        static inline void kh_clear_##name(kh_##name##_t *h...
                           ^
<scratch space>:31:1: note: expanded from here
kh_clear_cache
^
1 warning generated.
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE  kstring.c -o kstring.o
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE  knetfile.c -o knetfile.o
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE  index.c -o index.o
index.c:34:1: warning: unused function 'kh_clear_i' [-Wunused-function]
KHASH_MAP_INIT_INT(i, ti_binlist_t)
^
./khash.h:453:2: note: expanded from macro 'KHASH_MAP_INIT_INT'
        KHASH_INIT(name, uint32_t, khval_t, 1, kh_int_hash_func, kh_int_...
        ^
./khash.h:140:21: note: expanded from macro 'KHASH_INIT'
        static inline void kh_clear_##name(kh_##name##_t *h...
                           ^
<scratch space>:55:1: note: expanded from here
kh_clear_i
^
index.c:34:1: warning: unused function 'kh_del_i' [-Wunused-function]
./khash.h:453:2: note: expanded from macro 'KHASH_MAP_INIT_INT'
        KHASH_INIT(name, uint32_t, khval_t, 1, kh_int_hash_func, kh_int_...
        ^
./khash.h:259:21: note: expanded from macro 'KHASH_INIT'
        static inline void kh_del_##name(kh_##name##_t *h, khint_t x...
                           ^
<scratch space>:69:1: note: expanded from here
kh_del_i
^
index.c:35:1: warning: unused function 'kh_clear_s' [-Wunused-function]
KHASH_MAP_INIT_STR(s, int)
^
./khash.h:484:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:140:21: note: expanded from macro 'KHASH_INIT'
        static inline void kh_clear_##name(kh_##name##_t *h...
                           ^
<scratch space>:84:1: note: expanded from here
kh_clear_s
^
index.c:35:1: warning: unused function 'kh_del_s' [-Wunused-function]
./khash.h:484:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:259:21: note: expanded from macro 'KHASH_INIT'
        static inline void kh_del_##name(kh_##name##_t *h, khint_t x...
                           ^
<scratch space>:98:1: note: expanded from here
kh_del_s
^
4 warnings generated.
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE  bedidx.c -o bedidx.o
bedidx.c:20:1: warning: unused function 'kh_clear_reg' [-Wunused-function]
KHASH_MAP_INIT_STR(reg, bed_reglist_t)
^
./khash.h:484:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:140:21: note: expanded from macro 'KHASH_INIT'
        static inline void kh_clear_##name(kh_##name##_t *h...
                           ^
<scratch space>:238:1: note: expanded from here
kh_clear_reg
^
bedidx.c:20:1: warning: unused function 'kh_del_reg' [-Wunused-function]
./khash.h:484:2: note: expanded from macro 'KHASH_MAP_INIT_STR'
        KHASH_INIT(name, kh_cstr_t, khval_t, 1, kh_str_hash_func, kh_str...
        ^
./khash.h:259:21: note: expanded from macro 'KHASH_INIT'
        static inline void kh_del_##name(kh_##name##_t *h, khint_t x...
                           ^
<scratch space>:2:1: note: expanded from here
kh_del_reg
^
2 warnings generated.
ar -cru libtabix.a bgzf.o kstring.o knetfile.o index.o bedidx.o
ranlib libtabix.a
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE  main.c -o main.o
gcc -g -Wall -O2 -fPIC  -o tabix main.o -lm  -L. -ltabix -lz
gcc -c -g -Wall -O2 -fPIC  -D_FILE_OFFSET_BITS=64 -D_USE_KNETFILE  bgzip.c -o bgzip.o
gcc -g -Wall -O2 -fPIC  -o bgzip bgzip.o bgzf.o knetfile.o -lz
g++ -g -Wall -O2 -fPIC  -c tabix.cpp
g++ -g -Wall -O2 -fPIC  -o tabix++ main.cpp tabix.o bgzf.o -lm  -L. -ltabix -lz
g++ -c -o src/Variant.o src/Variant.cpp -I. -L. -Ltabixpp/ -lvcflib -ltabix -lz -lm -O3 -D_FILE_OFFSET_BITS=64
clang: warning: -lvcflib: 'linker' input unused
clang: warning: -ltabix: 'linker' input unused
clang: warning: -lz: 'linker' input unused
clang: warning: -lm: 'linker' input unused
clang: warning: argument unused during compilation: '-L.'
clang: warning: argument unused during compilation: '-Ltabixpp/'
src/Variant.cpp:214:5: warning: control may reach end of non-void function
      [-Wreturn-type]
    }
    ^
src/Variant.cpp:336:5: warning: control may reach end of non-void function
      [-Wreturn-type]
    }
    ^
src/Variant.cpp:370:5: warning: control may reach end of non-void function
      [-Wreturn-type]
    }
    ^
src/Variant.cpp:408:5: warning: control may reach end of non-void function
      [-Wreturn-type]
    }
    ^
4 warnings generated.
g++ -c -o src/split.o src/split.cpp -I. -L. -Ltabixpp/ -lvcflib -ltabix -lz -lm -O3 -D_FILE_OFFSET_BITS=64
clang: warning: -lvcflib: 'linker' input unused
clang: warning: -ltabix: 'linker' input unused
clang: warning: -lz: 'linker' input unused
clang: warning: -lm: 'linker' input unused
clang: warning: argument unused during compilation: '-L.'
clang: warning: argument unused during compilation: '-Ltabixpp/'
cd smithwaterman && /Applications/Xcode.app/Contents/Developer/usr/bin/make
c++    -c -o smithwaterman.o smithwaterman.cpp
c++    -c -o BandedSmithWaterman.o BandedSmithWaterman.cpp
c++    -c -o SmithWatermanGotoh.o SmithWatermanGotoh.cpp
c++    -c -o Repeats.o Repeats.cpp
c++    -c -o LeftAlign.o LeftAlign.cpp
LeftAlign.cpp:679:26: warning: '&&' within '||' [-Wlogical-op-parentheses]
            && (indel.insertion && indel.position == referenceSequence.size()
                ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
LeftAlign.cpp:679:26: note: place parentheses around the '&&' expression to
      silence this warning
            && (indel.insertion && indel.position == referenceSequence.size()
                                ^
                (                                                            )
1 warning generated.
c++    -c -o IndelAllele.o IndelAllele.cpp
g++ -c -o disorder.o disorder.c
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated
- linking smithwaterman
  ld: warning: option -s is obsolete and being ignored
  ld: internal error: atom not found in symbolIndex(__ZNKSt3__16vectorINS_4pairIicEENS_9allocatorIS2_EEE8max_sizeEv) for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  make[1]: **\* [smithwaterman] Error 1
  make: **\* [smithwaterman/SmithWatermanGotoh.o] Error 2

**Comment by ekg** [comment]
I think you may be able to work around this by using gcc. I need to build against clang myself to figure out what's going on. What clang version do you use on the mac?

**Comment by jzook** [comment]
It looks like 600.0.56.  See the full output below

$clang --version

Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)

Target: x86_64-apple-darwin13.4.0

Thread model: posix

Thanks!

**Comment by nh13** [comment]
Just hit this on Ubuntu 14 using `g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4`.
