### ISSUE TITLE
vcffilter crashes instantly if -f isn't specified on the command line

### ISSUE THREAD

**Issue by leecbaker** [vcflib/vcflib#86]
Running vcffilter with a parameter, but no -f, causes an instant crash. Perhaps at least an error should be printed?

Crash comes from src/vcffilter:200:

```
 filterSpec = filterSpec.substr(1); // strip leading " "
```

because filterSpec is empty.

**Comment by tseemann** [comment]
Possibly related to https://github.com/ekg/vcflib/issues/80

**Comment by zeeev** [comment]
@leecbaker fixed.  

bin/vcffilter your.vcf.gz

Argument -g or -f is required
