### ISSUE TITLE
vcfstats gives Segmentation fault

### ISSUE THREAD

**Issue by kbentele** [vcflib/vcflib#89]
Hi,
I am using the current vcflib (downloaded on 2015/04/16) compiled in CentOS7
( CentOS Linux release 7.1.1503, kernel 3.10.0-229.1.2.el7.x86_64) 

When I try to run vcfstats on a vcf file generated by freebayes I get a Segmentation fault. The same is true for the shipped sample.vcf:

$ ../bin/vcfstats sample.vcf 
Segmentation fault

Thanks a lot for any help,
Kajetan

**Comment by nekrut** [comment]
+1

**Comment by ekg** [comment]
It seems to be broken.

If you are looking for the same functionality, but with an even better interface, use [`vt peek`](https://github.com/atks/vt). Otherwise, I'll address this as time allows, but my motivation is low as vt is doing so much better a job here.

**Comment by HuaLing1** [comment]
same here. other commands are fine except for the vcfstats

**Comment by zeeev** [comment]
@nekrut @kajetanb  I know this is very late, but I have a fix.  I'd like to test it.  Do you have an old vcfstat output and vcf for me to test?

**Comment by zeeev** [comment]
@HuaLing1 @ekg @nekrut @kajetanb fixed.  Cheers.
