### ISSUE TITLE
vcfbiallelic - removes them rather then selects them?

### ISSUE THREAD

**Issue by tseemann** [vcflib/vcflib#90]
Is the logic correct in this script?

https://github.com/ekg/vcflib/blob/master/bin/vcfbiallelic

```
if ($alt =~ /,/) {
        # remove anything which isn't biallelic
    } else {
        print;
    }
```

**Comment by ekg** [comment]
No, it should say the opposite. However, it looks like it's doing the right
thing.

**Comment by tseemann** [comment]
Shouldn't it be called "vcf**notmulti**allelic" then?

**Comment by tseemann** [comment]
Suggest:
```
# remove anything which isn't biallelic
print unless $alt =~ /,/;
```
