### ISSUE TITLE
Problem in installation

### ISSUE THREAD

**Issue by asifzubair** [vcflib/vcflib#91]
Hi, 

I get the following error when I am installing:

``` shell
cd tabixpp && /Applications/Xcode.app/Contents/Developer/usr/bin/make
ar -cru libtabix.a 
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
    ar -m [-TLsv] archive file ...
    ar -m [-abiTLsv] position archive file ...
    ar -p [-TLsv] archive [file ...]
    ar -q [-cTLsv] archive file ...
    ar -r [-cuTLsv] archive file ...
    ar -r [-abciuTLsv] position archive file ...
    ar -t [-TLsv] archive [file ...]
    ar -x [-ouTLsv] archive [file ...]
make[2]: *** [libtabix.a] Error 1
make[1]: *** [all-recur] Error 1
make: *** [tabixpp/tabix.o] Error 2
```

I did clone 'recursively' from git and just ran the make command. 

I'm using a mac, can I use brew to install ?

**Comment by wrshoemaker** [comment]
Using brew I'm getting a similar error. 

```
      ar -t [-TLsv] archive [file ...]
      ar -x [-ouTLsv] archive [file ...]
 make[2]: *** [libtabix.a] Error 1
 make[1]: *** [all-recur] Error 1
 make: *** [tabixpp/tabix.o] Error 2
```

I've been keeping my eye on the homebrew-science page and waiting for it to be merged. 
https://github.com/Homebrew/homebrew-science/pull/2092

**Comment by koenvandenberge** [comment]
Similar error here.

Using Mac OS X Yosemite 10.10.3

**Comment by navarretemarce** [comment]
Same error here. Using Mac OS X Yose 10.10.3

**Comment by jharenza** [comment]
Same error Mac OSX Mav 10.9.5

**Comment by tseemann** [comment]
@wrshoemaker vcflib with the patches in now in Homebrew and works on Linux and OSX. It's up to date with 3 June 2015.

The actual issue is here: https://github.com/ekg/tabixpp/issues/5

**Comment by danielecook** [comment]
The installation doesn't link all the tools. For example vcffixup was not linked.

**Comment by tseemann** [comment]
@danielecook do you mean vcffixup was not linked in this vcflib package or in the homebrew package or both?

**Comment by zeeev** [comment]
@asifzubair @wrshoemaker @koenvandenberge @danielecook Master builds on OS X.  Added OS X to travis-ci.
