### ISSUE TITLE
Possibly include Zev Kronenberg's tools (pFst ect.)

### ISSUE THREAD

**Issue by travc** [vcflib/vcflib#93]
Zev Kronenberg (jewmanchue) has a set of nice tools based on vcflib called GAPT++
https://github.com/jewmanchue/vcflib/wiki

I've reorganized his code to make it 'stand-beside' vcflib (suitable for inclusion as a submodule):
https://github.com/travc/GPAT

It seems like a reasonable idea (to me at least) to include GPAT as a submodule in the official vcflib. 
It is his and your (ekg's) call of course.

Even if it isn't included, others may find it useful... Just clone it within the vcflib directory, or even clone it someplace else and change the VCFLIB_PATH variable at the top of the Makefile.

My fork of vcflib includes GPAT as a submodule and the Makefile has been modified to compile it:
https://github.com/travc/vcflib/tree/GPAT

**Comment by ekg** [comment]
Yes ++++. I will pull this in if you can provide a patch. In fact Zev and I
have talked about it before.

**Comment by travc** [comment]
It is ready to merge, but I think you or Zev should be the owner of the GPAT repository (which is linked as a submodule).  He seems amenable, but is travelling at the moment.

Anyway, I think this link will create a pull request / patch.
https://github.com/ekg/vcflib/compare/master...travc:GPAT?expand=1

**Comment by zeeev** [comment]
@travc thanks. done.
