### ISSUE TITLE
very large del,del hangs vcfallelicprimitives

### ISSUE THREAD

**Issue by travc** [vcflib/vcflib#94]
This is an odd use case, so not really a bug per-se.  However, it might crop up in other situations given how freebayes really likes to make long complex calls...

I'm running RNAseq data (tophat hacked to change CIGAR N's to D's), which seems to be working mostly ok.  But I hit one rare snag:

`vcfallelicprimitives` is hanging (or at least taking a ridiculously long time) on one particular variant line: 
I think the relevant part is `TYPE=del,del` and `LEN=19323,19332`
Yeah, that is an intron which should be N, but I recoded to D so I could call with freebayes.

A vcf containing just that line is:
https://popi.ucdavis.edu/~travc/tmp/hangs_vcfallelicprimitives.vcf

... Additionally ...
Can `vcffilter` handle those multi-value fields properly?  The docs on it should probably be updated to clarify.

**Comment by zeeev** [comment]
@travc I'm starting to attack bugs.  Can you provide the command line you used and I will see what I can do.

**Comment by ekg** [comment]
Any example with a long deletion should trigger the problem. It is using
pairwise alignment to derive a reduced representation of the differences
and this is quadratic in space.

**Comment by zeeev** [comment]
@ekg I could skip variants if the INFO line has abs(POS - END) > X?  Or would that be a lousy hack?

**Comment by ekg** [comment]
Maybe we just set a maximum. Beyond 1000 even, I don't know if we should
attempt to decompose. Shorter even might make sense. Like, 100.

**Comment by pjotrp** [comment]
We introduced wavefront as an aligner and this problem should be solved. Also the -L switch behaves properly on master.
