### ISSUE TITLE
Please tag a stable release

### ISSUE THREAD

**Issue by sjackman** [vcflib/vcflib#95]
Please tag a stable release for the Homebrew formula.
See https://github.com/Homebrew/homebrew-science/pull/2092

**Comment by ekg** [comment]
https://github.com/ekg/vcflib/releases/tag/v1.0.0-rc0

**Comment by ekg** [comment]
I guess I can just do 1.0.0, no?

**Comment by sjackman** [comment]
This issue is a duplicate of #76.
