### ISSUE TITLE
vcfaddinfo skips chroms 10 and above in usegalaxy instance

### ISSUE THREAD

**Issue by mchimenti** [vcflib/vcflib#96]
I am seeing an issue where vcfaddinfo adds new info fields only for chroms 1-9 and X/Y.  For some reason, there seems to be a bug where it is skipping chroms 10-22, even though my second VCF file from which I am adding the INFO field contains variants at these positions.

**Comment by ekg** [comment]
I think it is depending on the input being sorted in ascending order as per
`sort --version-sort`.

**Comment by mchimenti** [comment]
Thank you for your reply.  Could you briefly elaborate?  Do both files need to be sorted in the same way?  

Ascending order sort gives:

Chr1
Chr10
Chr11
...
Chr19
Chr2
Chr20
Chr21
Chr22
Chr3
.....
etc...

Is this correct?

**Comment by ekg** [comment]
I think they need to be sorted the same way. Is this the case?

**Comment by mchimenti** [comment]
Yes, sorting both VCF files in ascending order does help, i.e., "vcfaddinfo" is no longer skipping chroms 10-22.  Unfortunately, it only adds about 50% of the missing annotations.  There doesn't seem to be a pattern to which ones are skipped.
